import { Body,Controller,Delete,Get,Param,Patch,Post,Req,UseGuards } from "@nestjs/common";
import { Request } from "express";
import { RequirePermission } from "../../common/authorization/decorators/require-permission.decorator";
import { PermissionGuard } from "../../common/authorization/guards/permission.guard";
import { AuthGuard } from "../auth/guards/auth.guard";
import { FinanceResource,FinanceService } from "./finance.service";
@UseGuards(AuthGuard,PermissionGuard) class Base {constructor(public readonly service:FinanceService){}user(r:Request){if(!r.user)throw new Error("Authenticated user missing");return r.user.id;}}
function controller(path:string,resource:FinanceResource,permission:string){@Controller(path)class ResourceController extends Base {@Get()@RequirePermission(`${permission}.read`)list(@Req()r:Request){return this.service.list(this.user(r),resource);}@Post()@RequirePermission(`${permission}.create`)create(@Req()r:Request,@Body()b:Record<string,unknown>){return this.service.create(this.user(r),resource,b);}@Patch(":id")@RequirePermission(`${permission}.update`)update(@Req()r:Request,@Param("id")id:string,@Body()b:Record<string,unknown>){return this.service.update(this.user(r),resource,id,b);}@Delete(":id")@RequirePermission(`${permission}.delete`)remove(@Req()r:Request,@Param("id")id:string){return this.service.remove(this.user(r),resource,id);}}return ResourceController;}
export const AccountsController=controller("finance/accounts","finance_accounts","finance_accounts");export const CategoriesController=controller("finance/categories","finance_categories","finance_categories");export const PeriodsController=controller("finance/periods","finance_periods","finance_periods");export const BillsController=controller("finance/bills","student_bills","billing");export const PaymentsController=controller("finance/payments","payments","payments");
@Controller("finance/dashboard")@UseGuards(AuthGuard,PermissionGuard)export class DashboardController extends Base {@Get()@RequirePermission("finance_reports.read")dashboard(@Req()r:Request){return this.service.dashboard(this.user(r));}}
