"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, Search } from "lucide-react";
import { schoolRpc, useSchoolContext } from "../../lib/school";
import { RecordWorkspace, type ResourceSpec } from "../school/record-workspace";
import { usePermissionStore } from "../../stores/permission-store";
import { Button, Input, Select } from "../ui";
const specs: ResourceSpec[] = [
 {key:"finance_accounts",title:"Rekening",path:"/finance/accounts",permission:"finance_accounts",fields:[{key:"name",label:"Nama rekening"},{key:"account_type",label:"Jenis",options:["CASH","BANK","RECEIVABLE"]},{key:"is_active",label:"Aktif",type:"checkbox"}]},
 {key:"finance_categories",title:"Kategori",path:"/finance/categories",permission:"finance_categories",fields:[{key:"name",label:"Kategori"},{key:"category_type",label:"Jenis",options:["INCOME","EXPENSE"]},{key:"is_active",label:"Aktif",type:"checkbox"}]},
 {key:"finance_periods",title:"Periode",path:"/finance/periods",permission:"finance_periods",fields:[{key:"name",label:"Periode"},{key:"starts_on",label:"Mulai",type:"date"},{key:"ends_on",label:"Selesai",type:"date"},{key:"is_closed",label:"Ditutup",type:"checkbox"}]},
 {key:"student_bills",title:"Tagihan",path:"/finance/bills",permission:"billing",fields:[{key:"student_id",label:"Siswa",catalog:"students"},{key:"category_id",label:"Kategori",catalog:"finance:finance_categories"},{key:"period_id",label:"Periode",catalog:"finance:finance_periods",optional:true},{key:"invoice_number",label:"Nomor tagihan"},{key:"amount",label:"Nilai (Rp)",type:"number",min:1},{key:"due_date",label:"Jatuh tempo",type:"date"},{key:"status",label:"Status",options:["DRAFT","OPEN","VOID"]}]},
 {key:"payments",title:"Pembayaran",path:"/finance/payments",permission:"payments",fields:[{key:"student_bill_id",label:"Tagihan siswa",catalog:"finance:student_bills"},{key:"account_id",label:"Rekening",catalog:"finance:finance_accounts"},{key:"receipt_number",label:"Nomor kuitansi"},{key:"amount",label:"Nilai (Rp)",type:"number",min:1},{key:"paid_at",label:"Waktu bayar",type:"datetime-local"},{key:"reference",label:"Referensi",optional:true},{key:"status",label:"Status",options:["PENDING","CONFIRMED","VOID","REFUNDED"]}]},
];
const rupiah = (n: number) => new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
type Report = {count:number;total:number;paid?:number;outstanding?:number;rows:{id:string;invoice_number:string;receipt_number?:string;student_name:string;amount:number;due_date?:string;paid_at?:string;status:string}[]};
export function FinanceManager() {
 const school=useSchoolContext();const has=usePermissionStore(s=>s.has);const [tab,setTab]=useState("report");const allowed=specs.filter(s=>has(`${s.permission}.read`));
 return <section><div className="school-tabs" role="tablist" aria-label="Keuangan"><button role="tab" aria-selected={tab==="report"} onClick={()=>setTab("report")}>Laporan & tagihan</button>{school.data?.staff&&allowed.length>0&&<button role="tab" aria-selected={tab==="manage"} onClick={()=>setTab("manage")}>Kelola transaksi</button>}</div>{tab==="report"?<FinanceReport/>:allowed.length>0&&<RecordWorkspace specs={allowed}/> }</section>;
}
function FinanceReport() {
 const school=useSchoolContext(); const [resource,setResource]=useState("bills"); const [from,setFrom]=useState(()=>`${new Date().getFullYear()}-01-01`); const [to,setTo]=useState(()=>`${new Date().getFullYear()}-12-31`); const [search,setSearch]=useState(""); const [query,setQuery]=useState("");const [status,setStatus]=useState(""); const [page,setPage]=useState(0); const [printing,setPrinting]=useState(false);const [error,setError]=useState("");
 const args={resource,date_from:from,date_to:to,query,status_filter:status};
 const report=useQuery({queryKey:["school-finance",school.data?.tenant.id,args,page],enabled:!!school.data&&!!from&&!!to,queryFn:()=>schoolRpc<Report>("school_finance_report",{...args,page_offset:page*100})});
 async function print(){setPrinting(true);setError("");try{const all:Report["rows"]=[];for(let offset=0;offset<(report.data?.count??0);offset+=100){const r=await schoolRpc<Report>("school_finance_report",{...args,page_offset:offset});all.push(...r.rows);}const { reportPdf, downloadPdf } = await import("../../lib/school-pdf"); const bytes = await reportPdf(resource === "bills" ? "Laporan tagihan" : "Laporan pembayaran", `${school.data?.tenant.name ?? "OSEKOLA"} | ${from} - ${to}`, [`Jumlah transaksi: ${all.length}`, `Total: ${rupiah(report.data?.total ?? 0)}`, ...(report.data?.outstanding !== undefined ? [`Sisa tagihan: ${rupiah(report.data.outstanding)}`] : [])], all.map(r => [r.receipt_number ?? r.invoice_number, r.student_name, r.due_date ?? new Date(r.paid_at!).toLocaleDateString("id-ID"), r.status, rupiah(r.amount)])); downloadPdf(bytes, `osekola-${resource}-${from}-${to}.pdf`);}catch(e){setError(e instanceof Error?e.message:"Gagal menyiapkan laporan");}finally{setPrinting(false);}}
 return <div className="school-workspace school-finance-report"><div className="school-section-title"><div><p className="ose-eyebrow">O-FINANCE</p><h2>{school.data?.staff?"Laporan keuangan":"Tagihan keluarga"}</h2><p>{school.data?.tenant.name} · {from} — {to}</p></div><Button disabled={printing||!report.data?.count} onClick={()=>void print()}><Download size={16}/>{printing?"Menyiapkan…":"Download PDF"}</Button></div><form className="school-toolbar" onSubmit={e=>{e.preventDefault();setQuery(search);setPage(0);}}><Select aria-label="Laporan" value={resource} onChange={e=>{setResource(e.target.value);setStatus("");setPage(0);}}><option value="bills">Tagihan</option><option value="payments">Pembayaran</option></Select><Input aria-label="Dari tanggal" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(0);}}/><Input aria-label="Sampai tanggal" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(0);}}/><Select aria-label="Status" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">Semua status</option>{(resource==="bills"?["DRAFT","OPEN","PARTIAL","PAID","VOID"]:["PENDING","CONFIRMED","VOID","REFUNDED"]).map(s=><option key={s}>{s}</option>)}</Select><label className="school-search"><Search size={16}/><input value={search} aria-label="Cari siswa atau nomor" placeholder="Nama siswa / nomor transaksi" onChange={e=>setSearch(e.target.value)}/></label><Button type="submit" variant="ghost">Cari</Button></form>{(report.isError||error)&&<p role="alert" className="school-error">{report.error?.message??error}</p>}{report.isLoading?<p role="status">Memuat laporan…</p>:report.data&&<><div className="school-stat-strip"><div><small>Jumlah transaksi</small><strong>{report.data.count}</strong></div><div><small>{resource==="payments"?"Pembayaran terkonfirmasi":"Total tagihan"}</small><strong>{rupiah(report.data.total)}</strong></div>{report.data.outstanding!==undefined&&<div><small>Sisa tagihan</small><strong>{rupiah(report.data.outstanding)}</strong></div>}</div><div className="school-table-scroll"><table className="school-table"><thead><tr><th>Nomor</th><th>Siswa</th><th>Tanggal</th><th>Status</th><th>Nilai</th></tr></thead><tbody>{report.data.rows.map(r=><tr key={r.id}><td>{r.receipt_number??r.invoice_number}</td><td>{r.student_name}</td><td>{r.due_date??new Date(r.paid_at!).toLocaleDateString("id-ID")}</td><td>{r.status}</td><td>{rupiah(r.amount)}</td></tr>)}</tbody></table>{!report.data.count&&<p className="school-empty">Tidak ada transaksi sesuai filter.</p>}</div><div className="school-pagination"><Button variant="ghost" disabled={!page||report.isFetching} onClick={()=>setPage(p=>p-1)}>←</Button><span>Halaman {page+1} · {report.data.count} transaksi</span><Button variant="ghost" disabled={(page+1)*100>=report.data.count||report.isFetching} onClick={()=>setPage(p=>p+1)}>→</Button></div></>}</div>;
}
