"use client";
import { useState,type FormEvent } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { createClient } from "../../lib/supabase/client";
import { schoolRpc,useCatalog } from "../../lib/school";
import { usePermissionStore } from "../../stores/permission-store";
import { useTranslations } from "../i18n/i18n-provider";
import { Button,Input,Select } from "../ui";
const errors:Record<string,[string,string]>={PAYMENT_NOT_CONFIGURED:["Pembayaran online belum diaktifkan sekolah. Hubungi staf keuangan.","Online payment is not activated. Contact school finance staff."],RECONCILIATION_REQUIRED:["Transaksi sedang diperiksa. Jangan membuat pembayaran lain; hubungi staf bila status belum berubah.","The transaction is being checked. Avoid another payment; contact staff if it remains unresolved."],PROVIDER_UNCERTAIN:["Respons penyedia belum pasti. Periksa kembali status pembayaran.","The provider response is uncertain. Check payment status again."],PAYMENT_ACCESS_OR_STATE_DENIED:["Tagihan tidak tersedia, sudah lunas, atau tidak dapat diakses.","This bill is unavailable, already paid, or outside your access."]};
export function PaymentButton({kind="bill",target,accessToken="",onPaid}:{kind?:"bill"|"admission";target:string;accessToken?:string;onPaid?:()=>void}){
 const {locale}=useTranslations();const id=locale==="id-ID";const cache=useQueryClient();const [message,setMessage]=useState("");const [link,setLink]=useState("");
 const m=useMutation({mutationFn:async()=>{setMessage("");setLink("");const {data,error}=await createClient().functions.invoke("payment-gateway",{body:{kind,target,access_token:accessToken}});if(error){let code="PAYMENT_UNAVAILABLE";try{code=(await error.context.json()).error??code;}catch{}throw new Error(errors[code]?.[id?0:1]??(id?"Pembayaran belum dapat diproses. Coba periksa kembali atau hubungi staf.":"Payment is unavailable. Check again or contact staff."));}if(data.status==="PAID"){setMessage(id?"Pembayaran terkonfirmasi.":"Payment confirmed.");await cache.invalidateQueries({queryKey:["school-finance"]});onPaid?.();}else if(data.checkout_url){const u=new URL(data.checkout_url);if(u.protocol!=="https:"||!["checkout.xendit.co","checkout-staging.xendit.co","xen.to","dev.xen.to","app.midtrans.com","app.sandbox.midtrans.com"].includes(u.hostname))throw new Error("Invalid checkout");setLink(u.href);setMessage(`${data.provider} · ${id?"Lanjutkan pembayaran pada halaman resmi penyedia.":"Continue on the provider's official checkout."}`);}else setMessage(id?"Sesi berakhir. Periksa kembali sebelum mencoba pembayaran baru.":"Session ended. Check again before starting a new payment.");}});
 return <div className="p5-payment-action"><Button size="sm" variant="ghost" disabled={m.isPending} onClick={()=>m.mutate()}>{m.isPending?"…":id?"Bayar / periksa status":"Pay / check status"}</Button>{m.isError&&<p role="alert">{m.error.message}</p>}{message&&<p role="status">{message}</p>}{link&&<a className="ose-link" href={link} target="_blank" rel="noopener noreferrer">{id?"Buka pembayaran aman":"Open secure checkout"} ↗</a>}</div>;
}
type Config={provider:string;account_id:string;is_live:boolean;enabled:boolean;updated_at:string};
export function PaymentGatewaySettings(){
 const {locale,t}=useTranslations();const id=locale==="id-ID";const userId=usePermissionStore(s=>s.context?.userId);const [provider,setProvider]=useState("XENDIT");const q=useQuery({queryKey:["payment-config",userId],queryFn:()=>schoolRpc<Config[]>("school_payment_config_status")});const accounts=useCatalog("finance:finance_accounts");const cache=useQueryClient();const selected=q.data?.find(c=>c.provider===provider);const m=useMutation({mutationFn:(payload:Record<string,unknown>)=>schoolRpc("school_payment_configure",{payload}),onSuccess:async()=>{await cache.invalidateQueries({queryKey:["payment-config"]});}});
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);m.mutate({provider,secret:f.get("secret"),webhook_secret:f.get("webhook_secret"),account_id:f.get("account_id"),is_live:f.get("is_live")==="on",enabled:f.get("enabled")==="on"},{onSuccess:()=>{(document.getElementById("payment-key") as HTMLInputElement).value="";const hook=document.getElementById("payment-hook") as HTMLInputElement|null;if(hook)hook.value="";}});}
 const webhook=`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/payment-gateway/webhook/${provider.toLowerCase()}`;
 return <section className="school-editor"><h2>{id?"Pembayaran online":"Online payments"}</h2><p>{id?"Xendit utama · Midtrans cadangan. Gunakan akun merchant milik sekolah ini.":"Xendit primary · Midtrans backup. Use this school's merchant account."}</p><Select aria-label="Provider" value={provider} onChange={e=>{setProvider(e.target.value);m.reset();}}><option>XENDIT</option><option>MIDTRANS</option></Select>{q.isError&&<p role="alert">{q.error.message}</p>}{!q.isPending&&<form key={provider+(selected?.updated_at??"")} onSubmit={submit} className="owner-form"><p>{selected?(selected.is_live?"LIVE":"SANDBOX")+" · "+(selected.enabled?"ON":"OFF"):(id?"Belum dikonfigurasi":"Not configured")}</p><Select name="account_id" label={id?"Rekening pencatatan":"Ledger account"} defaultValue={selected?.account_id??""} required><option value="">{id?"Pilih rekening":"Choose account"}</option>{accounts.data?.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</Select><Input id="payment-key" name="secret" type="password" autoComplete="new-password" label={id?"Server key (kosongkan untuk mempertahankan)":"Server key (leave blank to keep)"} required={!selected} maxLength={2000}/>{provider==="XENDIT"&&<Input id="payment-hook" name="webhook_secret" type="password" autoComplete="new-password" label="Xendit webhook verification token" required={!selected} maxLength={1000}/>}<label className="school-field"><span>{id?"Daftarkan webhook ini di dashboard penyedia":"Register this webhook in the provider dashboard"}</span><input readOnly value={webhook} onFocus={e=>e.target.select()}/></label><label className="school-consent"><input type="checkbox" name="is_live" defaultChecked={selected?.is_live}/>{id?"Mode produksi (gunakan kredensial live)":"Production mode (use live credentials)"}</label><label className="school-consent"><input type="checkbox" name="enabled" defaultChecked={selected?.enabled??true}/>{id?"Aktifkan penyedia ini":"Enable this provider"}</label><p className="owner-help">{id?"Kunci dienkripsi dan tidak ditampilkan kembali. Selesaikan transaksi tertunda sebelum mengganti akun merchant.":"Keys are encrypted and never shown again. Resolve pending transactions before changing merchant accounts."}</p>{m.isError&&<p role="alert">{m.error.message}</p>}{m.isSuccess&&<p role="status">{id?"Konfigurasi tersimpan. Uji sandbox sebelum menerima pembayaran live.":"Configuration saved. Verify sandbox payments before accepting live payments."}</p>}<Button type="submit" disabled={m.isPending}>{t("save")}</Button></form>}</section>;
}
