"use client";
import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {browserApi} from "../../lib/api/browser";
import {usePermissionStore} from "../../stores/permission-store";
import {useTranslations} from "../i18n/i18n-provider";
import {Button,Input} from "../ui";
import {OwnerDialog} from "../owner/owner-ui";
type Approval={id:string;title:string;status:string;resource_type:string;resource_id:string;current_step:number;approval_steps:{sequence:number;approver_user_id:string;status:string}[]};
export function ApprovalWorkspace(){const {t,locale}=useTranslations();const id=locale==="id-ID";const context=usePermissionStore(s=>s.context);const allowed=context?.roles.some(r=>r.code==="PRINCIPAL");const [page,setPage]=useState(1);const [selected,setSelected]=useState<Approval>();const [note,setNote]=useState("");const cache=useQueryClient();const q=useQuery({queryKey:["approvals",context?.userId,page],enabled:!!allowed,queryFn:()=>browserApi<Approval[]>(`/operations/approvals?page=${page}&page_size=50`)});const m=useMutation({mutationFn:(decision:string)=>browserApi(`/operations/approvals/${selected!.id}/decision`,{method:"POST",body:JSON.stringify({decision,note})}),onSuccess:async()=>{setSelected(undefined);await Promise.all([cache.invalidateQueries({queryKey:["approvals"]}),cache.invalidateQueries({queryKey:["role-dashboard"]})]);}});if(!allowed)return <p>{t("accessLimited")}</p>;
return <section className="school-workspace"><h1>{t("approval")}</h1>{q.isError&&<p role="alert">{q.error.message}</p>}{q.isPending?<p>{t("loading")}</p>:q.data?.length?q.data.map(a=><article key={a.id} className="school-record"><div className="school-record-main"><small>{a.resource_type}</small><h3>{a.title}</h3><p>{a.status}</p></div>{a.status==="PENDING"&&a.approval_steps.some(s=>s.sequence===a.current_step&&s.approver_user_id===context?.userId)&&<Button onClick={()=>{setSelected(a);setNote("");m.reset();}}>{id?"Tinjau":"Review"}</Button>}</article>):<p className="school-empty">{id?"Tidak ada permintaan persetujuan.":"No approval requests."}</p>}<div className="school-pagination"><Button variant="ghost" disabled={page===1} onClick={()=>setPage(p=>p-1)}>←</Button><span>{page}</span><Button variant="ghost" disabled={(q.data?.length??0)<50} onClick={()=>setPage(p=>p+1)}>→</Button></div>{selected&&<OwnerDialog title={selected.title} close={()=>setSelected(undefined)}><p>{selected.resource_type} · {selected.resource_id}</p><p>{id?"Baca rincian permintaan di Operations sebelum mengambil keputusan.":"Read the request details in Operations before deciding."}</p><a className="ose-link" href="/dashboard/operations">{id?"Buka rincian":"Open details"} →</a><Input label={id?"Catatan keputusan":"Decision note"} value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/>{m.isError&&<p role="alert">{m.error.message}</p>}<div className="owner-actions"><Button disabled={m.isPending} onClick={()=>m.mutate("APPROVED")}>{id?"Setujui":"Approve"}</Button><Button variant="danger" disabled={m.isPending||!note.trim()} onClick={()=>m.mutate("REJECTED")}>{id?"Tolak":"Reject"}</Button></div></OwnerDialog>}</section>;
}
