"use client";
import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { schoolRpc,schoolModules } from "../../lib/school";
import { usePermissionStore } from "../../stores/permission-store";
import { useMediaContext,useMediaEntries } from "../media/media-hooks";
import { mediaUrl } from "../../lib/media";
import { Button,Select } from "../ui";
import { browserApi } from "../../lib/api/browser";
import { primaryRole } from "../../lib/modules";
import { Modal } from "../ui/modal";
type Tenant={id:string;name:string;plan_code:string;modules:Record<string,boolean>;users:number;is_active:boolean};
type Approval={id:string;resource_type:string;title:string;status:string;approval_steps:{approver_user_id:string;status:string}[]};
type Dashboard={school:string;students:number;teachers:number|null;classes:number;attendance_today:number;pending_approvals:Approval[]|null;children:{id:string;name:string;number:string;attendance:string|null}[];tenants:Tenant[]};
export function DashboardOverview(){
 const context=usePermissionStore(s=>s.context);const role=primaryRole(context);const q=useQuery({queryKey:["school-dashboard",context?.userId],enabled:!!context,queryFn:()=>schoolRpc<Dashboard>("school_dashboard")});
 if(q.isError)return <p role="alert" className="school-error">{q.error.message}<Button variant="ghost" onClick={()=>void q.refetch()}>Coba lagi</Button></p>;
 if(!q.data)return <p role="status">Memuat ringkasan sekolah…</p>;
 const d=q.data;const metrics=role==="PARENT"||role==="STUDENT"?[["Siswa terhubung",d.children.length],["Kelas",d.classes],["Hadir hari ini",d.attendance_today]]:[["Siswa",d.students],["Guru aktif",d.teachers],["Kelas",d.classes],["Hadir hari ini",d.attendance_today]];
 return <section className="school-dashboard-overview"><div className="school-stat-strip">{metrics.filter(([,n])=>n!==null).map(([label,value])=><div key={String(label)}><small>{label}</small><strong>{value}</strong></div>)}</div>{d.children.length>0&&<div className="school-exam-grid">{d.children.map(child=><article key={child.id}><p className="ose-eyebrow">{child.number}</p><h3>{child.name}</h3><p>Presensi hari ini: {child.attendance??"Belum tercatat"}</p><div className="school-quick-links"><Link href="/dashboard/learning">Tugas</Link><Link href="/dashboard/exams">Hasil ujian</Link><Link href="/dashboard/finance">Tagihan</Link><Link href="/dashboard/connect">Hubungi guru</Link></div></article>)}</div>}{["OWNER","PRINCIPAL","STAFF"].includes(role)&&<ApprovalQueue approvals={d.pending_approvals??[]}/>}<SchoolGallery/>{d.tenants.length>0&&<section className="school-workspace"><div className="school-section-title"><div><p className="ose-eyebrow">PLATFORM OWNER</p><h2>Sekolah & paket layanan</h2></div><Link className="ose-link" href="/dashboard/partners">Bisnis, partner & penawaran →</Link></div>{d.tenants.map(t=><TenantPlan key={t.id+JSON.stringify(t.modules)+t.plan_code} tenant={t}/>)}</section>}</section>;
}
function ApprovalQueue({approvals}:{approvals:Approval[]}){const uid=usePermissionStore(s=>s.context?.userId);const qc=useQueryClient();const [selected,setSelected]=useState<Approval>();const [note,setNote]=useState("");const save=useMutation({mutationFn:(decision:string)=>browserApi(`/operations/approvals/${selected?.id}/decision`,{method:"POST",body:JSON.stringify({decision,note})}),onSuccess:async()=>{setSelected(undefined);setNote("");await qc.invalidateQueries({queryKey:["school-dashboard"]});}});const pending=approvals.filter(a=>a.status==="PENDING");return <section className="school-editor"><div className="school-section-title"><h2>Menunggu persetujuan</h2><Link href="/dashboard/operations" className="ose-link">Semua permintaan →</Link></div>{pending.length?pending.map(a=><div key={a.id} className="school-record"><strong className="school-record-main">{a.title}</strong>{a.approval_steps.some(s=>s.approver_user_id===uid&&s.status==="PENDING")?<Button variant="ghost" onClick={()=>{setSelected(a);save.reset();}}>Tinjau</Button>:<span>Menunggu peninjau</span>}</div>):<p>Tidak ada permintaan tertunda pada daftar Anda.</p>}<Modal isOpen={!!selected} onClose={()=>setSelected(undefined)} title="Tinjau permintaan"><h3>{selected?.title}</h3><p>Buka pusat operasional untuk membaca rincian permintaan sebelum mengambil keputusan.</p><Link className="ose-link" href="/dashboard/operations">Buka rincian →</Link><label className="school-field"><span>Catatan keputusan</span><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/></label>{save.isError&&<p role="alert">{save.error.message}</p>}<div className="flex gap-3"><Button disabled={save.isPending} onClick={()=>save.mutate("APPROVED")}>Setujui</Button><Button variant="ghost" disabled={save.isPending||!note.trim()} onClick={()=>save.mutate("REJECTED")}>Tolak</Button></div></Modal></section>;}
function TenantPlan({tenant}:{tenant:Tenant}){const qc=useQueryClient();const [plan,setPlan]=useState(tenant.plan_code);const [flags,setFlags]=useState(tenant.modules);const save=useMutation({mutationFn:()=>schoolRpc("school_settings_save",{target_tenant:tenant.id,plan,module_flags:flags}),onSuccess:async()=>{await Promise.all([qc.invalidateQueries({queryKey:["school-dashboard"]}),qc.invalidateQueries({queryKey:["school-context"]})]);}});return <form className="school-tenant-plan" onSubmit={e=>{e.preventDefault();save.mutate();}}><div><h3>{tenant.name}</h3><p>{tenant.users} pengguna aktif · {tenant.is_active?"Aktif":"Nonaktif"}</p></div><Select aria-label={`Paket ${tenant.name}`} value={plan} onChange={e=>setPlan(e.target.value)}>{["ESSENTIAL","ELEVATE","ENTERPRISE"].map(p=><option key={p}>{p}</option>)}</Select><div className="school-module-flags">{schoolModules.map(([key,name])=><label key={key}><input type="checkbox" checked={flags[key]!==false} onChange={e=>setFlags(v=>({...v,[key]:e.target.checked}))}/>{name}</label>)}</div><Button disabled={save.isPending}>Simpan paket & modul</Button>{save.isError&&<p role="alert">{save.error.message}</p>}</form>;}
function SchoolGallery(){const {data:ctx}=useMediaContext();const prefix=ctx?.tenant_id?`${ctx.tenant_id}/gallery`:undefined;const {data,error}=useMediaEntries("tenant-media",prefix);return <section className="school-dashboard-gallery"><div className="school-section-title"><h2>Galeri sekolah</h2><Link href="/dashboard/media" className="ose-link">Kelola galeri →</Link></div>{error?<p role="alert">Galeri belum dapat dimuat.</p>:data?.filter(f=>f.id).length?<div>{data.filter(f=>f.id).slice(0,6).map(f=><Image unoptimized key={f.id} src={mediaUrl("tenant-media",`${prefix}/${f.name}`,f.updated_at)} width={320} height={200} alt={f.name.replace(/^[a-f0-9-]{36}-/,"")}/>)}</div>:<p className="school-empty">Dokumentasikan kegiatan sekolah melalui Pusat Media.</p>}</section>;}
