"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Clock, Save, Send, ShieldCheck } from "lucide-react";
import { schoolRpc, useSchoolContext } from "../../lib/school";
import type { QuestionContent } from "../../lib/question-schema";
import { Button, Input, Select } from "../ui";
import { QuestionDiagram } from "./question-diagram";
import { RecordWorkspace } from "./record-workspace";
import { QuestionWorkspace } from "./question-workspace";
type Exam = { id: string; title: string; course_id: string; starts_at: string; ends_at: string; status: string; can_manage: boolean; question_count: number; attempt_status: string | null; can_take: boolean; child_results: { id: string; name: string; score: number }[] };
type Attempt = { id: string; status: string; answers: Record<string, string>; revision: number; score: number | null; feedback: string | null };
type ExamState = { attempt: Attempt; title: string; ends_at: string; server_time: string; can_manage: boolean; questions: { id: string; position: number; content: QuestionContent }[] };
type AttemptSummary = { id: string; full_name: string; status: string; score: number | null; submitted_at: string | null };
const examSpec = [{ key: "exams", title: "Jadwal ujian", path: "/exams", permission: "exams", fields: [{ key: "course_id", label: "Course", catalog: "courses" }, { key: "title", label: "Judul" }, { key: "description", label: "Deskripsi", type: "textarea", optional: true }, { key: "starts_at", label: "Mulai", type: "datetime-local" }, { key: "ends_at", label: "Selesai", type: "datetime-local" }] }];
export function ExamWorkspace() {
 const school = useSchoolContext(); const qc = useQueryClient(); const [tab, setTab] = useState("exams"); const [taking, setTaking] = useState<ExamState>(); const [manage, setManage] = useState<Exam>();
 const q = useQuery({ queryKey: ["school-exams", school.data?.tenant.id], enabled: !!school.data, queryFn: () => schoolRpc<Exam[]>("school_exam_list"), refetchInterval: 30000 });
 const start = useMutation({ mutationFn: (id: string) => schoolRpc<ExamState>("school_exam_start", { exam_uuid: id }), onSuccess: setTaking });
 if (taking) return <ExamPlayer key={taking.attempt.id} initial={taking} onExit={() => { setTaking(undefined); void qc.invalidateQueries({ queryKey: ["school-exams"] }); }}/>;
 return <section><nav className="school-tabs" role="tablist" aria-label="Exam sections">{[["exams", "Ujian saya"], ...(school.data?.educator ? [["schedule", "Kelola jadwal"], ["bank", "Bank soal"]] : []), ["admissions", "PPDB / SPMB"]].map(([key, label]) => <button role="tab" key={key} aria-selected={tab === key} onClick={() => { setTab(key); setManage(undefined); }}>{label}</button>)}</nav>{tab === "schedule" && <RecordWorkspace specs={examSpec}/>} {tab === "bank" && <QuestionWorkspace/>}{tab === "admissions" && <div className="school-empty"><h2>Penerimaan siswa baru</h2><p>Ruang PPDB / SPMB akan dikembangkan pada tahap penerimaan siswa baru.</p></div>}
 {tab === "exams" && <div className="school-workspace"><div className="school-section-title"><div><p className="ose-eyebrow">FOCUS ON YOUR NEXT STEP</p><h2>Ruang ujian</h2><p>Jawaban disimpan berkala. Buka kembali ujian yang sama untuk melanjutkan.</p></div><ShieldCheck size={30} className="text-secondary"/></div>{(q.isError || start.isError) && <p role="alert" className="school-error">{q.error?.message ?? start.error?.message}</p>}{q.isLoading ? <p role="status">Memuat ujian…</p> : q.data?.length ? <div className="school-exam-grid">{q.data.map(exam => <article key={exam.id}><span className="ose-eyebrow">{exam.status}</span><h3>{exam.title}</h3><p>{exam.question_count} soal</p><p><Clock size={15}/>{exam.starts_at ? new Date(exam.starts_at).toLocaleString("id-ID") : "Belum dijadwalkan"}</p>{exam.can_manage ? <Button onClick={() => setManage(exam)}>Kelola soal & hasil</Button> : exam.can_take ? <Button disabled={start.isPending || !exam.question_count} onClick={() => start.mutate(exam.id)}>{exam.attempt_status ? "Buka kembali" : "Mulai ujian"}</Button> : <div>{exam.child_results.length ? exam.child_results.map(r => <p key={r.id}>{r.name}: {r.score}/100</p>) : <p>Hasil anak akan tersedia setelah dinilai.</p>}</div>}</article>)}</div> : <div className="school-empty">Belum ada ujian untuk kelas Anda.</div>}{manage && <ExamManagement key={manage.id} exam={manage}/>}</div>}</section>;
}
function ExamManagement({ exam }: { exam: Exam }) {
 const qc = useQueryClient(); const [setId, setSetId] = useState(""); const [chosen, setChosen] = useState<string[]>([]); const [review, setReview] = useState<ExamState>();
 const sets = useQuery({ queryKey: ["exam-question-bank", setId], queryFn: () => schoolRpc<{ sets: { id: string; title: string; course_id: string }[]; items: (QuestionContent & { id: string; review_status: string })[] }>("school_question_bank", { set_uuid: setId || null }) });
 const attempts = useQuery({ queryKey: ["exam-attempts", exam.id], queryFn: () => schoolRpc<AttemptSummary[]>("school_exam_attempts", { exam_uuid: exam.id }), refetchInterval: 15000 });
 const action = useMutation({ mutationFn: (name: string) => schoolRpc("school_exam_manage", { action: name, exam_uuid: exam.id, payload: name === "questions" ? chosen : {} }), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["school-exams"] }); } });
 const grade = useMutation({ mutationFn: (payload: Record<string, unknown>) => schoolRpc("school_exam_grade", payload), onSuccess: async () => { setReview(undefined); await qc.invalidateQueries({ queryKey: ["exam-attempts"] }); } });
 const inspect = useMutation({ mutationFn: (id: string) => schoolRpc<ExamState>("school_exam_state", { attempt_uuid: id }), onSuccess: setReview });
 return <div className="school-editor mt-6"><h2>{exam.title}</h2><p>Soal yang dipasang disalin ke naskah ujian. Perubahan bank soal berikutnya tidak mengubah naskah ujian yang sudah dipublikasikan.</p>{exam.status === "DRAFT" && <><Select aria-label="Bank soal" value={setId} onChange={e => setSetId(e.target.value)}><option value="">Pilih bank soal dari course yang sama</option>{sets.data?.sets.filter(s => s.course_id === exam.course_id).map(s => <option key={s.id} value={s.id}>{s.title}</option>)}</Select>{sets.data?.items.filter(q => q.review_status === "APPROVED").map(question => <label className="school-consent" key={question.id}><input type="checkbox" checked={chosen.includes(question.id)} onChange={e => setChosen(v => e.target.checked ? [...v, question.id] : v.filter(id => id !== question.id))}/>{question.prompt}</label>)}<div className="flex gap-3"><Button disabled={!chosen.length || action.isPending} onClick={() => action.mutate("questions")}>Pasang {chosen.length} soal</Button><Button variant="ghost" disabled={action.isPending} onClick={() => action.mutate("publish")}>Publikasikan ujian</Button></div></>}{exam.status === "PUBLISHED" && <Button variant="ghost" disabled={action.isPending} onClick={() => { if (confirm("Tutup ujian sekarang? Siswa hanya dapat mengumpulkan jawaban terakhir yang sudah tersimpan.")) action.mutate("close"); }}>Tutup ujian</Button>}{[action, grade, inspect].some(q => q.isError) && <p role="alert" className="school-error">{action.error?.message ?? grade.error?.message ?? inspect.error?.message}</p>}<h3>Progres & hasil siswa</h3>{attempts.data?.map(a => <article key={a.id} className="school-record"><div className="school-record-main"><strong>{a.full_name}</strong><p>{a.status} · {a.score == null ? "Menunggu penilaian" : `${a.score}/100`}</p></div><Button variant="ghost" disabled={inspect.isPending} onClick={() => inspect.mutate(a.id)}>Tinjau</Button></article>)}{review && <form className="school-editor" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); grade.mutate({ attempt_uuid: review.attempt.id, final_score: Number(f.get("score")), note: f.get("feedback") }); }}><h3>Penilaian jawaban</h3>{review.questions.map(q => <article key={q.id}><strong>{q.position}. {q.content.prompt}</strong><p>Jawaban siswa: {review.attempt.answers[q.id] ?? "—"}</p><p className="text-sm text-muted">Kunci / rubrik: {q.content.answer}</p></article>)}<Input name="score" label="Nilai akhir / 100" type="number" min={0} max={100} step="0.01" defaultValue={review.attempt.score ?? ""} required/><Input name="feedback" label="Umpan balik" maxLength={10000} defaultValue={review.attempt.feedback ?? ""}/><Button disabled={grade.isPending || review.attempt.status === "IN_PROGRESS"}>Simpan & publikasikan nilai</Button></form>}</div>;
}
function ExamPlayer({ initial, onExit }: { initial: ExamState; onExit: () => void }) {
 const [attempt, setAttempt] = useState(initial.attempt); const [answers, setAnswers] = useState(initial.attempt.answers); const [index, setIndex] = useState(0); const [status, setStatus] = useState("Tersimpan"); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const [now, setNow] = useState(() => Date.now());
 const revision = useRef(initial.attempt.revision); const latest = useRef(initial.attempt.answers); const queue = useRef<Promise<unknown>>(Promise.resolve()); const saved = useRef(JSON.stringify(initial.attempt.answers)); const live = useRef(true); const conflict = useRef(false); const [hasConflict, setHasConflict] = useState(false); const [clockOffset] = useState(() => Date.parse(initial.server_time) - Date.now()); const submitted = useRef(initial.attempt.status !== "IN_PROGRESS");
 const expirySubmitted = useRef(false);
 const remaining = Math.max(0, Date.parse(initial.ends_at) - (now + clockOffset));
 const persist = useCallback((final = false) => {
  const snapshot = { ...latest.current };
  const next = queue.current.catch(() => undefined).then(async () => {
   if (conflict.current || submitted.current || (!final && !live.current)) return;
   if (live.current) setStatus("Menyimpan…");
   const result = await schoolRpc<{ revision: number; status: string; score: number | null }>("school_exam_save", { attempt_uuid: initial.attempt.id, expected_revision: revision.current, answer_data: snapshot, submit: final });
   revision.current = result.revision; saved.current = JSON.stringify(snapshot); submitted.current = result.status !== "IN_PROGRESS";
   if (live.current) { setAttempt(old => ({ ...old, ...result })); setStatus("Tersimpan"); setError(""); }
  });
  queue.current = next;
  return next.catch(e => { if (e instanceof Error && e.message.includes("Another tab")) { conflict.current = true; if (live.current) setHasConflict(true); } if (live.current) { setStatus("Belum tersimpan"); setError(e instanceof Error ? e.message : "Koneksi terputus. Jawaban tetap di halaman ini; coba simpan lagi."); } throw e; });
 }, [initial.attempt.id]);
 useEffect(() => { live.current = true; const timer = window.setInterval(() => setNow(Date.now()), 1000); const warn = (e: BeforeUnloadEvent) => { if (saved.current !== JSON.stringify(latest.current) && !submitted.current) { e.preventDefault(); } }; window.addEventListener("beforeunload", warn); return () => { live.current = false; window.clearInterval(timer); window.removeEventListener("beforeunload", warn); }; }, []);
 useEffect(() => { latest.current = answers; if (JSON.stringify(answers) === saved.current || submitted.current) return; const timer = window.setTimeout(() => { void persist().catch(() => undefined); }, 800); return () => window.clearTimeout(timer); }, [answers, persist]);
 useEffect(() => { if (remaining === 0 && !submitted.current && !submitting && !expirySubmitted.current) { expirySubmitted.current = true; setSubmitting(true); void persist(true).catch(() => undefined).finally(() => { if (live.current) setSubmitting(false); }); } }, [remaining, submitting, persist]);
 if (attempt.status !== "IN_PROGRESS") return <section className="school-exam-complete"><ShieldCheck size={48}/><h1>Jawaban sudah dikumpulkan</h1><p>{initial.title}</p><strong>{attempt.score == null ? "Menunggu tinjauan guru" : `${attempt.score}/100`}</strong>{attempt.feedback && <p>{attempt.feedback}</p>}<Button onClick={onExit}>Kembali ke ruang ujian</Button></section>;
 const question = initial.questions[index];
 return <section className="school-exam-player"><header><div><p className="ose-eyebrow">O-EXAM</p><h1>{initial.title}</h1></div><div className="school-exam-timer"><Clock size={18}/>{String(Math.floor(remaining / 60000)).padStart(2, "0")}:{String(Math.floor(remaining / 1000) % 60).padStart(2, "0")}</div></header><div className="school-exam-body"><aside><h2>Nomor soal</h2><div className="school-question-numbers">{initial.questions.map((q, i) => <button key={q.id} aria-current={i === index ? "step" : undefined} data-answered={!!answers[q.id]} onClick={() => setIndex(i)}>{i + 1}</button>)}</div><p>{Object.values(answers).filter(Boolean).length} / {initial.questions.length} terjawab</p><small><Save size={14}/>{status}</small><Button variant="ghost" disabled={submitting} onClick={() => void persist().catch(() => undefined)}>Simpan sekarang</Button></aside><article>{error && <div className="school-error" role="alert">{error}{hasConflict && <Button onClick={onExit}>Muat ulang dari server</Button>}</div>}{question && <><p className="ose-eyebrow">Soal {index + 1} dari {initial.questions.length}</p><h2>{question.content.prompt}</h2><QuestionDiagram diagram={question.content.diagram}/>{question.content.question_type === "MULTIPLE_CHOICE" ? <fieldset className="school-answer-list"><legend className="sr-only">Jawaban</legend>{question.content.options.map((option, i) => <label key={option} data-selected={answers[question.id] === option}><input type="radio" name={question.id} checked={answers[question.id] === option} disabled={submitting || remaining === 0} onChange={() => { const next = { ...latest.current, [question.id]: option }; latest.current = next; setAnswers(next); }}/><span>{String.fromCharCode(65 + i)}</span>{option}</label>)}</fieldset> : <textarea aria-label="Jawaban esai" rows={12} maxLength={10000} value={answers[question.id] ?? ""} disabled={submitting || remaining === 0} onChange={e => { const next = { ...latest.current, [question.id]: e.target.value }; latest.current = next; setAnswers(next); }}/>}<div className="school-section-title"><Button variant="ghost" disabled={!index} onClick={() => setIndex(i => i - 1)}>← Sebelumnya</Button>{index < initial.questions.length - 1 ? <Button onClick={() => setIndex(i => i + 1)}>Selanjutnya →</Button> : <Button disabled={submitting || hasConflict} onClick={() => { if (confirm("Kumpulkan jawaban? Setelah dikumpulkan, jawaban tidak dapat diubah.")) { setSubmitting(true); void persist(true).catch(() => undefined).finally(() => { if (live.current) setSubmitting(false); }); } }}><Send size={16}/>{submitting ? "Mengumpulkan…" : "Kumpulkan jawaban"}</Button>}</div></>}</article></div></section>;
}
