"use client";
import { type ReactNode, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { schoolRpc,useSchoolContext } from "../../lib/school";
import { usePermissionStore } from "../../stores/permission-store";
import { useTranslations } from "../i18n/i18n-provider";
import { Button,Select } from "../ui";
import { Qualifications } from "../part8/qualifications";
import { Download } from "lucide-react";
import { primaryRole } from "../../lib/modules";
export function FamilyRoute({kind,children}:{kind:"academic"|"learning"|"exams";children:ReactNode}){
 const role=usePermissionStore(s=>primaryRole(s.context));
 return (kind==="academic"&&role==="STUDENT")||(["learning","exams"].includes(kind)&&role==="PARENT")?<FamilyWorkspace kind={kind}/>:children;
}
type Report={school:string;student:{id:string;name:string;number:string};rows:{id:string;title:string;course?:string;classroom?:string;academic_year?:string;semester?:string;subject?:string;programmes?:{name:string;version:string}[];due_at?:string;starts_at?:string;ends_at?:string;submitted_at?:string;score?:number|null;max_score?:number;feedback?:string;status?:string;result_status?:string}[]};
export function FamilyWorkspace({kind}:{kind:"academic"|"learning"|"exams"}){
 const {locale,t}=useTranslations();const id=locale==="id-ID";const school=useSchoolContext();const userId=usePermissionStore(s=>s.context?.userId);const [selected,setSelected]=useState("");const student=school.data?.children.find(c=>c.id===selected)??school.data?.children[0];const [page,setPage]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const q=useQuery({queryKey:["family-report",userId,kind,student?.id,page],enabled:!!student,queryFn:()=>schoolRpc<Report>("school_family_report",{kind,student:student!.id,page_offset:page*100})});
 const dt=(v?:string)=>v?new Date(v).toLocaleString(locale,{dateStyle:"medium",timeStyle:"short"}):"—";
 async function pdf(){setBusy(true);setError("");try{const rows:Report["rows"]=[];for(let offset=0;offset<=100000;offset+=100){const r=await schoolRpc<Report>("school_family_report",{kind,student:student!.id,page_offset:offset});rows.push(...r.rows);if(r.rows.length<100)break;}const {reportPdf,downloadPdf}=await import("../../lib/school-pdf");downloadPdf(await reportPdf(id?"Laporan pembelajaran":"Learning report",`${q.data!.school} | ${student!.name}`,[(id?"Diterbitkan: ":"Generated: ")+new Date().toLocaleString(locale)],rows.map(r=>[r.title,r.course??"",r.status??"",dt(r.due_at),`${r.score??"—"} / ${r.max_score??"—"}`,r.feedback??""])),"osekola-learning-report.pdf");}catch(e){setError(e instanceof Error?e.message:t("loadError"));}finally{setBusy(false);}}
 return <section className="school-workspace"><div className="school-toolbar"><Select aria-label={id?"Pilih anak":"Choose child"} value={student?.id??""} onChange={e=>{setSelected(e.target.value);setPage(0);}}><option value="">{id?"Pilih siswa":"Choose student"}</option>{school.data?.children.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select>{kind==="learning"&&<Button disabled={!q.data||busy} onClick={()=>void pdf()}><Download size={16}/>{busy?"…":"Download PDF"}</Button>}</div>{!student&&!school.isPending&&<p className="school-empty">{id?"Akun siswa belum terhubung. Hubungi staf sekolah untuk menghubungkan data anak.":"No student is linked yet. Contact school staff to link your child."}</p>}{(q.isError||error)&&<p role="alert">{q.error?.message??error}</p>}{q.isFetching&&<p role="status">{t("loading")}</p>}<div className="family-cards">{q.data?.rows.map(r=><article key={r.id} className="glass-panel ose-panel"><p className="ose-eyebrow">{r.course??r.subject}</p><h3>{r.title}</h3>{kind==="academic"?<><p>{r.classroom} · {r.academic_year} · {r.semester}</p>{r.programmes?.map(p=><p key={p.name+p.version}>{p.name} · {p.version}</p>)}</>:<><p>{kind==="learning"?(id?"Tenggat: ":"Due: ")+dt(r.due_at):dt(r.starts_at)+" — "+dt(r.ends_at)}</p><p>{r.status}</p><strong>{id?"Nilai":"Score"}: {r.score??(id?"Belum diterbitkan":"Not published")}{r.score!=null&&kind==="learning"&&` / ${r.max_score??"—"}`}</strong><p>{r.feedback}</p></>}</article>)}</div>{q.data&&!q.data.rows.length&&<p className="school-empty">{id?"Belum ada data yang diterbitkan untuk siswa ini.":"No published records for this student yet."}</p>}<div className="school-pagination"><Button variant="ghost" disabled={!page||q.isFetching} onClick={()=>setPage(p=>p-1)}>←</Button><span>{id?"Halaman":"Page"} {page+1}</span><Button variant="ghost" disabled={!q.data||q.data.rows.length<100||q.isFetching} onClick={()=>setPage(p=>p+1)}>→</Button></div>{student&&<Qualifications studentId={student.id}/>}</section>;
}
