"use client";
import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Copy, Search, Users, Wallet, TrendingUp, ArrowUpRight } from "lucide-react";
import { schoolRpc, useCatalog, type SchoolRow } from "../../lib/school";
import { usePermissionStore } from "../../stores/permission-store";
import { Button, Input, Select } from "../ui";
import { useMarketing, usePlans } from "./growth-public";
type Lead = { id: string; partner_id: string | null; school_name: string; contact_name: string; email: string; phone: string; student_count: number; score: number; recommended_plan: string; stage: string; deal_amount: number; notes: string | null; created_at: string };
type Partner = { id: string; user_id: string; name: string; referral_code: string; is_active: boolean };
type Commission = { id: string; partner_id: string; lead_id: string; amount: number; status: string; reference: string | null };
type Growth = { owner: boolean; partner: Partner | null; partners: Partner[]; leads: Lead[]; commissions: Commission[] };
const stages = ["NEW", "CONTACTED", "DEMO", "PROPOSAL", "WON", "LOST"];
const currency = (n: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(n);
export function GrowthWorkspace() {
 const userId = usePermissionStore(s => s.context?.userId); const qc = useQueryClient();
 const q = useQuery({ queryKey: ["growth", userId], enabled: !!userId, queryFn: () => schoolRpc<Growth>("school_growth_context") });
 const [tab, setTab] = useState("pipeline"); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<Lead>(); const [copyMessage, setCopyMessage] = useState("");
 const save = useMutation({ mutationFn: (args: { kind: string; payload: Record<string, unknown>; record_id?: string }) => schoolRpc("school_growth_save", args), onSuccess: async () => { await Promise.all([qc.invalidateQueries({ queryKey: ["growth"] }), qc.invalidateQueries({ queryKey: ["public-plans"] }), qc.invalidateQueries({ queryKey: ["public-marketing"] })]); setSelected(undefined); } });
 async function copyRef(code: string) { try { await navigator.clipboard.writeText(`${window.location.origin}/assessment?ref=${encodeURIComponent(code)}`); setCopyMessage("Tautan rujukan disalin."); } catch { setCopyMessage(`${window.location.origin}/assessment?ref=${encodeURIComponent(code)}`); } }
 if (q.isLoading) return <p role="status">Memuat ruang partner…</p>;
 if (q.isError) return <div className="school-empty" role="alert"><h2>Akses partner</h2><p>{q.error.message}</p><Button onClick={() => void q.refetch()}>Coba lagi</Button></div>;
 const data = q.data; if (!data) return null;
 const leads = data.leads.filter(l => `${l.school_name} ${l.contact_name} ${l.email}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="school-growth"><div className="school-section-title"><div><p className="ose-eyebrow">GROWTH & PARTNERSHIPS</p><h1>{data.owner ? "Business workspace" : `Halo, ${data.partner?.name}`}</h1><p>Hubungan yang terjaga. Peluang yang bergerak.</p></div>{data.partner && <Button onClick={() => void copyRef(data.partner!.referral_code)}><Copy size={16}/>Tautan rujukan</Button>}</div>{copyMessage && <p role="status" className="ose-link">{copyMessage}</p>}<div className="school-growth-stats">{[[Users, "Prospek", data.leads.length], [TrendingUp, "Deal berhasil", data.leads.filter(l => l.stage === "WON").length], [Wallet, "Fee diterima", currency(data.commissions.filter(c => c.status === "RECEIVED").reduce((n, c) => n + Number(c.amount), 0))], [Wallet, "Fee tertunda", currency(data.commissions.filter(c => c.status === "PENDING").reduce((n, c) => n + Number(c.amount), 0))]].map(([Icon, label, value]) => { const Symbol = Icon as typeof Users; return <article key={String(label)}><Symbol size={20}/><small>{String(label)}</small><strong>{value as React.ReactNode}</strong></article>; })}</div><nav className="school-tabs" role="tablist" aria-label="Business sections">{["pipeline", "commissions", ...(data.owner ? ["partners", "commercial"] : [])].map(t => <button role="tab" key={t} aria-selected={tab === t} onClick={() => { setTab(t); save.reset(); }}>{({ pipeline: "Pipeline", commissions: "Komisi", partners: "Partner", commercial: "Paket & penawaran" })[t]}</button>)}</nav>{save.isError && <p className="school-error" role="alert">{save.error.message}</p>}
 {tab === "pipeline" && <><label className="school-search my-5"><Search size={18}/><input aria-label="Cari prospek" value={search} onChange={e => setSearch(e.target.value)} placeholder="Cari sekolah atau kontak…"/></label><div className="school-pipeline">{stages.map(stage => <section key={stage}><h2>{stage}<span>{leads.filter(l => l.stage === stage).length}</span></h2>{leads.filter(l => l.stage === stage).map(lead => <button className="school-lead-card" key={lead.id} onClick={() => { setSelected(lead); save.reset(); }}><strong>{lead.school_name}</strong><p>{lead.contact_name}</p><small>{lead.student_count} siswa · {lead.score}/100</small><span>{lead.recommended_plan}</span>{Number(lead.deal_amount) > 0 && <b>{currency(Number(lead.deal_amount))}</b>}<ArrowUpRight size={16}/></button>)}</section>)}</div>{selected && <form className="school-editor mt-5" key={selected.id} onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); save.mutate({ kind: "lead", record_id: selected.id, payload: { stage: f.get("stage"), deal_amount: Number(f.get("deal_amount")), notes: f.get("notes") } }); }}><div className="school-section-title"><h2>{selected.school_name}</h2><Button type="button" variant="ghost" onClick={() => setSelected(undefined)}>Tutup</Button></div><p>{selected.contact_name} · {selected.email} · {selected.phone}</p><Select name="stage" aria-label="Tahap" defaultValue={selected.stage}>{stages.map(s => <option key={s}>{s}</option>)}</Select><Input name="deal_amount" label="Nilai deal (IDR)" type="number" min={0} defaultValue={selected.deal_amount}/><Input name="notes" label="Catatan tindak lanjut" defaultValue={selected.notes ?? ""} maxLength={5000}/><Button type="submit" disabled={save.isPending}>Simpan tindak lanjut</Button></form>}</>}
 {tab === "commissions" && <div className="school-workspace"><p className="text-sm text-muted mb-5">Catatan fee berikut digunakan untuk rekonsiliasi. Pembayaran dilakukan melalui proses keuangan yang disepakati.</p>{data.commissions.map(c => <article key={c.id} className="school-record"><div className="school-record-main"><strong>{data.leads.find(l => l.id === c.lead_id)?.school_name ?? "Deal"}</strong><p>{currency(Number(c.amount))} · {c.status}</p><small>{c.reference}</small></div>{data.owner && c.status === "PENDING" && <Button variant="ghost" disabled={save.isPending} onClick={() => { const reference = window.prompt("Referensi bukti pembayaran yang telah diterima:"); if (reference?.trim()) save.mutate({ kind: "commission", record_id: c.id, payload: { ...c, status: "RECEIVED", reference: reference.trim() } }); }}>Catat diterima</Button>}</article>)}{!data.commissions.length && <p>Belum ada catatan komisi.</p>}{data.owner && <form className="school-editor mt-5" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const lead = data.leads.find(l => l.id === f.get("lead_id")); if (lead?.partner_id) save.mutate({ kind: "commission", payload: { lead_id: lead.id, partner_id: lead.partner_id, amount: Number(f.get("amount")), status: "PENDING", reference: f.get("reference") } }); }}><h2>Catat fee untuk deal berhasil</h2><Select name="lead_id" aria-label="Deal" required><option value="">Pilih deal partner</option>{data.leads.filter(l => l.stage === "WON" && l.partner_id).map(l => <option key={l.id} value={l.id}>{l.school_name}</option>)}</Select><Input name="amount" label="Fee (IDR)" type="number" min={0} required/><Input name="reference" label="Referensi kesepakatan" required maxLength={200}/><Button disabled={save.isPending}>Simpan catatan fee</Button></form>}</div>}
 {tab === "partners" && data.owner && <div className="school-workspace">{data.partners.map(p => <article key={p.id} className="school-record"><div className="school-record-main"><strong>{p.name}</strong><small>{p.referral_code} · {p.is_active ? "Aktif" : "Nonaktif"}</small></div><Button variant="ghost" onClick={() => void copyRef(p.referral_code)}><Copy size={16}/></Button><Button variant="ghost" disabled={save.isPending} onClick={() => save.mutate({ kind: "partner", record_id: p.id, payload: { is_active: !p.is_active } })}>{p.is_active ? "Nonaktifkan" : "Aktifkan"}</Button></article>)}<PartnerForm pending={save.isPending} onSave={payload => save.mutate({ kind: "partner", payload })}/></div>}
 {tab === "commercial" && data.owner && <CommercialSettings pending={save.isPending} onSave={(kind, payload) => save.mutate({ kind, payload })}/>}
 </section>;
}
function PartnerForm({ pending, onSave }: { pending: boolean; onSave: (p: Record<string, unknown>) => void }) { const users = useCatalog("users"); return <form className="school-editor mt-5" onSubmit={e => { e.preventDefault(); onSave(Object.fromEntries(new FormData(e.currentTarget))); }}><h2>Tambahkan partner</h2><Select name="user_id" aria-label="Akun partner" required><option value="">Pilih akun aktif</option>{users.data?.map((u: SchoolRow) => <option key={u.id} value={u.id}>{String(u.name)}</option>)}</Select><Input name="name" label="Nama partner" required maxLength={200}/><Input name="referral_code" label="Kode rujukan" pattern="[a-zA-Z0-9-]{4,40}" required/><Button disabled={pending}>Simpan partner</Button></form>; }
function CommercialSettings({ pending, onSave }: { pending: boolean; onSave: (kind: string, p: Record<string, unknown>) => void }) { const plans = usePlans(); const config = useMarketing(); function submit(e: FormEvent<HTMLFormElement>, code: string) { e.preventDefault(); const f = new FormData(e.currentTarget); onSave("plan", { code, price_monthly: Number(f.get("price_monthly")), features: String(f.get("features")).split("\n").map(s => s.trim()).filter(Boolean), offer_note: f.get("offer_note") }); } return <div className="school-workspace"><div className="school-pricing-grid">{plans.data?.map(p => <form className="school-editor" key={`${p.code}-${p.price_monthly}`} onSubmit={e => submit(e, p.code)}><h2>{p.name}</h2><Input label="IDR / siswa / bulan (ditagih tahunan)" name="price_monthly" type="number" min={0} defaultValue={p.price_monthly} required/><label className="school-field">Fitur (satu per baris)<textarea name="features" rows={5} defaultValue={p.features.join("\n")} required/></label><Input label="Catatan penawaran" name="offer_note" defaultValue={p.offer_note}/><Button disabled={pending}>Simpan paket</Button></form>)}</div>{config.data && <form className="school-editor mt-5" onSubmit={e => { e.preventDefault(); onSave("marketing", Object.fromEntries(new FormData(e.currentTarget))); }}><h2>Kontak & kemitraan</h2><Input label="Google Form minat sekolah" name="form_url" type="url" defaultValue={config.data.form_url ?? ""} placeholder="https://forms.gle/…"/><Input label="Nomor WhatsApp (angka internasional)" name="whatsapp" pattern="[0-9]{8,16}" required defaultValue={config.data.whatsapp}/><label className="school-field">Penawaran partner<textarea name="partner_copy" rows={4} defaultValue={config.data.partner_copy} required/></label><Button disabled={pending}>Simpan penawaran</Button></form>}</div>; }
