"use client";
import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Plus, RefreshCw, Sparkles } from "lucide-react";
import { schoolRpc, useCatalog, useSchoolContext } from "../../lib/school";
import { questionSchema, validateQuestion, type QuestionContent } from "../../lib/question-schema";
import { Button, Input, Select } from "../ui";
import { QuestionDiagram } from "./question-diagram";
type SetRow = { id: string; title: string; course_id: string; lesson_id: string | null; grade_level: number };
type Question = QuestionContent & { id: string; set_id: string; source: string; review_status: string };
type Bank = { sets: SetRow[]; items: Question[] };
export function QuestionWorkspace() {
 const school = useSchoolContext(); const courses = useCatalog("courses"); const lessons = useCatalog("lessons"); const assignments = useCatalog("assignments"); const qc = useQueryClient();
 const [exporting, setExporting] = useState(false);
 const [selected, setSelected] = useState(""); const [course, setCourse] = useState(""); const [form, setForm] = useState<"set" | "item" | "ai" | null>(null); const [editing, setEditing] = useState<Question>(); const [replace, setReplace] = useState<Question>(); const [error, setError] = useState("");
 const q = useQuery({ queryKey: ["question-bank", school.data?.tenant.id, selected], enabled: !!school.data?.educator, queryFn: () => schoolRpc<Bank>("school_question_bank", { set_uuid: selected || null }) });
 const save = useMutation({ mutationFn: (args: { kind: string; payload: Record<string, unknown>; record_id?: string }) => schoolRpc<{ id: string }>("school_question_save", args), onSuccess: async (data, args) => { if (args.kind === "set") setSelected(data.id); await qc.invalidateQueries({ queryKey: ["question-bank"] }); setForm(null); setEditing(undefined); } });
 const generate = useMutation({ mutationFn: async (body: Record<string, unknown>) => { const response = await fetch("/api/school/questions/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "AI belum tersedia"); return data; }, onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["question-bank"] }); setForm(null); setReplace(undefined); } });
 if (!school.data?.educator) return null;
 const set = q.data?.sets.find(s => s.id === selected);
 function submitSet(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); save.mutate({ kind: "set", payload: { title: f.get("title"), grade_level: Number(f.get("grade_level")), course_id: course, lesson_id: f.get("lesson_id") || null, assignment_id: f.get("assignment_id") || null } }); }
 function submitAI(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); generate.mutate({ request_id: crypto.randomUUID(), set_id: selected, count: replace ? 1 : Number(f.get("count")), question_type: f.get("question_type"), difficulty: f.get("difficulty"), include_image: f.get("include_image") === "on", instructions: String(f.get("instructions") ?? ""), ...(replace ? { replace_id: replace.id } : {}) }); }
 return <section className="school-workspace school-question-workspace"><div className="school-section-title"><div><p className="ose-eyebrow">TEACHER STUDIO</p><h2>Bank soal & asisten guru</h2><p>Susun soal sesuai course dan lesson, tinjau kualitasnya, lalu gunakan dalam penilaian.</p></div><Button onClick={() => { setForm("set"); save.reset(); }}><Plus size={16}/>Bank baru</Button></div><div className="school-toolbar"><Select aria-label="Bank soal" value={selected} onChange={e => { setSelected(e.target.value); setForm(null); setError(""); }}><option value="">Pilih bank soal</option>{q.data?.sets.map(s => <option key={s.id} value={s.id}>{s.title} · kelas {s.grade_level}</option>)}</Select>{set && <><Button variant="ghost" onClick={() => { setEditing(undefined); setForm("item"); save.reset(); }}><Plus size={16}/>Soal manual</Button><Button onClick={() => { setReplace(undefined); setForm("ai"); generate.reset(); }}><Sparkles size={16}/>Buat dengan AI</Button><Button variant="ghost" disabled={exporting || !q.data?.items.length} onClick={async () => { setExporting(true); try { const { questionPdf, downloadPdf } = await import("../../lib/school-pdf"); downloadPdf(await questionPdf(set.title, school.data?.tenant.name ?? "OSEKOLA", q.data?.items ?? []), "osekola-questions.pdf"); } catch { setError("PDF belum dapat dibuat. Silakan coba lagi."); } finally { setExporting(false); } }}><Download size={16}/>PDF</Button></>}</div>{q.isError && <p role="alert" className="school-error">{q.error.message}</p>}{(save.isError || generate.isError || error) && <p role="alert" className="school-error">{save.error?.message ?? generate.error?.message ?? error}</p>}
 {form === "set" && <form className="school-editor" onSubmit={submitSet}><h3>Bank soal baru</h3><Input name="title" label="Nama bank soal" minLength={2} maxLength={200} required/><Select aria-label="Course" value={course} onChange={e => setCourse(e.target.value)} required><option value="">Pilih course</option>{courses.data?.map(c => <option key={c.id} value={c.id}>{String(c.name)}</option>)}</Select><Select name="lesson_id" aria-label="Lesson"><option value="">Semua lesson dalam course</option>{lessons.data?.filter(l => l.course_id === course).map(l => <option key={l.id} value={l.id}>{String(l.title)}</option>)}</Select><Select name="assignment_id" aria-label="Assignment"><option value="">Tanpa assignment khusus</option>{assignments.data?.filter(a => a.course_id === course).map(a => <option key={a.id} value={a.id}>{String(a.title)}</option>)}</Select><Input name="grade_level" label="Tingkat kelas" type="number" min={1} max={12} required/><div className="flex gap-2"><Button disabled={save.isPending}>Simpan bank</Button><Button type="button" variant="ghost" onClick={() => setForm(null)}>Batal</Button></div></form>}
 {form === "ai" && set && <form className="school-editor" onSubmit={submitAI}><h3><Sparkles size={18}/> {replace ? "Buat ulang soal terpilih" : "Generator soal"}</h3><p>{set.title} · Kelas {set.grade_level}</p>{replace && <blockquote>{replace.prompt}</blockquote>}<Select name="question_type" label="Jenis soal" defaultValue={replace?.question_type ?? "MULTIPLE_CHOICE"}><option value="MULTIPLE_CHOICE">Pilihan ganda</option><option value="ESSAY">Esai</option></Select><Select name="difficulty" label="Kesulitan" defaultValue={replace?.difficulty ?? "MEDIUM"}>{["EASY", "MEDIUM", "HARD"].map(d => <option key={d}>{d}</option>)}</Select>{!replace && <Input name="count" label="Jumlah soal" type="number" min={1} max={20} defaultValue={5} required/>}<label className="school-consent"><input type="checkbox" name="include_image" defaultChecked={!!replace?.diagram}/>Sertakan gambar diagram data</label><label className="school-field">Instruksi tambahan untuk guru<textarea name="instructions" maxLength={2000} rows={3}/></label><p className="text-sm text-muted">Hasil disimpan sebagai draf. Periksa fakta, diagram, pilihan, dan kunci jawaban sebelum menyetujui. Maksimal 10 proses per guru/hari.</p><div className="flex gap-2"><Button disabled={generate.isPending}>{generate.isPending ? "Menyusun draf…" : "Generate"}</Button><Button type="button" variant="ghost" disabled={generate.isPending} onClick={() => setForm(null)}>Batal</Button></div></form>}
 {form === "item" && <QuestionEditor key={editing?.id ?? "new"} question={editing} pending={save.isPending} onClose={() => setForm(null)} onSave={payload => { try { const content = validateQuestion(questionSchema.parse(payload)); setError(""); save.mutate({ kind: "item", record_id: editing?.id, payload: { ...content, set_id: selected, review_status: payload.review_status } }); } catch (e) { setError(e instanceof Error ? e.message : "Periksa soal"); } }}/>}<div className="school-question-list"><h2 className="school-print-title">{set?.title}</h2>{q.data?.items.map((question, i) => <article className="school-question-card" key={question.id}><div className="school-section-title"><span className="ose-eyebrow">{i + 1} · {question.difficulty} · {question.review_status}</span><span className="text-xs text-muted">{question.source}</span></div><h3>{question.prompt}</h3><QuestionDiagram diagram={question.diagram}/>{question.question_type === "MULTIPLE_CHOICE" && <ol type="A">{question.options.map(option => <li key={option}>{option}</li>)}</ol>}<details className="school-answer-key"><summary>Kunci & pembahasan</summary><p>{question.answer}</p><p>{question.explanation}</p></details><div className="school-question-actions"><Button variant="ghost" onClick={() => { setEditing(question); setForm("item"); save.reset(); }}>Tinjau / edit</Button><Button variant="ghost" onClick={() => { setReplace(question); setForm("ai"); generate.reset(); }}><RefreshCw size={14}/>Buat ulang</Button><Button variant="ghost" disabled={save.isPending} onClick={() => { if (confirm("Hapus soal ini dari bank? Soal yang sudah digunakan ujian tetap dilindungi.")) save.mutate({ kind: "delete", record_id: question.id, payload: {} }); }}>Hapus</Button></div></article>)}</div>{selected && !q.isLoading && !q.data?.items.length && <div className="school-empty">Tambahkan soal manual atau buat draf dengan AI.</div>}</section>;
}
function QuestionEditor({ question, pending, onSave, onClose }: { question?: Question; pending: boolean; onSave: (p: Record<string, unknown>) => void; onClose: () => void }) {
 const [kind, setKind] = useState(question?.question_type ?? "MULTIPLE_CHOICE");
 return <form className="school-editor" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); onSave({ question_type: kind, prompt: f.get("prompt"), options: kind === "MULTIPLE_CHOICE" ? String(f.get("options")).split("\n").map(v => v.trim()).filter(Boolean) : [], answer: f.get("answer"), explanation: f.get("explanation"), difficulty: f.get("difficulty"), diagram: question?.diagram ?? null, review_status: f.get("review_status") }); }}><h3>Tinjau soal</h3><Select name="question_type" aria-label="Jenis soal" value={kind} onChange={e => setKind(e.target.value as typeof kind)}><option value="MULTIPLE_CHOICE">Pilihan ganda</option><option value="ESSAY">Esai</option></Select><label className="school-field">Pertanyaan<textarea name="prompt" minLength={5} maxLength={10000} rows={4} defaultValue={question?.prompt} required/></label>{kind === "MULTIPLE_CHOICE" && <label className="school-field">Pilihan (satu per baris, tanpa awalan A/B)<textarea name="options" rows={4} defaultValue={question?.options.join("\n")} required/></label>}<label className="school-field">{kind === "ESSAY" ? "Rubrik penilaian" : "Kunci (salin teks pilihan yang benar)"}<textarea name="answer" defaultValue={question?.answer} rows={2} required/></label><label className="school-field">Pembahasan<textarea name="explanation" defaultValue={question?.explanation} rows={3}/></label><Select name="difficulty" label="Kesulitan" defaultValue={question?.difficulty ?? "MEDIUM"}>{["EASY", "MEDIUM", "HARD"].map(d => <option key={d}>{d}</option>)}</Select><Select name="review_status" label="Hasil tinjauan" defaultValue={question?.review_status ?? "DRAFT"}><option value="DRAFT">Draf — belum digunakan</option><option value="APPROVED">Disetujui guru</option><option value="REJECTED">Ditolak</option></Select><div className="flex gap-2"><Button disabled={pending}>Simpan soal</Button><Button type="button" variant="ghost" onClick={onClose}>Batal</Button></div></form>;
}
