"use client";
import { Pagination } from "../ui/pagination";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { type FormEvent, useState } from "react";
import { createClient } from "../../lib/supabase/client";
import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import { Card } from "../ui/card";
import { EmptyState } from "../ui/empty-state";
import { Input } from "../ui/input";
import { Select } from "../ui/select";
import { useToast } from "../ui/toast";

type Status = "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED";
type View = "board" | "rooms" | "new";
type Room = { id:string; code:string; name:string; location?:string; capacity:number; is_active:boolean };
type User = { id:string; full_name?:string; email?:string };
type RequestItem = { id:string; title?:string; leave_type?:string; reason?:string; purpose?:string; starts_at?:string; starts_on?:string; proposed_starts_at?:string; status:Status; requester_user_id:string; kind:string };
type Approval = { id:string; title:string; resource_type:string; status:Status; current_step:number; approval_steps:{ approver_user_id:string; sequence:number; status:Status }[] };

async function api<T>(path:string,init?:RequestInit){const {data}=await createClient().auth.getSession();if(!data.session)throw new Error("Authenticated session is unavailable");const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/,"")}${path}`,{...init,headers:{Authorization:`Bearer ${data.session.access_token}`,"Content-Type":"application/json",...init?.headers}});const payload=await response.json();if(!response.ok||payload.data===undefined)throw new Error(payload.error?.message??"Request failed");return payload.data as T;}
const label=(user?:User)=>user?.full_name||user?.email||"Unknown user";
const statusTone=(status:Status):"neutral"|"info"|"warning"|"success"|"danger"=>status==="APPROVED"?"success":status==="REJECTED"?"danger":status==="PENDING"?"warning":"neutral";

export function OperationsManager(){
  const [approverPage,setApproverPage]=useState(1);const [page,setPage]=useState(1);const [view,setView]=useState<View>("board"); const [kind,setKind]=useState("booking"); const [error,setError]=useState<string>();
  const qc=useQueryClient(); const {toast}=useToast();
  const rooms=useQuery({queryKey:["operations","rooms"],queryFn:()=>api<Room[]>("/operations/rooms")});
  const users=useQuery({queryKey:["operations","approvers",approverPage],queryFn:()=>api<User[]>(`/operations/approvers?page=${approverPage}&page_size=50`),retry:false});
  const me=useQuery({queryKey:["users","me"],queryFn:()=>api<User>("/users/me")});
  const bookings=useQuery({queryKey:["operations","bookings",page],queryFn:()=>api<Omit<RequestItem,"kind">[]>(`/operations/room-bookings?page=${page}&page_size=50`)});
  const leaves=useQuery({queryKey:["operations","leaves",page],queryFn:()=>api<Omit<RequestItem,"kind">[]>(`/operations/leave-requests?page=${page}&page_size=50`)});
  const schedules=useQuery({queryKey:["operations","schedules",page],queryFn:()=>api<Omit<RequestItem,"kind">[]>(`/operations/schedule-changes?page=${page}&page_size=50`)});
  const approvals=useQuery({queryKey:["operations","approvals",page],queryFn:()=>api<Approval[]>(`/operations/approvals?page=${page}&page_size=50`)});
  const refresh=()=>qc.invalidateQueries({queryKey:["operations"]});
  const mutate=useMutation({mutationFn:({path,body}:{path:string;body:object})=>api(path,{method:"POST",body:JSON.stringify(body)}),onSuccess:async()=>{await refresh();setView("board");toast({title:"Operational request submitted",tone:"success"});},onError:reason=>setError(reason instanceof Error?reason.message:"Request failed")});
  const roomMutation=useMutation({mutationFn:(body:object)=>api<Room>("/operations/rooms",{method:"POST",body:JSON.stringify(body)}),onSuccess:async()=>{await refresh();toast({title:"Room created",tone:"success"});},onError:reason=>setError(reason instanceof Error?reason.message:"Unable to create room")});
  const decision=useMutation({mutationFn:({id,value}:{id:string;value:"APPROVED"|"REJECTED"})=>api(`/operations/approvals/${id}/decision`,{method:"POST",body:JSON.stringify({decision:value})}),onSuccess:async()=>{await refresh();toast({title:"Approval updated",tone:"success"});},onError:reason=>setError(reason instanceof Error?reason.message:"Unable to decide approval")});
  const people=users.data??[]; const approver=people.find(user=>user.id!==me.data?.id)?.id??people[0]?.id??"";
  const all:RequestItem[]=[...(bookings.data??[]).map(item=>({...item,kind:"Room booking"})),...(leaves.data??[]).map(item=>({...item,kind:"Leave"})),...(schedules.data??[]).map(item=>({...item,kind:"Schedule change"}))];
  const assigned=new Set((approvals.data??[]).filter(a=>a.status==="PENDING"&&a.approval_steps.find(s=>s.sequence===a.current_step)?.approver_user_id===me.data?.id).map(a=>a.id));

  function submitRoom(event:FormEvent<HTMLFormElement>){event.preventDefault();setError(undefined);const f=new FormData(event.currentTarget);roomMutation.mutate({code:f.get("code"),name:f.get("name"),location:f.get("location")||undefined,capacity:Number(f.get("capacity")),facilities:[]});}
  function submitRequest(event:FormEvent<HTMLFormElement>){event.preventDefault();setError(undefined);const f=new FormData(event.currentTarget);const approver_user_ids=[f.get("approver_user_id")];if(kind==="booking")mutate.mutate({path:"/operations/room-bookings",body:{room_id:f.get("room_id"),title:f.get("title"),purpose:f.get("reason"),starts_at:f.get("starts_at"),ends_at:f.get("ends_at"),approver_user_ids}});else if(kind==="leave")mutate.mutate({path:"/operations/leave-requests",body:{leave_type:f.get("leave_type"),starts_on:f.get("starts_on"),ends_on:f.get("ends_on"),reason:f.get("reason"),approver_user_ids}});else mutate.mutate({path:"/operations/schedule-changes",body:{calendar_event_id:f.get("calendar_event_id"),proposed_starts_at:f.get("starts_at"),proposed_ends_at:f.get("ends_at"),reason:f.get("reason"),approver_user_ids}});}

  return <section className="mt-6">
{[rooms,bookings,leaves,schedules,approvals].some(query=>query.isError)&&<p role="alert" className="mb-4 text-danger">Some operational records could not be loaded. Check permissions or retry.</p>}
    <div className="flex flex-wrap items-end justify-between gap-4"><div><Badge tone="info">Phase 43–46</Badge><h1 className="mt-2 text-3xl font-black">Operations board</h1><p className="mt-1 text-sm text-muted">Rooms, leave, schedule changes, and approvals in one Jira-style flow.</p></div><Button onClick={()=>setView("new")}>Create request</Button></div>
    <nav className="mt-5 flex gap-2">{(["board","rooms","new"] as View[]).map(item=><Button key={item} size="sm" variant={view===item?"secondary":"ghost"} onClick={()=>setView(item)}>{item==="new"?"New request":item[0].toUpperCase()+item.slice(1)}</Button>)}</nav>
    {error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {view==="board"&&<div className="mt-5 overflow-x-auto pb-4"><div className="grid min-w-[1000px] grid-cols-4 gap-3">{(["PENDING","APPROVED","REJECTED","CANCELLED"] as Status[]).map(status=><div key={status} className="min-h-[480px] rounded-2xl border border-border bg-white/35 p-3"><div className="mb-3 flex justify-between"><Badge tone={statusTone(status)}>{status}</Badge><span className="text-xs font-bold text-muted">{all.filter(item=>item.status===status).length}</span></div><div className="space-y-3">{all.filter(item=>item.status===status).map(item=><Card key={`${item.kind}-${item.id}`} className="p-4"><p className="text-xs font-bold uppercase text-secondary">{item.kind}</p><p className="mt-1 font-semibold">{item.title??item.leave_type??item.reason??item.id}</p><p className="mt-2 text-xs text-muted">{item.starts_at??item.starts_on??item.proposed_starts_at??"Awaiting schedule"}</p></Card>)}</div></div>)}</div></div>}
    {view==="rooms"&&<div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><Card><h2 className="text-lg font-bold">Room directory</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{rooms.data?.map(room=><div key={room.id} className="rounded-xl bg-white/60 p-4"><div className="flex justify-between"><p className="font-bold">{room.code} · {room.name}</p><Badge tone={room.is_active?"success":"neutral"}>{room.is_active?"Active":"Inactive"}</Badge></div><p className="mt-2 text-sm text-muted">{room.location||"No location"} · {room.capacity} seats</p></div>)}{!rooms.isLoading&&!rooms.data?.length&&<EmptyState title="No rooms" description="Create the first bookable room."/>}</div></Card><Card><h2 className="font-bold">Add room</h2><form className="mt-4 space-y-3" onSubmit={submitRoom}><Input name="code" label="Room code" placeholder="LAB-01" required/><Input name="name" label="Room name" required/><Input name="location" label="Location"/><Input name="capacity" type="number" min="1" label="Capacity" required/><Button type="submit" disabled={roomMutation.isPending}>Create room</Button></form></Card></div>}
    {view==="new"&&<Card className="mt-5 max-w-2xl p-5"><h2 className="text-lg font-bold">New operational request</h2><div className="mt-4 flex gap-2">{[["booking","Room booking"],["leave","Leave"],["schedule","Schedule change"]].map(([key,name])=><Button key={key} size="sm" variant={kind===key?"secondary":"ghost"} onClick={()=>setKind(key)}>{name}</Button>)}</div><form className="mt-5 space-y-3" onSubmit={submitRequest}>{kind==="booking"&&<><Select name="room_id" label="Room" required><option value="">Select room</option>{rooms.data?.filter(r=>r.is_active).map(r=><option key={r.id} value={r.id}>{r.code} · {r.name}</option>)}</Select><Input name="title" label="Booking title" required/></>}{kind==="leave"&&<><Select name="leave_type" label="Leave type"><option value="ANNUAL">Annual</option><option value="SICK">Sick</option><option value="PERSONAL">Personal</option><option value="OTHER">Other</option></Select><Input name="starts_on" type="date" label="Starts on" required/><Input name="ends_on" type="date" label="Ends on" required/></>}{kind==="schedule"&&<Input name="calendar_event_id" label="Calendar event ID" required/>}{kind!=="leave"&&<><Input name="starts_at" type="datetime-local" label="Proposed start" required/><Input name="ends_at" type="datetime-local" label="Proposed end" required/></>}<Input name="reason" label={kind==="booking"?"Purpose":"Reason"} required/><Select key={approverPage} name="approver_user_id" label="Approver" defaultValue={approver} required><option value="">Select approver</option>{people.map(user=><option key={user.id} value={user.id}>{label(user)}</option>)}</Select><Pagination page={approverPage} count={people.length} pending={users.isFetching} onPage={setApproverPage}/><Button type="submit" disabled={mutate.isPending||!people.length}>Submit for approval</Button></form></Card>}
    {assigned.size>0&&<Card className="mt-5 p-5"><h2 className="text-lg font-bold">My approval queue</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{approvals.data?.filter(a=>assigned.has(a.id)).map(a=><div key={a.id} className="rounded-xl bg-white/60 p-4"><p className="text-xs font-bold text-secondary">{a.resource_type.replaceAll("_"," ")}</p><p className="mt-1 font-semibold">{a.title}</p><div className="mt-4 flex gap-2"><Button size="sm" disabled={decision.isPending} onClick={()=>decision.mutate({id:a.id,value:"APPROVED"})}>Approve</Button><Button size="sm" variant="danger" disabled={decision.isPending} onClick={()=>decision.mutate({id:a.id,value:"REJECTED"})}>Reject</Button></div></div>)}</div></Card>}
    {view==="board"&&<Pagination page={page} count={Math.max(bookings.data?.length??0,leaves.data?.length??0,schedules.data?.length??0,approvals.data?.length??0)} pending={bookings.isFetching||approvals.isFetching} onPage={setPage}/>}
  </section>;
}
