"use client";
import {useState} from "react";
import {useMutation,useQuery} from "@tanstack/react-query";
import {schoolRpc} from "../../lib/school";
import {usePermissionStore} from "../../stores/permission-store";
import {Button} from "../ui";
import {executePeople,useP9,useRefreshP9,type PeopleResult} from "./shared";
import {CredentialNotice} from "./staff-directory";
export type Approval={id:string;title:string;resource_type:string;resource_id:string;status:string;created_at:string;requester_name:string;school:string;can_decide:boolean;details:Record<string,unknown>|null;steps:{sequence:number;status:string;note:string|null;name:string}[]};
const shown=(v:unknown)=>typeof v==='string'||typeof v==='number'?String(v):'—';
export function ApprovalCard({request,compact=false,onIssued}:{request:Approval;compact?:boolean;onIssued?:(r:PeopleResult)=>void}){
 const tr=useP9(),refresh=useRefreshP9(),[note,setNote]=useState(''),[credentials,setCredentials]=useState<PeopleResult|null>(null);const details=request.details??{};const issued=(r:PeopleResult)=>{setCredentials(r);onIssued?.(r);};
 const decision=useMutation({mutationFn:async(value:string)=>{const r=await schoolRpc<{change_id?:string}>('school_approval_decide',{request_id:request.id,decision:value,note});if(value==='APPROVED'&&r.change_id)issued(await executePeople(r.change_id));},onSettled:refresh});
 const retry=useMutation({mutationFn:()=>executePeople(request.resource_id),onSuccess:issued,onSettled:refresh});
 const labels:Record<string,string>={subject_name:tr('Person','Nama'),starts_on:tr('From','Mulai'),ends_on:tr('Until','Sampai'),leave_type:tr('Leave type','Jenis izin'),substitute_name:tr('Substitute','Guru pengganti'),substitute_kind:tr('Duty','Tugas'),reason:tr('Reason','Alasan'),operation:tr('Action','Tindakan'),role:tr('Role','Peran'),starts_at:tr('Start','Mulai'),ends_at:tr('End','Selesai'),purpose:tr('Purpose','Keperluan'),proposed_starts_at:tr('Proposed start','Usulan mulai'),proposed_ends_at:tr('Proposed end','Usulan selesai')};
 const payload=details.payload as Record<string,unknown>|undefined;
 return <article className="p9-request"><CredentialNotice result={credentials}/><small>{request.school} · {request.requester_name}</small><h3>{request.title}</h3><span className="owner-badge" data-status={request.status}>{request.status}</span><dl>{Object.entries(labels).filter(([key])=>details[key]!=null).map(([key,label])=><div key={key} style={{display:'contents'}}><dt>{label}</dt><dd>{shown(details[key])}</dd></div>)}</dl>{payload&&<details open={!compact}><summary>{tr('Proposed account details','Rincian perubahan akun')}</summary>{Object.entries(payload).filter(([k])=>k!=='student_ids').map(([k,v])=><p key={k}>{k.replaceAll('_',' ')}: <strong>{shown(v)}</strong></p>)}</details>}
 {request.steps.some(s=>s.note)&&<details><summary>{tr('Decision history','Riwayat keputusan')}</summary>{request.steps.filter(s=>s.note).map(s=><p key={s.sequence}>{s.name}: {s.note}</p>)}</details>}
 {request.can_decide&&<><textarea aria-label={`${tr('Decision note','Catatan keputusan')}: ${request.title}`} placeholder={tr('Note (required to reject)','Catatan (wajib untuk menolak)')} value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/><div className="owner-actions"><Button size="sm" variant="secondary" disabled={decision.isPending} onClick={()=>decision.mutate('APPROVED')}>{tr('Approve','Setujui')}</Button><Button size="sm" variant="danger" disabled={decision.isPending||note.trim().length<3} onClick={()=>decision.mutate('REJECTED')}>{tr('Reject','Tolak')}</Button></div></>}
 {request.resource_type==='USER_CHANGE'&&request.status==='APPROVED'&&details.execution_status!=='DONE'&&<div><p>{tr('Approved. Apply the account change to complete it.','Disetujui. Terapkan perubahan akun untuk menyelesaikannya.')}</p><Button variant="secondary" disabled={retry.isPending} onClick={()=>retry.mutate()}>{tr('Apply / retry','Terapkan / coba lagi')}</Button></div>}
 {(decision.isError||retry.isError)&&<p role="alert">{decision.error?.message??retry.error?.message}</p>}
 </article>;
}
export function ApprovalBoard(){const tr=useP9(),actor=usePermissionStore(s=>s.context?.userId),[page,setPage]=useState(0),[history,setHistory]=useState(false),[credentials,setCredentials]=useState<PeopleResult|null>(null);const q=useQuery({queryKey:['p9','approvals',actor,page],enabled:!!actor,queryFn:()=>schoolRpc<Approval[]>('school_approval_queue',{page_offset:page*50}),refetchInterval:20000});
 const groups=[['LEAVE_REQUEST',tr('Leave requests','Pengajuan izin')],['USER_CHANGE',tr('User changes','Perubahan pengguna')],['OTHER',tr('School operations','Operasional sekolah')]];
 const rows=(q.data??[]).filter(r=>history||r.status==='PENDING'||(r.status==='APPROVED'&&r.resource_type==='USER_CHANGE'&&r.details?.execution_status!=='DONE'));
 return <section className="school-workspace"><div className="school-section-title"><div><h1>{tr('Approvals','Persetujuan')}</h1><p>{tr('Review the context and decide directly from each request.','Tinjau rincian dan berikan keputusan langsung pada setiap pengajuan.')}</p></div><Button variant="secondary" aria-pressed={history} onClick={()=>setHistory(v=>!v)}>{tr('Include history','Tampilkan riwayat')}</Button></div><CredentialNotice result={credentials}/>{q.isError?<p role="alert">{q.error.message}</p>:q.isPending?<p>{tr('Loading…','Memuat…')}</p>:<div className="p9-approval-board">{groups.map(([key,label])=>{const items=rows.filter(r=>key==='OTHER'?!['LEAVE_REQUEST','USER_CHANGE'].includes(r.resource_type):r.resource_type===key);return <section className="p9-approval-column" key={key}><h2>{label} <span>{items.length}</span></h2>{items.length?items.map(r=><ApprovalCard key={r.id} request={r} onIssued={setCredentials}/>):<p>{tr('No requests on this page.','Tidak ada pengajuan di halaman ini.')}</p>}</section>;})}</div>}<div className="school-pagination"><Button variant="ghost" disabled={!page} onClick={()=>setPage(p=>p-1)}>←</Button><span>{page+1}</span><Button variant="ghost" disabled={(q.data?.length??0)<50} onClick={()=>setPage(p=>p+1)}>→</Button></div></section>;
}
export function LeaveMessage({messageId}:{messageId:string}){const actor=usePermissionStore(s=>s.context?.userId);const q=useQuery({queryKey:['p9','leave-message',actor,messageId],enabled:!!actor,queryFn:()=>schoolRpc<Approval|null>('school_leave_message',{message_id:messageId}),refetchInterval:15000});return q.isError?<p role="alert">{q.error.message}</p>:q.data?<ApprovalCard request={q.data} compact/>:null;}
