"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {useMutation,useQuery} from "@tanstack/react-query";
import {schoolRpc} from "../../lib/school";
import {usePermissionStore} from "../../stores/permission-store";
import {Button,Input,Select} from "../ui";
import {Modal} from "../ui/modal";
import {useP9,useRefreshP9} from "./shared";
type Person={id:string;full_name:string;roles:string[];verified_at:string|null;enrolled_at:string|null;credentials:{id:string;kind:string;mask:string|null}[]};
function QrCard({token,name}:{token:string;name:string}){const canvas=useRef<HTMLCanvasElement>(null),tr=useP9();const[error,setError]=useState('');useEffect(()=>{let active=true;void import('qrcode').then(q=>{if(active&&canvas.current)return q.toCanvas(canvas.current,token,{width:280,margin:3});}).catch(e=>setError(String(e)));return()=>{active=false;};},[token]);return <div className="p9-qr-card"><h3>{name}</h3><canvas ref={canvas} aria-label={tr('Attendance QR code','Kode QR presensi')}/>{error&&<p role="alert">{error}</p>}<Button variant="secondary" onClick={()=>{if(!canvas.current)return;const a=document.createElement('a');a.href=canvas.current.toDataURL('image/png');a.download='osekola-attendance-qr.png';a.click();}}>{tr('Download QR','Unduh QR')}</Button><p>{tr('Save this card before closing. A replacement revokes the previous QR.','Simpan kartu ini sebelum menutup. Penggantian akan mencabut QR sebelumnya.')}</p></div>;}
export function IdentityWorkspace(){const tr=useP9(),context=usePermissionStore(s=>s.context),refresh=useRefreshP9();const allowed=context?.roles.some(r=>r.code==='STAFF');const[search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(0),[person,setPerson]=useState<Person|null>(null),[qr,setQr]=useState<{token:string;name:string}|null>(null),[checkKind,setCheckKind]=useState('RFID'),[checkToken,setCheckToken]=useState(''),[confirm,setConfirm]=useState<{person:Person;kind:string}|null>(null);
 const q=useQuery({queryKey:['p9','identities',context?.userId,query,page],enabled:!!allowed,queryFn:()=>schoolRpc<Person[]>('school_identity_directory',{query,page_offset:page*50})});
 const save=useMutation({mutationFn:({target,kind,token='',remove=false}:{target:Person;kind:string;token?:string;remove?:boolean})=>schoolRpc<{token?:string}>('school_identity_save',{target:target.id,kind,token,remove}).then(r=>({r,target})),onSuccess:async({r,target})=>{setPerson(null);setConfirm(null);if(r.token)setQr({token:r.token,name:target.full_name});await refresh();}});
 const check=useMutation({mutationFn:()=>schoolRpc<{name:string;date:string}>('school_identity_checkin',{kind:checkKind,token:checkToken}),onSuccess:async()=>{setCheckToken('');await refresh();}});
 if(!allowed)return <p>{tr('Staff access required.','Akses khusus staf.')}</p>;
 return <section className="school-workspace"><Link className="ose-link" href="/dashboard">← Dashboard</Link><div className="school-section-title"><div><h1>{tr('Face / QR / RFID','Wajah / QR / RFID')}</h1><p>{tr('School users · supervised registration and attendance','Pengguna sekolah · pendaftaran dan presensi dengan pendampingan')}</p></div><Link className="ose-cta" href="/dashboard/attendance/enrollment">{tr('Enroll / verify faces','Daftar / verifikasi wajah')}</Link><Link className="ose-link" href="/dashboard/attendance/face">{tr('Face check-in →','Presensi wajah →')}</Link></div>
 <form className="school-editor" onSubmit={e=>{e.preventDefault();check.mutate();}}><h2>{tr('Record attendance','Catat presensi')}</h2><Select label={tr('Method','Metode')} value={checkKind} onChange={e=>setCheckKind(e.target.value)}><option>RFID</option><option>QR</option></Select><Input label={tr('Scan using a USB reader, or paste the scanned code','Pindai dengan pembaca USB, atau tempel kode hasil pindai')} value={checkToken} onChange={e=>setCheckToken(e.target.value)} maxLength={128} required autoComplete="off"/><Button type="submit" disabled={check.isPending}>{tr('Check in','Catat hadir')}</Button>{check.isError&&<p role="alert">{check.error.message}</p>}{check.data&&<p role="status">✓ {check.data.name} · {check.data.date}</p>}</form>
 <form className="school-toolbar" onSubmit={e=>{e.preventDefault();setQuery(search);setPage(0);}}><Input aria-label={tr('Search users','Cari pengguna')} value={search} onChange={e=>setSearch(e.target.value)} maxLength={160}/><Button type="submit" variant="ghost">{tr('Search','Cari')}</Button></form>{(q.isError||save.isError)&&<p role="alert">{q.error?.message??save.error?.message}</p>}
 <div className="school-record-list">{q.data?.map(p=><article className="school-record" key={p.id}><div className="school-record-main"><strong>{p.full_name}</strong><p>{p.roles.join(' · ')}</p><small>{tr('Face','Wajah')}: {p.verified_at?tr('Verified','Terverifikasi'):p.enrolled_at?tr('Verify again','Pindai ulang'):tr('Not enrolled','Belum terdaftar')}</small><div>{p.credentials.map(c=><span className="owner-badge" key={c.id}>{c.kind}{c.mask?' · ••••'+c.mask:''} <button type="button" aria-label={`${tr('Revoke','Cabut')} ${c.kind} ${p.full_name}`} onClick={()=>setConfirm({person:p,kind:c.kind})}>×</button></span>)}</div></div><Button variant="ghost" disabled={save.isPending} onClick={()=>save.mutate({target:p,kind:'QR'})}>{p.credentials.some(c=>c.kind==='QR')?tr('Replace QR','Ganti QR'):'+ QR'}</Button><Button variant="ghost" onClick={()=>{save.reset();setPerson(p);}}>+ RFID</Button></article>)}</div><div className="school-pagination"><Button variant="ghost" disabled={!page} onClick={()=>setPage(p=>p-1)}>←</Button><span>{page+1}</span><Button variant="ghost" disabled={(q.data?.length??0)<50} onClick={()=>setPage(p=>p+1)}>→</Button></div>
 <Modal isOpen={!!person} onClose={()=>setPerson(null)} title={`${tr('Register RFID','Daftar RFID')} · ${person?.full_name??''}`}><form className="p9-leave-form" onSubmit={e=>{e.preventDefault();if(person)save.mutate({target:person,kind:'RFID',token:String(new FormData(e.currentTarget).get('token'))});}}><Input className="p9-full" name="token" label={tr('Card identifier','Nomor kartu')} minLength={6} maxLength={128} required autoComplete="off"/><Button className="p9-full" type="submit" disabled={save.isPending}>{tr('Save','Simpan')}</Button>{save.isError&&<p role="alert">{save.error.message}</p>}</form></Modal>
 <Modal isOpen={!!qr} onClose={()=>setQr(null)} title={tr('Attendance card','Kartu presensi')}>{qr&&<QrCard {...qr}/>}</Modal><Modal isOpen={!!confirm} onClose={()=>setConfirm(null)} title={tr('Revoke credential','Cabut identitas presensi')}><p>{confirm?.person.full_name} · {confirm?.kind}</p><Button variant="danger" disabled={save.isPending} onClick={()=>confirm&&save.mutate({target:confirm.person,kind:confirm.kind,remove:true})}>{tr('Revoke','Cabut')}</Button></Modal>
 </section>;
}
