"use client";
import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {schoolRpc} from "../../lib/school";
import {usePermissionStore} from "../../stores/permission-store";
import {useTranslations} from "../i18n/i18n-provider";
import {Modal} from "../ui/modal";
import {Button} from "../ui";
import {statusName,useP9} from "./shared";
type Month={month:string;students:number;employees:number;assets:number;asset_categories:Record<string,number>|null};
type Data={today:string;history:Month[];finance:{income:number;expenses:number;balance:number;receivables:number;previous_income:number;previous_expenses:number;previous_balance:number;previous_receivables:number};students_total:number;students_present:number;employees_total:number;employees_present:number;grades:{day:string;average:number|null}[]};
export function changePercent(current:number,previous:number){return previous===0?null:(current-previous)/Math.abs(previous)*100;}
function MiniChart({values,labels,bars=false,label}:{values:(number|null)[];labels:string[];bars?:boolean;label:string}){
 const max=Math.max(1,...values.filter((v):v is number=>v!==null));
 return <><svg viewBox="0 0 300 110" role="img" aria-label={`${label}: ${values.map((v,i)=>`${labels[i]} ${v??'—'}`).join(', ')}`}><line x1="8" x2="292" y1="95" y2="95" stroke="var(--border)"/>{bars?values.map((v,i)=><rect key={i} x={i*46+16} y={95-(v??0)/max*80} width="24" height={(v??0)/max*80} rx="5" fill="var(--secondary)"><title>{labels[i]}: {v??'—'}</title></rect>):values.map((v,i)=>v===null?null:<g key={i}>{i>0&&values[i-1]!==null&&<line className="p9-line" x1={12+(i-1)*276/(values.length-1)} y1={95-values[i-1]!/max*80} x2={12+i*276/(values.length-1)} y2={95-v/max*80} stroke="var(--secondary)" strokeWidth="3"/>}<circle cx={12+i*276/(values.length-1)} cy={95-v/max*80} r="4" fill="var(--secondary)"><title>{labels[i]}: {v}</title></circle></g>)}</svg><div className="p9-chart-labels">{labels.map((l,i)=><span key={i}>{l}</span>)}</div></>;
}
function AssetChart({history,labels}:{history:Month[];labels:string[]}){const tr=useP9();const categories=[['CLASSROOM',tr('Classrooms','Ruang kelas'),'#4887e8'],['LAB',tr('Labs','Laboratorium'),'#8b67d5'],['FIELD',tr('Fields','Lapangan'),'#2aa48a'],['EQUIPMENT',tr('Equipment','Peralatan'),'#e0a23f'],['OTHER',tr('Other','Lainnya'),'#93a1b5']];const max=Math.max(1,...history.map(m=>m.assets));return <><svg viewBox="0 0 300 110" role="img" aria-label={tr('School assets by category over six months','Aset sekolah per kategori selama enam bulan')}>{history.map((m,i)=>{let base=95;return <g key={m.month}>{categories.map(([key,label,color])=>{const n=m.asset_categories?.[key]??0,h=n/max*80;base-=h;return <rect key={key} x={16+i*46} y={base} height={h} width="24" fill={color}><title>{labels[i]} · {label}: {n}</title></rect>;})}</g>;})}</svg><div className="p9-chart-labels">{labels.map((label,i)=><span key={i}>{label}</span>)}</div><div className="p9-chart-legend">{categories.map(([key,label,color])=><span key={key}><i style={{background:color}}/>{label}</span>)}</div></>;}
function Absences({kind,today,close}:{kind:string;today:string;close:()=>void}){const tr=useP9(),actor=usePermissionStore(s=>s.context?.userId),[page,setPage]=useState(0);const q=useQuery({queryKey:["p9","absences",actor,kind,page],queryFn:()=>schoolRpc<{name:string;classroom?:string;homeroom?:string;status:string;reason:string|null}[]>("school_absence_list",{kind,page_offset:page*100})});return <Modal isOpen onClose={close} title={`${tr("Attendance follow-up","Tindak lanjut presensi")} · ${today}`}><p>{tr("Unrecorded attendance is listed separately from an absence.","Presensi belum tercatat dibedakan dari ketidakhadiran.")}</p>{q.isError?<p role="alert">{q.error.message}</p>:q.isPending?<p>{tr("Loading…","Memuat…")}</p>:<div className="owner-table-scroll"><table className="owner-table"><thead><tr><th>{tr("Name","Nama")}</th>{kind==="STUDENT"&&<><th>{tr("Class","Kelas")}</th><th>{tr("Homeroom teacher","Wali kelas")}</th></>}<th>Status</th><th>{tr("Reason","Alasan")}</th></tr></thead><tbody>{q.data.map((r,i)=><tr key={i}><td>{r.name}</td>{kind==="STUDENT"&&<><td>{r.classroom??'—'}</td><td>{r.homeroom??'—'}</td></>}<td>{statusName(r.status,tr)}</td><td>{r.reason??'—'}</td></tr>)}</tbody></table>{!q.data.length&&<p>{tr("No attendance follow-up on this page.","Tidak ada tindak lanjut presensi di halaman ini.")}</p>}</div>}<div className="owner-actions"><Button variant="ghost" disabled={!page} onClick={()=>setPage(p=>p-1)}>←</Button><span>{page+1}</span><Button variant="ghost" disabled={(q.data?.length??0)<100} onClick={()=>setPage(p=>p+1)}>→</Button></div></Modal>;}
export function PrincipalDashboard(){const tr=useP9(),{locale}=useTranslations(),actor=usePermissionStore(s=>s.context?.userId),[absent,setAbsent]=useState<string>();const q=useQuery({queryKey:["p9","principal",actor],enabled:!!actor,queryFn:()=>schoolRpc<Data>("school_principal_dashboard"),refetchInterval:60000});if(q.isError)return <p role="alert">{q.error.message}</p>;if(!q.data)return <p role="status">{tr("Loading school statistics…","Memuat statistik sekolah…")}</p>;const d=q.data,labels=d.history.map(m=>new Date(m.month+"T12:00:00").toLocaleDateString(locale,{month:"short"}));
 const money=(n:number)=>new Intl.NumberFormat(locale,{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
 const financial=[['income',tr("Income this month","Pemasukan bulan ini")],['expenses',tr("Expenses this month","Pengeluaran bulan ini")],['balance',tr("Recorded cash balance","Saldo kas tercatat")],['receivables',tr("Outstanding receivables","Tagihan / piutang")]] as const;
 return <><div className="p9-grid-three">{[['students',tr("Students · 6 months","Siswa · 6 bulan")],['employees',tr("Staff & teachers · 6 months","Staf & guru · 6 bulan")],['assets',tr("School assets · 6 months","Aset sekolah · 6 bulan")]].map(([key,title])=><article className="p9-stat-card" key={key}><h2>{title}</h2><strong>{d.history.at(-1)?.[key as 'students'|'employees'|'assets']??0}</strong>{key==='assets'?<AssetChart history={d.history} labels={labels}/>:<MiniChart label={title} labels={labels} values={d.history.map(m=>m[key as 'students'|'employees'])}/>}</article>)}</div><p className="owner-help">{tr("History is reconstructed from recorded admission, creation and archive dates. Records removed before this release cannot be reconstructed.","Riwayat dihitung dari tanggal masuk, pembuatan, dan arsip yang tercatat. Data yang telah dihapus sebelum rilis ini tidak dapat direkonstruksi.")}</p>
 <div className="p9-financial">{financial.map(([key,title])=>{const n=d.finance[key],prev=d.finance[`previous_${key}`],pct=changePercent(n,prev),good=key==='receivables'?n<=prev:n>=prev;return <article className="p9-stat-card" key={key}><span className="p9-growth" data-good={good}>{pct===null?(n===0?'0%':tr("New","Baru")):`${pct>0?'+':''}${pct.toFixed(1)}%`}</span><h2>{title}</h2><strong>{money(n)}</strong><small>{tr("Previous month","Bulan lalu")}: {money(prev)}</small></article>;})}</div>
 <div className="p9-grid-three">{(['STUDENT','EMPLOYEE'] as const).map(kind=>{const total=kind==='STUDENT'?d.students_total:d.employees_total,present=kind==='STUDENT'?d.students_present:d.employees_present;return <button className="p9-stat-card" key={kind} onClick={()=>setAbsent(kind)}><h2>{kind==='STUDENT'?tr("Student attendance","Kehadiran siswa"):tr("Staff & teacher attendance","Kehadiran staf & guru")}</h2><strong>{total?`${(present/total*100).toFixed(1)}%`:'—'}</strong><p>{present} / {total}</p><small>{d.today} · {tr("View follow-up","Lihat tindak lanjut")}</small></button>;})}<article className="p9-stat-card"><h2>{tr("Published grades · 7 days","Nilai terpublikasi · 7 hari")}</h2><MiniChart label={tr("Daily average","Rata-rata harian")} labels={d.grades.map(g=>new Date(g.day+'T12:00:00').toLocaleDateString(locale,{weekday:'short'}))} values={d.grades.map(g=>g.average)}/><small>{tr("Days without published grades remain empty.","Hari tanpa nilai terpublikasi tetap kosong.")}</small></article></div>{absent&&<Absences kind={absent} today={d.today} close={()=>setAbsent(undefined)}/>}</>;
}
