"use client";
import { useState, useRef } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Upload } from "lucide-react";
import { schoolRpc } from "../../lib/school";
import { useOwnerSave, value, type OwnerRow } from "../../lib/owner";
import { createClient } from "../../lib/supabase/client";
import { validateMedia } from "../../lib/media";
import { useTranslations } from "../i18n/i18n-provider";
import { Button, Input, Select } from "../ui";
import { Modal } from "../ui/modal";
import { OwnerDialog } from "../owner/owner-ui";

type Reference = { code:string; name:string; postal_code?:string; npsn?:string; id:string; principals?:{id:string;name:string}[]; school?:string };
function useReference(resource:string,parent?:string,query="",enabled=true) {return useQuery({queryKey:["p10-reference",resource,parent,query],enabled,queryFn:()=>schoolRpc<Reference[]>("school_owner_reference",{resource,parent:parent||null,query}),staleTime:60_000});}
const regions=["province_code","city_code","district_code","village_code"];
export function TenantForm({initial,close}:{initial:OwnerRow|null;close:()=>void}) {
 const {locale}=useTranslations(),ind=locale==="id-ID",tr=(en:string,id:string)=>ind?id:en;
 const [form,setForm]=useState<Record<string,string>>(()=>Object.fromEntries(["npsn","name","group_id",...regions,"postal_code","address","website_url","contact_email","contact_phone","timezone","locale","week_starts_on"].map(k=>[k,initial?value(initial,k):({timezone:"Asia/Jakarta",locale:"en-US",week_starts_on:"1"} as Record<string,string>)[k]||""])));
 const [bank,setBank]=useState({bank_name:"",account_name:"",account_number:""});
 const [file,setFile]=useState<File>(),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const savedId=useRef(initial?.id),save=useOwnerSave(),cache=useQueryClient();
 const groups=useReference("groups"),provinces=useReference("regions"),cities=useReference("regions",form.province_code,"",!!form.province_code),districts=useReference("regions",form.city_code,"",!!form.city_code),villages=useReference("regions",form.district_code,"",!!form.district_code),npsn=useReference("npsn",undefined,form.npsn,form.npsn.length>=3);
 const lists=[provinces,cities,districts,villages];
 const change=(key:string,v:string)=>setForm(old=>({...old,[key]:v}));
 async function persist(){setBusy(true);setError("");try{
  const payload=Object.fromEntries(Object.entries(form).map(([k,v])=>[k,k==="week_starts_on"?Number(v):v.trim()||null]));
  const row=await save.mutateAsync({kind:"tenant",id:savedId.current,payload:{...payload,...(!initial&&Object.values(bank).some(Boolean)?{settlement_account:bank}:{})}});savedId.current=row.id;
  if(file){const {error}=await createClient().storage.from("tenant-media").upload(`${row.id}/logos/logo`,file,{upsert:true,contentType:file.type,cacheControl:"0"});if(error)throw new Error(tr("School saved. Avatar upload failed; retry Save to finish uploading.","Sekolah tersimpan. Unggah avatar gagal; klik Simpan lagi untuk mengunggah."));}
  await cache.invalidateQueries({queryKey:["media"]});await cache.invalidateQueries({queryKey:["school-context"]});close();
 }catch(e){setError(e instanceof Error?e.message:"Unable to save");setConfirm(false);}finally{setBusy(false);}}
 return <form className="p10-tenant-form" onSubmit={e=>{e.preventDefault();setError("");setConfirm(true);}}>
  <div className="p10-form-grid p11-tenant-fields">
   <div><Input name="npsn" label="NPSN" pattern="[0-9]{8}" maxLength={8} inputMode="numeric" list="p10-npsn" value={form.npsn} onChange={e=>{const v=e.target.value;setForm(old=>({...old,npsn:v}));if(v.length===8)void schoolRpc<Reference[]>("school_owner_reference",{resource:"npsn",query:v}).then(rows=>{const match=rows.find(r=>r.npsn===v);if(match)setForm(old=>old.npsn===v?{...old,name:match.name}:old);}).catch(()=>{});}}/><datalist id="p10-npsn">{npsn.data?.map(r=><option key={r.npsn} value={r.npsn}>{r.name}</option>)}</datalist><small>{tr("Type 8 digits. A matching reference fills the school name; otherwise enter it below.","Masukkan 8 digit. Referensi yang cocok mengisi nama sekolah; jika belum ada, isi nama di bawah.")}</small></div>
   <Input name="name" label={tr("School Name","Nama Sekolah")} minLength={2} maxLength={160} required value={form.name} onChange={e=>change("name",e.target.value)}/>
   <Select label={tr("School Group / Foundation (Optional)","Grup Sekolah / Yayasan (Opsional)")} value={form.group_id} onChange={e=>change("group_id",e.target.value)}><option value="">{tr("Independent school","Sekolah mandiri")}</option>{groups.data?.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</Select>
   <div className="p10-form-full"><h3>{tr("School Address","Alamat Sekolah")}</h3></div>
   {regions.map((key,index)=><Select key={key} label={(ind?["Provinsi","Kabupaten / Kota","Kecamatan","Kelurahan / Desa"]:["Province","Regency / City","District","Village"])[index]} disabled={index>0&&!form[regions[index-1]]} value={form[key]} onChange={e=>{const v=e.target.value;setForm(old=>({...old,[key]:v,...Object.fromEntries(regions.slice(index+1).map(k=>[k,""])),postal_code:index===3?lists[index].data?.find(r=>r.code===v)?.postal_code||"":""}));}}><option value="">{tr("Select location","Pilih wilayah")}</option>{lists[index].data?.map(r=><option key={r.code} value={r.code}>{r.name}</option>)}</Select>)}
   <Select label={tr("Postal Code","Kode Pos")} disabled={!form.village_code} value={form.postal_code} onChange={e=>change("postal_code",e.target.value)}><option value="">{tr("Not available / not selected","Belum tersedia / belum dipilih")}</option>{villages.data?.find(r=>r.code===form.village_code)?.postal_code&&<option>{villages.data.find(r=>r.code===form.village_code)?.postal_code}</option>}</Select>
   <Input label={tr("Street & Address Details","Jalan & Detail Alamat")} value={form.address} maxLength={500} onChange={e=>change("address",e.target.value)}/>
   {[["website_url","Website (Optional)","Website (Opsional)","url"],["contact_email","Official School Email (Optional)","Email Resmi Sekolah (Opsional)","email"],["contact_phone","PIC Mobile Number (Optional)","Nomor Ponsel PIC (Opsional)","tel"]].map(([k,en,id,type])=><Input key={k} type={type} label={tr(en,id)} value={form[k]} onChange={e=>change(k,e.target.value)}/>)}
   <Select label={tr("Time Zone","Zona Waktu")} value={form.timezone} onChange={e=>change("timezone",e.target.value)}>{[["Asia/Jakarta","WIB · UTC+7"],["Asia/Makassar","WITA · UTC+8"],["Asia/Jayapura","WIT · UTC+9"]].map(([v,n])=><option key={v} value={v}>{n}</option>)}</Select>
   <Select label={tr("Week Starts On","Awal Minggu")} value={form.week_starts_on} onChange={e=>change("week_starts_on",e.target.value)}><option value="1">{tr("Monday","Senin")}</option><option value="0">{tr("Sunday","Minggu")}</option></Select>
   <Select label={tr("Language","Bahasa")} value={form.locale} onChange={e=>change("locale",e.target.value)}><option value="en-US">English</option><option value="id-ID">Bahasa Indonesia</option></Select>
   <div className="p10-upload p10-form-full"><span>{tr("School Avatar (Optional)","Avatar Sekolah (Opsional)")}</span><label className="ose-file-label"><Upload size={18}/>{tr("Upload / Replace File","Unggah / Ganti Berkas")}<input className="p10-file-input" type="file" aria-label={tr("School avatar","Avatar sekolah")} accept="image/png,image/jpeg,image/webp" onChange={e=>{const chosen=e.target.files?.[0];if(chosen&&validateMedia(chosen,"tenant-media")){setError(tr("Choose PNG, JPEG or WebP up to 5 MB.","Pilih PNG, JPEG, atau WebP maksimal 5 MB."));e.target.value="";return;}setFile(chosen);setError("");}}/></label><small>{file?.name||"PNG / JPEG / WebP · max 5 MB"}</small></div>
  </div>
  {!initial&&<fieldset className="p11-bank-fields"><legend>{tr("School Bank Account (Optional)","Rekening Sekolah (Opsional)")}</legend><p>{tr("Leave all fields empty to add an account later.","Kosongkan seluruh kolom jika rekening akan ditambahkan nanti.")}</p>{[["bank_name","Bank Name","Nama Bank"],["account_name","Account Holder","Nama Pemilik Rekening"],["account_number","Account Number","Nomor Rekening"]].map(([k,en,id])=><Input key={k} label={tr(en,id)} required={Object.values(bank).some(Boolean)} maxLength={k==="account_number"?40:100} pattern={k==="account_number"?"[0-9]{5,40}":undefined} inputMode={k==="account_number"?"numeric":undefined} value={bank[k as keyof typeof bank]} onChange={e=>setBank(b=>({...b,[k]:e.target.value}))}/>)}</fieldset>}
  {lists.some(q=>q.isError)&&<p role="alert">{tr("Location data could not be loaded. Please try again.","Data wilayah gagal dimuat. Silakan coba lagi.")}</p>}
  {error&&<p role="alert" className="school-error">{error}</p>}
  <footer className="owner-form-footer"><Button type="submit" disabled={busy}>{tr("Save","Simpan")}</Button></footer>
  <Modal isOpen={confirm} title={tr("Confirm School Details","Konfirmasi Data Sekolah")} onClose={()=>{if(!busy)setConfirm(false);}}><p>{tr("Save these school details?","Simpan data sekolah ini?")}</p><dl className="p10-confirm"><dt>NPSN</dt><dd>{form.npsn||"—"}</dd><dt>{tr("School","Sekolah")}</dt><dd>{form.name}</dd><dt>{tr("Foundation","Yayasan")}</dt><dd>{groups.data?.find(g=>g.id===form.group_id)?.name||"—"}</dd><dt>{tr("Address","Alamat")}</dt><dd>{[form.address,...lists.map((q,i)=>q.data?.find(r=>r.code===form[regions[i]])?.name),form.postal_code].filter(Boolean).join(", ")||"—"}</dd><dt>{tr("Contact","Kontak")}</dt><dd>{[form.contact_email,form.contact_phone,form.website_url].filter(Boolean).join(" · ")||"—"}</dd><dt>{tr("Time zone / week","Zona waktu / minggu")}</dt><dd>{form.timezone} · {form.week_starts_on==="1"?tr("Monday","Senin"):tr("Sunday","Minggu")}</dd><dt>Avatar</dt><dd>{file?.name||tr("Current avatar","Avatar saat ini")}</dd></dl><Button disabled={busy} onClick={()=>void persist()}>{busy?tr("Saving…","Menyimpan…"):tr("Confirm & Save","Konfirmasi & Simpan")}</Button></Modal>
 </form>;
}
export function FoundationManager(){
 const {locale}=useTranslations(),ind=locale==="id-ID",tr=(en:string,id:string)=>ind?id:en;
 const [open,setOpen]=useState(false),[selected,setSelected]=useState<Reference|null>(null),[name,setName]=useState(""),[people,setPeople]=useState<string[]>([]),[search,setSearch]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const groups=useReference("groups",undefined,"",open),principals=useReference("principals",undefined,search,open),cache=useQueryClient();
 return <><Button variant="ghost" onClick={()=>setOpen(true)}>{tr("School Groups","Grup Sekolah")}</Button>{open&&<OwnerDialog wide title={tr("School Groups / Foundations","Grup Sekolah / Yayasan")} close={()=>setOpen(false)}><div className="p10-foundation-list">{groups.data?.map(g=><Button key={g.id} variant="ghost" onClick={()=>{setSelected(g);setName(g.name);setPeople(g.principals?.map(p=>p.id)||[]);setError("");}}>{g.name}</Button>)}<Button variant="ghost" onClick={()=>{setSelected(null);setName("");setPeople([]);}}>+ {tr("Foundation","Yayasan")}</Button></div><form className="grid gap-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await schoolRpc("school_group_save",{record_id:selected?.id||null,payload:{name,principals:people}});await cache.invalidateQueries({queryKey:["p10-reference","groups"]});await cache.invalidateQueries({queryKey:["school-context"]});setSelected(null);setName("");setPeople([]);}catch(e){setError(e instanceof Error?e.message:"Unable to save");}finally{setBusy(false);}}}><Input label={tr("Foundation Name","Nama Yayasan")} required minLength={2} maxLength={160} value={name} onChange={e=>setName(e.target.value)}/><p>{tr("Assigned Principals can view dashboards of schools in this group. They do not receive or decide approval requests.","Principal yang ditugaskan dapat melihat dashboard sekolah dalam grup ini. Mereka tidak menerima atau memutuskan pengajuan persetujuan.")}</p><Input type="search" label={tr("Find a Principal","Cari Principal")} value={search} onChange={e=>setSearch(e.target.value)}/>{selected?.principals?.filter(p=>!principals.data?.some(u=>u.id===p.id)).map(p=><label key={p.id} className="p10-person-option"><input type="checkbox" checked={people.includes(p.id)} onChange={e=>setPeople(v=>e.target.checked?[...v,p.id]:v.filter(x=>x!==p.id))}/>{p.name}</label>)}{principals.data?.map(p=><label key={p.id} className="p10-person-option"><input type="checkbox" checked={people.includes(p.id)} onChange={e=>setPeople(v=>e.target.checked?[...v,p.id]:v.filter(x=>x!==p.id))}/><span>{p.name}<small>{p.school}</small></span></label>)}{(error||groups.isError||principals.isError)&&<p role="alert">{error||tr("Unable to load foundations or principals.","Gagal memuat yayasan atau Principal.")}</p>}<Button type="submit" disabled={busy}>{tr("Save Foundation","Simpan Yayasan")}</Button></form></OwnerDialog>}</>;
}
