"use client";
import { useState, type FormEvent } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDownLeft, ArrowUpRight, CalendarDays, CheckCircle2, CreditCard, Download, Landmark, Plus, ReceiptText, Wallet } from "lucide-react";
import { usePermissionStore } from "../../stores/permission-store";
import { schoolRpc, useCatalog, useSchoolContext } from "../../lib/school";
import { useTranslations } from "../i18n/i18n-provider";
import { Button, Input, Select } from "../ui";
import { Modal } from "../ui/modal";
import { RecordWorkspace } from "../school/record-workspace";
import { financeSpecs } from "./finance-specs";
import { PaymentButton, PaymentGatewaySettings } from "../finance/payment-gateway";
type Row={id:string;student_id?:string;student_name?:string;invoice_number?:string;receipt_number?:string;description?:string;amount:number;outstanding_amount?:number;paid_amount?:number;due_date?:string;paid_at?:string;entry_date?:string;created_at?:string;days_overdue?:number;status?:string;kind?:string;provider?:string;reference?:string;voided_at?:string};
type Rows={rows:Row[];count:number;balance?:number};
type Summary={today:string;can_manage:boolean;billed:number;collected:number;outstanding:number;overdue:number;due_soon:number;aging:number[];pending_payments:number;students:number};
export const financeMoney=(n:number|string=0)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n));
export function FinanceWorkspace(){
 const {locale}=useTranslations(),tr=(en:string,id:string)=>locale==="id-ID"?id:en,school=useSchoolContext(),context=usePermissionStore(s=>s.context),has=usePermissionStore(s=>s.has),cache=useQueryClient();
 const staff=!!context?.roles.some(r=>r.code==="STAFF"),principal=!!context?.roles.some(r=>r.code==="PRINCIPAL"),parent=!!context?.roles.some(r=>r.code==="PARENT"),admin=staff||principal;
 const [tab,setTab]=useState("overview"),[tenant,setTenant]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(0),[student,setStudent]=useState(""),[status,setStatus]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[reportResource,setReportResource]=useState("bills"),[manage,setManage]=useState("");
 const [composer,setComposer]=useState(false),[cashForm,setCashForm]=useState(false),[selected,setSelected]=useState<Row[]>([]),[pay,setPay]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const args={target_tenant:tenant||null},filters={query,student_id:student,status,from,to};
 const summary=useQuery({queryKey:["school-finance11",context?.userId,tenant,"overview"],enabled:!!context,queryFn:()=>schoolRpc<Summary>("school_finance11",{...args})});
 const resource=tab==="reports"?reportResource:tab==="billing"?"bills":tab==="overview"?"bills":tab==="settings"?"bills":tab;
 const rows=useQuery({queryKey:["school-finance11",context?.userId,tenant,resource,filters,page],enabled:!!context&&tab!=="settings",queryFn:()=>schoolRpc<Rows>("school_finance11",{...args,resource,filters,page_offset:page*100})});
 const recent=useQuery({queryKey:["school-finance11",context?.userId,tenant,"recent"],enabled:!!context&&tab==="overview",queryFn:()=>schoolRpc<Rows>("school_finance11",{...args,resource:"payments"})});
 const children=school.data?.children??[];
 const tabs=admin?[["overview",tr("Overview","Ringkasan")],["billing",tr("Billing","Tagihan")],["collections",tr("Collections","Penagihan")],["payments",tr("Payments","Pembayaran")],["students",tr("Students","Siswa")],["cash",tr("Cash & Expenses","Kas & Pengeluaran")],["reconciliation",tr("Reconciliation","Rekonsiliasi")],["reports",tr("Reports","Laporan")],...(staff?[["settings",tr("Settings","Pengaturan")]]:[])]:[["overview",tr("Overview","Ringkasan")],["billing",tr("Family Bills","Tagihan Keluarga")],["payments",tr("Payment History","Riwayat Pembayaran")],["reports",tr("Receipts & Reports","Kuitansi & Laporan")]];
 function navigate(next:string){setTab(next);setPage(0);setStatus("");setQuery("");setManage("");setMessage("");setError("");}
 async function refresh(){await Promise.all([cache.invalidateQueries({queryKey:["school-finance11"]}),cache.invalidateQueries({queryKey:["school-finance"]})]);}
 async function exportFile(format:"pdf"|"csv"){setBusy(true);setError("");try{const all:Row[]=[];for(let offset=0;;offset+=100){const chunk=await schoolRpc<Rows>("school_finance11",{...args,resource,filters,page_offset:offset});all.push(...chunk.rows);if(offset+100>=chunk.count)break;}const headers=[tr("Reference","Referensi"),tr("Student / Description","Siswa / Deskripsi"),tr("Date","Tanggal"),"Status",tr("Amount","Nominal"),tr("Outstanding","Sisa Tagihan")],values=all.map(r=>[r.receipt_number||r.invoice_number||r.id,r.student_name||r.description||r.provider||"",r.due_date||r.entry_date||(r.paid_at||r.created_at||"").slice(0,10),r.status||(r.voided_at?"VOID":r.kind)||"",String(r.amount),r.outstanding_amount===undefined?"":String(r.outstanding_amount)]);
 if(format==="pdf"){const {reportPdf,downloadPdf}=await import("../../lib/school-pdf");const bytes=await reportPdf(`${tr("Financial Report","Laporan Keuangan")} · ${tabs.find(t=>t[0]===tab)?.[1]||resource}`,school.data?.tenant.name||"OSEKOLA",[`${tr("Transactions","Transaksi")}: ${all.length}`,`${from||"—"} - ${to||"—"}`],values);downloadPdf(bytes,`osekola-${resource}.pdf`);}else{const cell=(v:string)=>'"'+( /^[=+\-@\t\r]/.test(v)?"'"+v:v).replaceAll('"','""')+'"';const csv="\uFEFF"+[headers,...values].map(r=>r.map(cell).join(",")).join("\r\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=`osekola-${resource}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 }catch(e){setError(e instanceof Error?e.message:tr("Export failed","Ekspor gagal"));}finally{setBusy(false);}}
 async function saveCash(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const f=new FormData(e.currentTarget);await schoolRpc("school_cash_entries",{action:"CREATE",payload:{...Object.fromEntries(f),amount:Number(f.get("amount"))}});await refresh();setCashForm(false);}catch(e){setError(e instanceof Error?e.message:"Unable to save");}finally{setBusy(false);}}
 const title=tabs.find(t=>t[0]===tab)?.[1]||"O-Finance",totals=summary.data;
 const payable=rows.data?.rows.filter(r=>r.outstanding_amount&&!["DRAFT","VOID","PAID"].includes(r.status||""))??[];
 return <section className="p11-finance">
  <div className="p11-finance-top"><div><p className="ose-eyebrow">O-FINANCE</p><h2>{admin?tr("Your school's financial picture","Keuangan sekolah, dalam satu pandangan"):tr("School payments, made simple","Pembayaran sekolah jadi lebih mudah")}</h2><p>{admin?tr("See what has arrived, what is due, and what needs your attention.","Pantau dana masuk, tagihan jatuh tempo, dan hal yang perlu ditindaklanjuti."):tr("View your children's bills and payment history together.","Lihat tagihan anak dan riwayat pembayaran dalam satu tempat.")}</p></div><span className="p11-finance-seal"><Wallet size={22}/>{school.data?.tenant.name}</span></div>
  <nav className="p11-finance-nav" aria-label="O-Finance">{tabs.map(([v,l])=><button key={v} aria-current={tab===v?"page":undefined} onClick={()=>navigate(v)}>{l}</button>)}</nav>
  {principal&&!!school.data?.foundation_schools?.length&&<Select label={tr("School","Sekolah")} value={tenant} onChange={e=>{setTenant(e.target.value);setPage(0);}}><option value="">{school.data.tenant.name}</option>{school.data.foundation_schools.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</Select>}
  {(summary.isError||rows.isError||recent.isError||error)&&<p className="school-error" role="alert">{error||summary.error?.message||rows.error?.message||recent.error?.message}<Button variant="ghost" onClick={()=>void refresh()}>{tr("Retry","Coba Lagi")}</Button></p>}{message&&<p role="status">{message}</p>}
  {tab==="overview"&&<>
   <div className="p11-money-cards">{[[tr("Billed","Ditagihkan"),totals?.billed,ReceiptText],[tr("Collected","Diterima"),totals?.collected,ArrowDownLeft],[tr("Outstanding","Belum Dibayar"),totals?.outstanding,Wallet],[tr("Overdue","Lewat Jatuh Tempo"),totals?.overdue,CalendarDays]].map(([label,value,Icon],i)=>{const Component=Icon as typeof Wallet;return <button key={String(label)} className={`p11-money-card p11-money-${i}`} onClick={()=>navigate(i===1?"payments":i===3&&admin?"collections":"billing")}><span><Component size={19}/>{String(label)}</span><strong>{value===undefined?"—":financeMoney(Number(value))}</strong><small>{i===3?tr("Requires follow-up","Perlu tindak lanjut"):i===1?tr("Confirmed payments","Pembayaran terkonfirmasi"):tr("View details","Lihat detail")} <ArrowUpRight size={14}/></small></button>;})}</div>
   <div className="p11-finance-overview"><section className="p11-panel p11-attention"><header><h3>{tr("Needs Attention","Perlu Perhatian")}</h3><span className="p11-status-pill">{tr("Today","Hari Ini")}</span></header>{Number(totals?.overdue)>0&&<button onClick={()=>navigate(admin?"collections":"billing")}><CalendarDays/><span><strong>{financeMoney(totals!.overdue)}</strong><small>{tr("Past-due bills to follow up","Tagihan lewat jatuh tempo untuk ditindaklanjuti")}</small></span><ArrowUpRight/></button>}{Number(totals?.due_soon)>0&&<button onClick={()=>navigate("billing")}><ReceiptText/><span><strong>{financeMoney(totals!.due_soon)}</strong><small>{tr("Due in the next 7 days","Jatuh tempo dalam 7 hari")}</small></span><ArrowUpRight/></button>}{admin&&Number(totals?.pending_payments)>0&&<button onClick={()=>{navigate("payments");setStatus("PENDING");}}><CreditCard/><span><strong>{totals!.pending_payments} {tr("payments","pembayaran")}</strong><small>{tr("Awaiting confirmation","Menunggu konfirmasi")}</small></span><ArrowUpRight/></button>}{totals&&!Number(totals.overdue)&&!Number(totals.due_soon)&&!Number(totals.pending_payments)&&<div className="p11-clear"><CheckCircle2/><p>{tr("Everything is up to date.","Semua sudah tertangani.")}</p></div>}{staff&&<Button onClick={()=>setComposer(true)}><Plus size={17}/>{tr("Create Billing Plan","Buat Rencana Tagihan")}</Button>}{parent&&payable.length>0&&<Button onClick={()=>{navigate("billing");}}>{tr("Review & Pay","Lihat & Bayar")}</Button>}</section>
    <section className="p11-panel"><header><h3>{tr("Receivables by Age","Umur Piutang")}</h3></header><div className="p11-aging">{(totals?.aging??[0,0,0,0,0]).map((value,i)=><div key={i}><span>{[tr("Not Yet Due","Belum Jatuh Tempo"),"1–30 "+tr("days","hari"),"31–60 "+tr("days","hari"),"61–90 "+tr("days","hari"),">90 "+tr("days","hari")][i]}</span><progress value={Number(value)} max={Math.max(Number(totals?.outstanding)||0,1)}/><strong>{financeMoney(value)}</strong></div>)}</div></section>
   </div>
   <section className="p11-panel"><header><div><p className="ose-eyebrow">MONEY TIMELINE</p><h3>{tr("Recent Payment Activity","Aktivitas Pembayaran Terbaru")}</h3></div><Button variant="ghost" onClick={()=>navigate("payments")}>{tr("View All","Lihat Semua")}</Button></header><div className="p11-money-timeline">{recent.data?.rows.slice(0,6).map(r=><div key={r.id}><span className="p11-timeline-icon"><ArrowDownLeft size={18}/></span><div><strong>{r.student_name}</strong><small>{r.receipt_number} · {r.paid_at?.slice(0,10)}</small></div><span><strong>{financeMoney(r.amount)}</strong><small>{r.status}</small></span></div>)}{!recent.isLoading&&!recent.data?.count&&<p className="school-empty">{tr("Payments will appear here when recorded.","Pembayaran akan tampil di sini setelah dicatat.")}</p>}</div></section>
  </>}
  {tab!=="overview"&&tab!=="settings"&&<section className="p11-panel"><header><div><p className="ose-eyebrow">O-FINANCE</p><h3>{title}</h3>{tab==="collections"&&<p>{tr("Outstanding balances with a past due date.","Sisa tagihan yang telah melewati jatuh tempo.")}</p>}{tab==="reconciliation"&&<p>{tr("Provider-confirmed payments are matched automatically. Unknown or creating transactions need review before another charge.","Pembayaran terkonfirmasi penyedia dicocokkan otomatis. Transaksi berstatus Unknown atau Creating perlu diperiksa sebelum pembayaran baru.")}</p>}</div><div className="owner-actions">{staff&&tab==="billing"&&<Button onClick={()=>setComposer(true)}><Plus size={16}/>{tr("Billing Plan","Rencana Tagihan")}</Button>}{staff&&tab==="cash"&&<Button onClick={()=>{setError("");setCashForm(true);}}>+ {tr("Cash Entry","Transaksi Kas")}</Button>}{staff&&["billing","payments"].includes(tab)&&<Button variant="ghost" onClick={()=>setManage(manage?"":tab==="billing"?"student_bills":"payments")}>{manage?tr("Back to Overview","Kembali ke Ringkasan"):tr("Manage Records","Kelola Transaksi")}</Button>}<Button variant="ghost" disabled={busy||!rows.data?.count} onClick={()=>void exportFile("pdf")}><Download size={16}/> PDF</Button><Button variant="ghost" disabled={busy||!rows.data?.count} onClick={()=>void exportFile("csv")}>Excel (CSV)</Button></div></header>
   {manage?<RecordWorkspace specs={financeSpecs.filter(s=>s.key===manage&&has(`${s.permission}.read`))}/>:<>
    <div className="p11-finance-filters"><Input type="search" label={tr("Search","Cari")} placeholder={tr("Student or reference…","Siswa atau referensi…")} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/>{!admin&&children.length>0&&<Select label={tr("Child","Anak")} value={student} onChange={e=>{setStudent(e.target.value);setPage(0);}}><option value="">{tr("All Children","Semua Anak")}</option>{children.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select>}{tab==="reports"&&<Select label={tr("Report","Laporan")} value={reportResource} onChange={e=>{setReportResource(e.target.value);setPage(0);setStatus("");}}><option value="bills">{tr("Bills","Tagihan")}</option><option value="payments">{tr("Payments","Pembayaran")}</option></Select>}{!["cash","collections","students"].includes(tab)&&<Select label="Status" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">{tr("All Statuses","Semua Status")}</option>{(resource==="payments"?["PENDING","CONFIRMED","VOID","REFUNDED"]:resource==="reconciliation"?["PAID","OPEN","UNKNOWN","CREATING","FAILED","EXPIRED"]:["OPEN","PARTIAL","PAID","OVERDUE",...(admin?["DRAFT","VOID"]:[])]).map(s=><option key={s}>{s}</option>)}</Select>}{tab==="reports"&&<><Input type="date" label={tr("From","Dari")} value={from} onChange={e=>{setFrom(e.target.value);setPage(0);}}/><Input type="date" label={tr("To","Sampai")} value={to} onChange={e=>{setTo(e.target.value);setPage(0);}}/></>}</div>
    {tab==="cash"&&<div className="p11-cash-balance"><Landmark/><span>{tr("Recorded Cash Balance","Saldo Kas Tercatat")}</span><strong>{financeMoney(rows.data?.balance??0)}</strong><small>{tr("Includes confirmed receipts and cash entries.","Termasuk penerimaan terkonfirmasi dan transaksi kas.")}</small></div>}
    {parent&&tab==="billing"&&selected.length>0&&<div className="p11-pay-selection"><span>{selected.length} {tr("bills selected","tagihan dipilih")} · {financeMoney(selected.reduce((s,r)=>s+Number(r.outstanding_amount??0),0))}</span><Button onClick={()=>setPay(true)}>{tr("Pay Selected Bills","Bayar Tagihan Pilihan")}</Button><Button variant="ghost" onClick={()=>setSelected([])}>{tr("Clear","Hapus Pilihan")}</Button></div>}
    {rows.isLoading?<p role="status">{tr("Loading transactions…","Memuat transaksi…")}</p>:<div className="school-table-scroll"><table className="school-table p11-finance-table"><thead><tr>{parent&&tab==="billing"&&<th><input type="checkbox" aria-label={tr("Select all payable bills on this page","Pilih semua tagihan yang dapat dibayar di halaman ini")} checked={payable.length>0&&payable.every(r=>selected.some(s=>s.id===r.id))} onChange={e=>setSelected(e.target.checked?payable:[])}/></th>}<th>{tr("Student / Description","Siswa / Deskripsi")}</th><th>{tr("Reference","Referensi")}</th><th>{tr("Date","Tanggal")}</th><th>Status</th><th>{tr("Amount","Nominal")}</th>{["bills","collections","students"].includes(resource)&&<th>{tr("Outstanding","Sisa Tagihan")}</th>}</tr></thead><tbody>{rows.data?.rows.map(r=><tr key={r.id}>{parent&&tab==="billing"&&<td><input type="checkbox" aria-label={`${tr("Select","Pilih")} ${r.invoice_number}`} disabled={!r.outstanding_amount||["DRAFT","VOID","PAID"].includes(r.status||"")} checked={selected.some(s=>s.id===r.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,r]:v.filter(s=>s.id!==r.id))}/></td>}<td><strong>{r.student_name||r.description||r.provider}</strong>{!!r.days_overdue&&<small className="p11-overdue">{r.days_overdue} {tr("days overdue","hari terlambat")}</small>}</td><td>{r.receipt_number||r.invoice_number||r.reference||r.kind||"—"}</td><td>{r.due_date||r.entry_date||(r.paid_at||r.created_at||"").slice(0,10)}</td><td><span className="p11-status-pill" data-status={r.status}>{r.status||(r.voided_at?"VOID":r.kind)}</span></td><td>{financeMoney(r.amount)}</td>{["bills","collections","students"].includes(resource)&&<td><strong>{financeMoney(r.outstanding_amount??0)}</strong>{(parent||staff)&&Number(r.outstanding_amount)>0&&!["DRAFT","VOID","PAID"].includes(r.status||"")&&<PaymentButton target={r.id} onPaid={()=>void refresh()}/>}</td>}</tr>)}</tbody></table>{!rows.isError&&!rows.data?.count&&<p className="school-empty">{tr("No transactions match these filters.","Belum ada transaksi yang sesuai filter.")}</p>}</div>}
    <div className="school-pagination"><Button variant="ghost" disabled={!page||rows.isFetching} onClick={()=>setPage(p=>p-1)}>←</Button><span>{page+1} · {rows.data?.count??0} {tr("records","data")}</span><Button variant="ghost" disabled={(page+1)*100>=(rows.data?.count??0)||rows.isFetching} onClick={()=>setPage(p=>p+1)}>→</Button></div>
   </>}
  </section>}
  {tab==="settings"&&staff&&<><section className="p11-panel"><h3>{tr("Accounts, Categories & Periods","Rekening, Kategori & Periode")}</h3><RecordWorkspace specs={financeSpecs.filter(s=>["finance_accounts","finance_categories","finance_periods"].includes(s.key)&&has(`${s.permission}.read`))}/></section><PaymentGatewaySettings/></>}
  <Modal isOpen={composer} onClose={()=>setComposer(false)} title={tr("Create Billing Plan","Buat Rencana Tagihan")}>{composer&&<BillingComposer onDone={async()=>{setComposer(false);setMessage(tr("Billing plan published. Student invoices are ready.","Rencana tagihan diterbitkan. Tagihan siswa sudah tersedia."));await refresh();}}/>}</Modal>
  <Modal isOpen={cashForm} onClose={()=>{if(!busy)setCashForm(false);}} title={tr("Record Cash Movement","Catat Pergerakan Kas")}><form className="p11-form" onSubmit={e=>void saveCash(e)}><Select name="kind" label={tr("Type","Jenis")}><option value="INCOME">{tr("Cash In","Kas Masuk")}</option><option value="EXPENSE">{tr("Expense","Pengeluaran")}</option><option value="OPENING_BALANCE">{tr("Opening Balance","Saldo Awal")}</option></Select><Input name="description" label={tr("Description","Keterangan")} required minLength={3} maxLength={500}/><Input name="amount" type="number" min={1} step={1} label={tr("Amount (Rp)","Nominal (Rp)")} required/><Input name="entry_date" type="date" defaultValue={totals?.today} label={tr("Date","Tanggal")} required/>{error&&<p role="alert">{error}</p>}<Button type="submit" disabled={busy}>{tr("Save","Simpan")}</Button></form></Modal>
  <Modal isOpen={pay} onClose={()=>setPay(false)} title={tr("Selected Family Bills","Tagihan Keluarga Pilihan")}><p>{tr("Complete each bill through the school's secure payment provider. Confirmed payments update automatically.","Selesaikan setiap tagihan melalui penyedia pembayaran sekolah. Pembayaran terkonfirmasi diperbarui otomatis.")}</p>{selected.map(r=><section className="p11-panel" key={r.id}><strong>{r.student_name} · {r.invoice_number}</strong><p>{financeMoney(r.outstanding_amount??0)}</p><PaymentButton target={r.id} onPaid={()=>{setSelected(s=>s.filter(i=>i.id!==r.id));void refresh();}}/></section>)}</Modal>
 </section>;
}
function BillingComposer({onDone}:{onDone:()=>Promise<void>}){
 const {locale}=useTranslations(),tr=(en:string,id:string)=>locale==="id-ID"?id:en,students=useCatalog("students"),categories=useCatalog("finance:finance_categories");const [query,setQuery]=useState(""),[selected,setSelected]=useState<string[]>([]),[amount,setAmount]=useState(""),[discount,setDiscount]=useState("0"),[occurrences,setOccurrences]=useState("1"),[requestKey]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState("");
 return <form className="p11-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{const f=new FormData(e.currentTarget);await schoolRpc("school_billing11",{payload:{...Object.fromEntries(f),students:selected,amount:Number(amount),discount:Number(discount),occurrences:Number(occurrences),request_key:requestKey}});await onDone();}catch(e){setError(e instanceof Error?e.message:"Unable to publish");}finally{setBusy(false);}}}>
 <Input name="name" label={tr("Plan Name","Nama Rencana Tagihan")} placeholder={tr("Tuition · School Year 2026/27","SPP · Tahun Ajaran 2026/27")} required minLength={2} maxLength={160}/><Select name="category_id" label={tr("Income Category","Kategori Penerimaan")} required><option value="">{tr("Choose category","Pilih kategori")}</option>{categories.data?.filter(c=>!c.category_type||c.category_type==="INCOME").map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><div className="p11-form-pair"><Input name="amount" type="number" min={1} step={1} label={tr("Amount per Student (Rp)","Nominal per Siswa (Rp)")} required value={amount} onChange={e=>setAmount(e.target.value)}/><Input name="discount" type="number" min={0} max={Math.max(0,Number(amount)-1)} step={1} label={tr("Discount / Scholarship (Rp)","Diskon / Beasiswa (Rp)")} value={discount} onChange={e=>setDiscount(e.target.value)}/></div><Input name="first_due" type="date" label={tr("First Due Date","Jatuh Tempo Pertama")} required/><Select name="occurrences" label={tr("Schedule","Jadwal")} value={occurrences} onChange={e=>setOccurrences(e.target.value)}>{[1,3,6,12,24,36].map(n=><option key={n} value={n}>{n===1?tr("One-time","Sekali Bayar"):`${n} ${tr("monthly invoices","tagihan bulanan")}`}</option>)}</Select><fieldset className="p11-people"><legend>{tr("Students","Siswa")} · {selected.length}</legend><Input type="search" aria-label={tr("Find student","Cari siswa")} value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={!!students.data?.length&&selected.length===students.data.length} onChange={e=>setSelected(e.target.checked?students.data?.map(s=>s.id)??[]:[])}/>{tr("Select All","Pilih Semua")}</label><div>{students.data?.filter(s=>!query||String(s.name||s.full_name||s.student_number).toLowerCase().includes(query.toLowerCase())).map(s=><label key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,s.id]:v.filter(x=>x!==s.id))}/>{String(s.name||s.full_name||s.student_number)}</label>)}</div></fieldset><div className="p11-billing-preview"><small>{tr("Publish Preview","Pratinjau Penerbitan")}</small><strong>{selected.length*Number(occurrences)} {tr("invoices","tagihan")} · {financeMoney(Math.max(0,Number(amount)-Number(discount))*selected.length*Number(occurrences))}</strong><p>{tr("Invoices for the full selected schedule are published together. Check the students, dates and total before publishing.","Seluruh tagihan pada jadwal terpilih diterbitkan sekaligus. Periksa siswa, tanggal, dan total sebelum menerbitkan.")}</p></div>{(error||students.isError||categories.isError)&&<p role="alert">{error||students.error?.message||categories.error?.message}</p>}<Button type="submit" disabled={busy||!selected.length||students.isError||categories.isError}>{busy?tr("Publishing…","Menerbitkan…"):tr("Publish Invoices","Terbitkan Tagihan")}</Button>
 </form>;
}
