"use client";
import { useRef, useState, type FormEvent } from "react";
import { useSearchParams } from "next/navigation";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, CheckCircle2, FileText, GripVertical, Plus, Users } from "lucide-react";
import { schoolRpc, useSchoolContext, useCatalog } from "../../lib/school";
import { usePermissionStore } from "../../stores/permission-store";
import { useTranslations } from "../i18n/i18n-provider";
import { PersonPicker } from "../part10/person-picker";
import { Button, Input, Select } from "../ui";
import { Modal } from "../ui/modal";
import { ProjectEvidence } from "./project-evidence";

export type Person = {id:string;name:string};
export type Project = {id:string;tenant_id:string;code:string;name:string;description?:string;status:string;starts_on?:string;due_on?:string;can_manage?:boolean;task_count:number;done_count:number};
export type Task = {id:string;title:string;description?:string;status:string;priority:string;starts_on?:string;due_date?:string;parent_task_id?:string;assignees:Person[];can_edit:boolean};
export type ProjectData = {project:Project;can_manage:boolean;complete:boolean;task_count:number;tasks:Task[];committee:{id:string;name:string;position:string}[];invoices:{id:string;invoice_number:string;description:string;amount:number;due_date:string;status:string}[];payments:{id:string;receipt_number:string;amount:number;paid_at:string;status:string}[];comments:{id:string;task_id:string;body:string;created_at:string;name:string}[]};
const statuses = ["TODO","IN_PROGRESS","BLOCKED","DONE"] as const;
const normalized = (status:string) => status==="BACKLOG"?"TODO":status==="REVIEW"?"IN_PROGRESS":status;
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
export function ProjectWorkspace(){
 const {locale}=useTranslations(),tr=(en:string,id:string)=>locale==="id-ID"?id:en;
 const school=useSchoolContext(),userId=usePermissionStore(s=>s.context?.userId),cache=useQueryClient();
 const params=useSearchParams();
 const [selected,setSelected]=useState(""),[tenant,setTenant]=useState(""),[page,setPage]=useState(0),[view,setView]=useState("board"),[filter,setFilter]=useState("");
 const draggedTask=useRef("");
 const [dialog,setDialog]=useState<"create"|"task"|"member"|"project"|"invoice"|"payment">(),[task,setTask]=useState<Task>(),[parent,setParent]=useState(""),[detail,setDetail]=useState<Task>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const projects=useQuery({queryKey:["team11",userId,tenant,page],enabled:!!userId,queryFn:()=>schoolRpc<{projects:Project[];count:number;can_create:boolean}>("school_project11",{action:"list",page_offset:page*50,target_tenant:tenant||null})});
 const projectId=selected||(!tenant&&!page?params.get("project"):null)||projects.data?.projects[0]?.id||"";
 const board=useQuery({queryKey:["team11-detail",userId,projectId],enabled:!!projectId,queryFn:async()=>{const first=await schoolRpc<ProjectData>("school_project11",{action:"read",project_uuid:projectId});const all=[...first.tasks];for(let offset=100;offset<first.task_count;offset+=100){const more=await schoolRpc<ProjectData>("school_project11",{action:"read",project_uuid:projectId,page_offset:offset});all.push(...more.tasks);}return {...first,tasks:all};}});
 const allUsers=useCatalog("users",dialog==="create");
 const people=useQuery({queryKey:["team11-people",userId,projectId],enabled:!!projectId&&!!board.data?.can_manage,queryFn:async()=>{const all:Person[]=[];for(let offset=0;;offset+=500){const rows=await schoolRpc<Person[]>("school_project11",{action:"people",project_uuid:projectId,page_offset:offset});all.push(...rows);if(rows.length<500)break;}return all;}});
 async function refresh(){await Promise.all([cache.invalidateQueries({queryKey:["team11"]}),cache.invalidateQueries({queryKey:["team11-detail"]}),cache.invalidateQueries({queryKey:["school-calendar"]}),cache.invalidateQueries({queryKey:["notifications"]})]);}
 async function action(kind:string,payload:Record<string,unknown>,recordId?:string){setBusy(true);setError("");try{await schoolRpc("school_project11",{action:kind,project_uuid:projectId,payload,record_id:recordId||null});await refresh();setDialog(undefined);setTask(undefined);return true;}catch(e){setError(e instanceof Error?e.message:tr("Unable to save","Gagal menyimpan"));return false;}finally{setBusy(false);}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),payload:Record<string,unknown>=Object.fromEntries(f);if(dialog==="create"){setBusy(true);setError("");try{const result=await schoolRpc<{id:string}>("school_project_template",{payload:{...payload,committee:Object.fromEntries(["CHAIR","SECRETARY","TREASURER"].map(k=>[k,f.get(k)]))}});setSelected(result.id);setDialog(undefined);await refresh();}catch(e){setError(e instanceof Error?e.message:tr("Unable to create project","Gagal membuat proyek"));}finally{setBusy(false);}return;}
 if(dialog==="task"){payload.assignees=f.getAll("assignees");payload.parent_task_id=f.get("parent_task_id")||null;await action("task",payload,task?.id);}else if(dialog)await action(dialog,payload);}
 const d=board.data,labels=locale==="id-ID"?["Akan Dikerjakan","Sedang Dikerjakan","Terhambat","Selesai"]:["To Do","In Progress","Blocked","Done"];
 const tasks=d?.tasks.filter(t=>!filter||t.title.toLowerCase().includes(filter.toLowerCase())||t.assignees.some(p=>p.name.toLowerCase().includes(filter.toLowerCase())))??[];
 function open(kind:typeof dialog){setError("");setDialog(kind);}
 return <section className="p11-project" aria-label="O-Team">
  <div className="p11-project-toolbar">
   <div className="p11-project-switch"><Select label={tr("Project","Proyek")} value={projectId} onChange={e=>{setSelected(e.target.value);setDetail(undefined);setError("");}}><option value="">{tr("Choose project","Pilih proyek")}</option>{projects.data?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}{selected&&!projects.data?.projects.some(p=>p.id===selected)&&d&&<option value={selected}>{d.project.name}</option>}</Select>
    {!!school.data?.foundation_schools?.length&&<Select label={tr("School","Sekolah")} value={tenant} onChange={e=>{setTenant(e.target.value);setSelected("");setPage(0);}}><option value="">{school.data.tenant.name}</option>{school.data.foundation_schools.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</Select>}
   </div>{projects.data?.can_create&&<Button onClick={()=>open("create")}><Plus size={16}/> Project</Button>}
  </div>
  {(projects.isError||board.isError||people.isError)&&<p role="alert" className="school-error">{projects.error?.message||board.error?.message||people.error?.message}<Button variant="ghost" onClick={()=>void refresh()}>{tr("Retry","Coba Lagi")}</Button></p>}
  {(projects.data?.count??0)>50&&<div className="school-pagination"><Button disabled={!page} onClick={()=>{setPage(p=>p-1);setSelected("");}}>←</Button><span>{page+1}</span><Button disabled={(page+1)*50>=(projects.data?.count??0)} onClick={()=>{setPage(p=>p+1);setSelected("");}}>→</Button></div>}
  {projects.isLoading||board.isLoading?<p role="status">{tr("Loading workspace…","Memuat ruang kerja…")}</p>:d?<>
   <header className="p11-project-summary"><div><p className="ose-eyebrow">{d.project.code} · O-TEAM</p><h2>{d.project.name}</h2><p>{d.project.description}</p><span><CalendarDays size={15}/>{d.project.starts_on||"—"} → {d.project.due_on||"—"}</span></div><div className="p11-project-progress"><strong>{d.tasks.filter(t=>t.status==="DONE").length}<small> / {d.task_count}</small></strong><span>{tr("tasks completed","tugas selesai")}</span><progress value={d.tasks.filter(t=>t.status==="DONE").length} max={Math.max(d.task_count,1)}/></div></header>
   <div className="p11-board-tools"><nav className="school-tabs" aria-label={tr("Project views","Tampilan proyek")}>{[["board",tr("Board","Papan Tugas")],["committee",tr("Committee","Panitia")],["finance",tr("Project Finance","Keuangan Proyek")]].map(([v,l])=><button key={v} aria-current={view===v?"page":undefined} onClick={()=>setView(v)}>{l}</button>)}</nav><div className="owner-actions">{d.can_manage&&<><Button variant="ghost" onClick={()=>open("project")}>{tr("Timeline","Jadwal")}</Button><Button onClick={()=>{setTask(undefined);setParent("");open("task");}}><Plus size={16}/>{tr("Task","Tugas")}</Button></>}</div></div>
   {error&&!dialog&&<p role="alert" className="school-error">{error}</p>}
   {view==="board"&&<><div className="p11-board-search"><Input type="search" label={tr("Find a task or person","Cari tugas atau penanggung jawab")} value={filter} onChange={e=>setFilter(e.target.value)}/><p>{tr("Drag a task to move it. You can also use its status menu.","Geser tugas untuk memindahkannya, atau gunakan menu status.")}</p></div><div className="p11-kanban">{statuses.map((status,i)=><section className="p11-kanban-column" data-status={status} key={status} aria-label={labels[i]} onDragOver={e=>{if(draggedTask.current){e.preventDefault();e.dataTransfer.dropEffect="move";}}} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData("text/plain")||draggedTask.current;draggedTask.current="";if(id&&!busy&&d.tasks.some(t=>t.id===id&&t.can_edit))void action("move",{status},id);}}><h3><span className="p11-status-dot"/>{labels[i]}<small>{tasks.filter(t=>normalized(t.status)===status).length}</small></h3><div className="p11-kanban-cards">{tasks.filter(t=>normalized(t.status)===status).map(t=><article key={t.id} className="p11-task-card" draggable={t.can_edit&&!busy} onDragStart={e=>{draggedTask.current=t.id;e.dataTransfer.setData("text/plain",t.id);e.dataTransfer.effectAllowed="move";}} onDragEnd={()=>{draggedTask.current="";}}><div className="p11-task-top"><span>{t.priority}</span>{t.can_edit&&<GripVertical size={15} aria-hidden="true"/>}</div>{t.parent_task_id&&<small className="p11-parent-task">↳ {d.tasks.find(p=>p.id===t.parent_task_id)?.title}</small>}<button className="p11-task-title" onClick={()=>setDetail(t)}>{t.title}</button><div className="p11-task-meta">{t.due_date&&<span><CalendarDays size={13}/>{t.due_date}</span>}{d.tasks.some(k=>k.parent_task_id===t.id)&&<span><CheckCircle2 size={13}/>{d.tasks.filter(k=>k.parent_task_id===t.id&&k.status==="DONE").length}/{d.tasks.filter(k=>k.parent_task_id===t.id).length}</span>}</div><div className="p11-assignees">{t.assignees.map(p=><span key={p.id} title={p.name}>{p.name}</span>)}{!t.assignees.length&&<small>{tr("Unassigned","Belum Ditugaskan")}</small>}</div>{t.can_edit&&<Select aria-label={`${tr("Status for","Status untuk")} ${t.title}`} value={normalized(t.status)} disabled={busy} onChange={e=>void action("move",{status:e.target.value},t.id)}>{statuses.map((s,j)=><option key={s} value={s}>{labels[j]}</option>)}</Select>}{d.can_manage&&<footer><button onClick={()=>{setTask(t);setParent(t.parent_task_id||"");open("task");}}>{tr("Edit","Edit")}</button>{!t.parent_task_id&&<button onClick={()=>{setTask(undefined);setParent(t.id);open("task");}}>+ {tr("Subtask","Subtugas")}</button>}</footer>}</article>)}{!tasks.some(t=>normalized(t.status)===status)&&<p className="p11-column-empty">{tr("No tasks","Belum Ada Tugas")}</p>}</div></section>)}</div></>}
   {view==="committee"&&<section className="p11-panel"><header><h3><Users size={20}/>{tr("Project Committee","Panitia Proyek")}</h3>{d.can_manage&&<Button onClick={()=>open("member")}>+ {tr("Member","Anggota")}</Button>}</header><div className="p11-committee">{d.committee.map(p=><div key={p.id}><small>{({CHAIR:tr("Chair / PIC","Ketua / PIC"),SECRETARY:tr("Secretary","Sekretaris"),TREASURER:tr("Treasurer","Bendahara"),COORDINATOR:tr("Coordinator","Koordinator"),MEMBER:tr("Member","Anggota")} as Record<string,string>)[p.position]}</small><strong>{p.name}</strong></div>)}</div></section>}
   {view==="finance"&&<section className="p11-panel"><header><h3>{tr("Project Finance","Keuangan Proyek")}</h3>{d.can_manage&&<div className="owner-actions"><Button variant="ghost" onClick={()=>open("invoice")}>+ {tr("Invoice","Tagihan")}</Button><Button onClick={()=>open("payment")}>+ {tr("Payment","Pembayaran")}</Button></div>}</header><div className="p11-metrics">{[[tr("Invoiced","Ditagihkan"),d.invoices.filter(i=>!["VOID","DRAFT"].includes(i.status)).reduce((s,i)=>s+Number(i.amount),0)],[tr("Collected","Diterima"),d.payments.filter(p=>p.status==="CONFIRMED").reduce((s,p)=>s+Number(p.amount),0)]].map(([k,v])=><div key={k}><small>{k}</small><strong>{money(Number(v))}</strong></div>)}</div><div className="school-table-scroll"><table className="school-table"><thead><tr><th>{tr("Reference","Referensi")}</th><th>{tr("Date","Tanggal")}</th><th>Status</th><th>{tr("Amount","Nominal")}</th></tr></thead><tbody>{d.invoices.map(i=><tr key={i.id}><td>{i.invoice_number}</td><td>{i.due_date}</td><td>{i.status}</td><td>{money(Number(i.amount))}</td></tr>)}{d.payments.map(p=><tr key={p.id}><td>{p.receipt_number}</td><td>{p.paid_at.slice(0,10)}</td><td>{p.status}</td><td>{money(Number(p.amount))}</td></tr>)}</tbody></table></div></section>}
   {d.complete&&<ProjectEvidence data={d}/>}
  </>:<div className="p11-panel school-empty"><FileText size={30}/><h2>{tr("Create your first O-Team project","Buat proyek O-Team pertama Anda")}</h2><p>{tr("Projects assigned to you will appear here.","Proyek yang ditugaskan kepada Anda akan tampil di sini.")}</p></div>}
  <Modal isOpen={!!dialog} onClose={()=>{if(!busy)setDialog(undefined);}} title={dialog==="create"?tr("New Project","Proyek Baru"):dialog==="task"?tr("Task Details","Detail Tugas"):dialog==="member"?tr("Add Committee Member","Tambah Panitia"):dialog==="project"?tr("Project Timeline","Jadwal Proyek"):dialog==="invoice"?tr("Project Invoice","Tagihan Proyek"):tr("Record Payment","Catat Pembayaran")}>
   <form className="p11-form" key={`${dialog}-${task?.id||parent}`} onSubmit={e=>void submit(e)}>
    {dialog==="create"&&<><Input name="code" label={tr("Project Code","Kode Proyek")} required maxLength={30}/><Input name="name" label={tr("Project Name","Nama Proyek")} required minLength={2} maxLength={200}/><Input name="description" label={tr("Description","Deskripsi")}/><Select name="template" label={tr("Activity Template","Template Kegiatan")}>{[["CUSTOM",tr("Custom Activity","Kegiatan Lainnya")],["GRADUATION",tr("Graduation","Kelulusan")],["OPEN_HOUSE","Open House"],["SCHOOL_TRIP",tr("School Trip","Kunjungan Belajar")],["SPORTS_DAY",tr("Sports Day","Pekan Olahraga")]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select>{[["CHAIR",tr("Chair / PIC","Ketua / PIC")],["SECRETARY",tr("Secretary","Sekretaris")],["TREASURER",tr("Treasurer","Bendahara")]].map(([k,l])=><PersonPicker key={k} name={k} label={l} users={allUsers.data??[]} required/>)}</>}
    {dialog==="task"&&<><Input name="title" label={tr("Task Name","Nama Tugas")} required minLength={2} maxLength={240} defaultValue={task?.title}/><Input name="description" label={tr("Description","Deskripsi")} defaultValue={task?.description}/><Select name="parent_task_id" label={tr("Parent Task (Optional)","Tugas Induk (Opsional)")} defaultValue={parent}><option value="">{tr("Main task","Tugas utama")}</option>{d?.tasks.filter(t=>!t.parent_task_id&&t.id!==task?.id).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</Select><PeopleCheckboxes users={people.data??[]} selected={task?.assignees.map(a=>a.id)??[]} label={tr("Responsible People","Penanggung Jawab")}/><Select name="priority" label={tr("Priority","Prioritas")} defaultValue={task?.priority??"MEDIUM"}>{["LOWEST","LOW","MEDIUM","HIGH","HIGHEST"].map(v=><option key={v}>{v}</option>)}</Select><Select name="status" label="Status" defaultValue={normalized(task?.status??"TODO")}>{statuses.map((s,i)=><option key={s} value={s}>{labels[i]}</option>)}</Select></>}
    {["create","task","project"].includes(dialog??"")&&<><Input type="date" name="starts_on" label={tr("Start Date","Tanggal Mulai")} defaultValue={dialog==="task"?task?.starts_on:dialog==="project"?d?.project.starts_on:undefined}/><Input type="date" name={dialog==="task"?"due_date":"due_on"} label={tr("Due Date","Batas Waktu")} defaultValue={dialog==="task"?task?.due_date:dialog==="project"?d?.project.due_on:undefined}/></>}
    {dialog==="project"&&<Select name="status" label="Status" defaultValue={d?.project.status}>{["PLANNING","ACTIVE","ON_HOLD","COMPLETED","ARCHIVED"].map(s=><option key={s} disabled={s==="COMPLETED"&&!d?.complete}>{s}</option>)}</Select>}
    {dialog==="member"&&<><PersonPicker name="user_id" label={tr("School User","Pengguna Sekolah")} users={people.data??[]} required/><Select name="position" label={tr("Position","Posisi")}><option value="MEMBER">{tr("Member","Anggota")}</option><option value="COORDINATOR">{tr("Coordinator","Koordinator")}</option></Select></>}
    {dialog==="invoice"&&<><Input name="invoice_number" label={tr("Invoice Number","Nomor Tagihan")} required/><Input name="description" label={tr("Description","Deskripsi")}/><Input name="due_date" type="date" label={tr("Due Date","Jatuh Tempo")} required/></>}
    {dialog==="payment"&&<><Select name="project_invoice_id" label={tr("Invoice","Tagihan")} required><option value="">{tr("Choose invoice","Pilih tagihan")}</option>{d?.invoices.filter(i=>!["PAID","VOID","DRAFT"].includes(i.status)).map(i=><option key={i.id} value={i.id}>{i.invoice_number}</option>)}</Select><Input name="receipt_number" label={tr("Receipt Number","Nomor Kuitansi")} required/></>}
    {["invoice","payment"].includes(dialog??"")&&<Input name="amount" label={tr("Amount (Rp)","Nominal (Rp)")} type="number" min={1} step={1} required/>}
    {error&&<p role="alert" className="school-error">{error}</p>}<Button type="submit" disabled={busy}>{busy?tr("Saving…","Menyimpan…"):tr("Save","Simpan")}</Button>
   </form>
  </Modal>
  <Modal isOpen={!!detail} onClose={()=>setDetail(undefined)} title={detail?.title??""}><p>{detail?.description||tr("No description.","Belum ada deskripsi.")}</p>{d?.comments.filter(c=>c.task_id===detail?.id).map(c=><div className="p11-comment" key={c.id}><strong>{c.name}</strong><p>{c.body}</p></div>)}<form className="p11-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await action("comment",{body:new FormData(form).get("body")},detail?.id))form.reset();}}><Input name="body" label={tr("Comment","Komentar")} required maxLength={4000}/><Button type="submit" disabled={busy}>{tr("Add Comment","Tambah Komentar")}</Button></form>{error&&<p role="alert">{error}</p>}</Modal>
 </section>;
}
function PeopleCheckboxes({users,selected,label}:{users:Person[];selected:string[];label:string}){const [query,setQuery]=useState("");return <fieldset className="p11-people"><legend>{label}</legend><Input aria-label={label} type="search" value={query} onChange={e=>setQuery(e.target.value)}/><div>{users.map(p=><label key={p.id} hidden={!!query&&!p.name.toLowerCase().includes(query.toLowerCase())}><input type="checkbox" name="assignees" value={p.id} defaultChecked={selected.includes(p.id)}/>{p.name}</label>)}</div></fieldset>;}
