"use client";
import { useEffect, useRef, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Download, FileText, Upload } from "lucide-react";
import { schoolRpc } from "../../lib/school";
import { createClient } from "../../lib/supabase/client";
import { usePermissionStore } from "../../stores/permission-store";
import { useTranslations } from "../i18n/i18n-provider";
import { Button } from "../ui";
import { Modal } from "../ui/modal";
import type { ProjectData } from "./project-workspace";
export type Evidence = {name:string;url:string;type:string};
export function ProjectEvidence({data}:{data:ProjectData}){
 const {locale}=useTranslations(),tr=(en:string,id:string)=>locale==="id-ID"?id:en,userId=usePermissionStore(s=>s.context?.userId),cache=useQueryClient();
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[viewer,setViewer]=useState<{url:string;title:string}>(),reportUrl=useRef("");
 useEffect(()=>()=>{if(reportUrl.current)URL.revokeObjectURL(reportUrl.current);},[]);
 const prefix=`${data.project.tenant_id}/${data.project.id}`;
 const documents=useQuery({queryKey:["project-evidence",userId,data.project.id],queryFn:async()=>{const storage=createClient().storage.from("project-evidence");const all:Evidence[]=[];for(let offset=0;;offset+=100){const {data:rows,error}=await storage.list(prefix,{limit:100,offset,sortBy:{column:"created_at",order:"desc"}});if(error)throw error;const files=rows.filter(r=>r.id);if(files.length){const {data:links,error}=await storage.createSignedUrls(files.map(r=>`${prefix}/${r.name}`),3600);if(error)throw error;files.forEach((r,i)=>{if(!links?.[i]?.signedUrl)throw new Error(tr("Unable to open evidence","Gagal membuka dokumentasi"));all.push({name:r.name,url:links[i].signedUrl,type:r.metadata?.mimetype??""});});}if(rows.length<100)break;}return all;},staleTime:1800000});
 async function upload(file:File){setBusy(true);setError("");try{if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(file.type)||file.size>5242880)throw new Error(tr("Choose JPG, PNG, WebP or PDF up to 5 MB.","Pilih JPG, PNG, WebP, atau PDF maksimal 5 MB."));const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_").slice(-120);const {error}=await createClient().storage.from("project-evidence").upload(`${prefix}/${crypto.randomUUID()}-${safe}`,file,{contentType:file.type,upsert:false});if(error)throw error;await cache.invalidateQueries({queryKey:["project-evidence"]});}catch(e){setError(e instanceof Error?e.message:tr("Upload failed","Unggah gagal"));}finally{setBusy(false);}}
 async function report(){setBusy(true);setError("");try{const {projectPdf}=await import("../../lib/project-pdf");const fresh=await schoolRpc<ProjectData>("school_project11",{action:"read",project_uuid:data.project.id});if(!fresh.complete)throw new Error(tr("Some tasks were reopened. Complete them before reporting.","Ada tugas yang dibuka kembali. Selesaikan sebelum membuat laporan."));for(let offset=100;offset<fresh.task_count;offset+=100){const chunk=await schoolRpc<ProjectData>("school_project11",{action:"read",project_uuid:data.project.id,page_offset:offset});fresh.tasks.push(...chunk.tasks);}const bytes=await projectPdf(fresh,documents.data??[],locale);if(reportUrl.current)URL.revokeObjectURL(reportUrl.current);reportUrl.current=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:"application/pdf"}));setViewer({url:reportUrl.current,title:tr("Project Completion Report","Laporan Pelaksanaan Proyek")});}catch(e){setError(e instanceof Error?e.message:tr("Unable to prepare report","Gagal menyiapkan laporan"));}finally{setBusy(false);}}
 return <section className="p11-completion"><header><div><CheckCircle2 size={24}/><h3>{tr("All tasks are complete","Seluruh tugas sudah selesai")}</h3><p>{tr("Add event evidence and prepare the final report.","Tambahkan dokumentasi kegiatan dan siapkan laporan pelaksanaan.")}</p></div><div className="owner-actions">{data.can_manage&&<label className="ose-file-label"><Upload size={17}/>{tr("Upload Documentation","Unggah Dokumentasi")}<input type="file" className="p10-file-input" aria-label={tr("Upload Documentation","Unggah Dokumentasi")} accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value="";}}/></label>}<Button disabled={busy||documents.isLoading||documents.isError} onClick={()=>void report()}><FileText size={17}/>{tr("View Project Report","Lihat Laporan Proyek")}</Button></div></header>
 {(error||documents.isError)&&<p role="alert">{error||documents.error?.message}</p>}<div className="p11-evidence-list">{documents.data?.map(d=><a href={d.url} key={d.name} target="_blank" rel="noopener noreferrer" onClick={e=>{if(d.type==="application/pdf"){e.preventDefault();setViewer({url:d.url,title:d.name.slice(37)});}}}><FileText size={17}/>{d.name.slice(37)}</a>)}</div>
 <Modal isOpen={!!viewer} title={viewer?.title??""} onClose={()=>setViewer(undefined)}>{viewer&&<><a className="ose-link" href={viewer.url} download={`osekola-${data.project.code}-report.pdf`} target="_blank" rel="noopener noreferrer"><Download size={16}/>{tr("Download PDF","Unduh PDF")}</a><iframe title={viewer.title} src={viewer.url} className="p11-pdf-viewer"/><p>{tr("If the preview is unavailable, use Download PDF.","Jika pratinjau tidak tersedia, gunakan Unduh PDF.")}</p></>}</Modal>
 </section>;
}
