"use client";
import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, GraduationCap, Pencil, Trash2 } from "lucide-react";
import { schoolRpc } from "../../lib/school";
import { curriculumCsv, evidenceValue, type CurriculumOption, type CurriculumLearningData, type CurriculumEvidence } from "../../lib/curriculum";
import { usePermissionStore } from "../../stores/permission-store";
import { useTranslations } from "../i18n/i18n-provider";
import { Button, Input, Select } from "../ui";
export function CurriculumLearning({ examMode = false,courseId }: { examMode?: boolean;courseId?:string }) {
 const { locale } = useTranslations(); const id = locale === "id-ID"; const userId = usePermissionStore(s => s.context?.userId);
 const [selected, setSelected] = useState(courseId??"");
 const courses = useQuery({ queryKey: ["curriculum-courses", userId, examMode], enabled: !!userId, queryFn: () => schoolRpc<CurriculumOption[]>("school_curriculum_courses", { exam_mode: examMode }) });
 const course = courses.data?.find(c => c.id === selected) ?? courses.data?.[0];
 return <section className="curriculum-workspace"><header className="school-section-title"><div><p className="ose-eyebrow">{examMode ? "CURRICULUM & ASSESSMENT" : "CURRICULUM & LEARNING"}</p><h2>{id ? "Capaian belajar setiap program" : "Learning outcomes for every programme"}</h2><p>{id ? "Lihat tujuan pembelajaran dan perkembangan sesuai kurikulum yang Anda ikuti." : "Explore learning goals and progress in your curriculum programmes."}</p></div><GraduationCap size={32}/></header>
 {courses.isError && <p role="alert" className="school-error">{courses.error.message}</p>}
 <label className="school-field"><span>Course</span><Select value={course?.id ?? ""} onChange={e => setSelected(e.target.value)} disabled={!!courseId||courses.isLoading}><option value="">{id ? "Pilih course" : "Choose course"}</option>{courses.data?.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Select></label>
 {course ? <CourseCurriculum key={`${course.id}-${examMode}`} course={course} examMode={examMode}/> : <p className="school-empty">{courses.isLoading ? (id ? "Memuat…" : "Loading…") : (id ? "Course akan tampil sesuai kelas atau penugasan mengajar Anda." : "Courses appear for your class or teaching assignments.")}</p>}
 </section>;
}
function CourseCurriculum({ course, examMode }: { course: CurriculumOption; examMode: boolean }) {
 const { locale } = useTranslations(); const id = locale === "id-ID"; const userId = usePermissionStore(s => s.context?.userId); const qc = useQueryClient();
 const [program, setProgram] = useState(""); const [page, setPage] = useState(0); const [student, setStudent] = useState(""); const [tab, setTab] = useState("outcomes"); const [editing, setEditing] = useState<CurriculumEvidence>();
 const q = useQuery({ queryKey: ["curriculum-learning", userId, course.id, examMode, page, program, student], queryFn: () => schoolRpc<CurriculumLearningData>("school_curriculum_learning", { course_uuid: course.id, exam_mode: examMode, evidence_offset: page * 100, evidence_student: student || null, evidence_program: program || null }) });
 const save = useMutation({ mutationFn: ({ resource, payload, recordId }: { resource: string; payload: Record<string, unknown>; recordId?: string }) => schoolRpc("school_curriculum_save", { resource, payload: { ...payload, course_id: course.id }, record_id: recordId ?? null }), onSuccess: async () => { setEditing(undefined); await qc.invalidateQueries({ queryKey: ["curriculum-learning"] }); } });
 const pdf = useMutation({mutationFn:async()=>{
   const evidence:CurriculumEvidence[]=[];
   for(let offset=0;offset<=100000;offset+=100){const r=await schoolRpc<CurriculumLearningData>("school_curriculum_learning",{course_uuid:course.id,exam_mode:examMode,evidence_offset:offset,evidence_student:student||null,evidence_program:program||null});evidence.push(...r.evidence);if(r.evidence.length<100)break;}
   const {reportPdf,downloadPdf}=await import("../../lib/school-pdf");
   downloadPdf(await reportPdf(id?"Laporan capaian pembelajaran":"Learning outcomes report",course.name,[(id?"Diterbitkan: ":"Generated: ")+new Date().toLocaleString(locale),id?"Setiap hasil memakai skala dan versi kurikulum saat penilaian.":"Each result retains its assessed curriculum version and grading scale."],evidence.map(e=>[q.data?.students.find(s=>s.id===e.student_id)?.name??"Student",e.assessment_context.program.name+" · "+e.assessment_context.program.version,e.assessment_context.outcome.code+" · "+e.assessment_context.outcome.name,e.assessment_context.scale.name+": "+evidenceValue(e),e.feedback,e.assessed_at,e.status])),"osekola-learning-outcomes.pdf");
 }});
 const unlink = useMutation({ mutationFn: (alignment: string) => schoolRpc("school_curriculum_unlink", { alignment_uuid: alignment }), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["curriculum-learning"] }); } });
 if (q.isLoading) return <p role="status">{id ? "Memuat kurikulum…" : "Loading curriculum…"}</p>;
 if (!q.data || q.isError) return <div role="alert"><p>{q.error?.message}</p><Button onClick={() => void q.refetch()}>{id ? "Coba lagi" : "Retry"}</Button></div>;
 const data = q.data;
 const outcomes = data.outcomes.filter(o => !program || o.program_id === program);
 const evidence = data.evidence.filter(e => (!program || e.assessment_context.program.id === program) && (!student || e.student_id === student));
 const programs = Array.from(new Map([...data.programs, ...data.evidence.map(e => e.assessment_context.program)].map(p => [p.id, p])).values());
 const download = () => { const url = URL.createObjectURL(new Blob(["\uFEFF", curriculumCsv(evidence, data.students)], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "curriculum-progress.csv"; a.click(); URL.revokeObjectURL(url); };
 return <div><div className="school-toolbar"><Select aria-label={id ? "Program kurikulum" : "Curriculum programme"} value={program} onChange={e => { setProgram(e.target.value); setPage(0); }}><option value="">{id ? "Semua program" : "All programmes"}</option>{programs.map(p => <option key={p.id} value={p.id}>{p.name} · {p.version}</option>)}</Select>{data.can_manage && <Select aria-label={id ? "Filter siswa" : "Filter student"} value={student} onChange={e => { setStudent(e.target.value); setPage(0); }}><option value="">{id ? "Semua siswa" : "All students"}</option>{data.students.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</Select>}</div>
 <nav className="school-tabs" aria-label={id ? "Kurikulum course" : "Course curriculum"}>{[["outcomes", id ? "Capaian & keterkaitan" : "Outcomes & alignment"], ["progress", id ? "Perkembangan & laporan" : "Progress & report"]].map(([key, label]) => <button key={key} type="button" aria-current={tab === key ? "page" : undefined} onClick={() => setTab(key)}>{label}</button>)}</nav>
 {!programs.length && <p className="school-empty">{id ? "Program belum dipetakan ke course ini. Staf atau guru dapat mengaturnya melalui Academic → Kurikulum." : "This course has no programme mappings yet. Staff or teachers can configure them in Academic → Curriculum."}</p>}
 {tab === "outcomes" ? <><div className="curriculum-outcomes">{outcomes.map(o => <article key={o.id} className="school-record"><div className="school-record-main"><p className="ose-eyebrow">{data.programs.find(p => p.id === o.program_id)?.name} · {o.kind} · {o.code}</p><h3>{o.sequence}. {o.name}</h3><p>{o.description}</p><small>{o.strand} · {o.activity_type.replaceAll("_", " ")}</small>{data.alignments.filter(a => a.outcome_id === o.id).map(a => <div key={a.id} className="curriculum-alignment"><span>{a.purpose} · {data.lessons.find(r => r.id === a.lesson_id)?.name ?? data.assignments.find(r => r.id === a.assignment_id)?.name ?? data.question_sets.find(r => r.id === a.question_set_id)?.name ?? data.exams.find(r => r.id === a.exam_id)?.name ?? course.name}{a.notes && ` — ${a.notes}`}</span>{data.can_manage && <Button variant="ghost" aria-label={id ? "Hapus keterkaitan" : "Remove alignment"} disabled={unlink.isPending} onClick={() => unlink.mutate(a.id)}><Trash2 size={15}/></Button>}</div>)}</div></article>)}</div>
 {data.can_manage && outcomes.length > 0 && <AlignmentForm key={program} data={{ ...data, outcomes }} examMode={examMode} pending={save.isPending} onSave={payload => save.mutate({ resource: "alignments", payload })}/>}</> : <>
 <div className="school-toolbar"><Button variant="ghost" disabled={!evidence.length} onClick={download}><Download size={16}/>{id ? "Unduh halaman laporan CSV" : "Download report page CSV"}</Button><Button variant="ghost" disabled={pdf.isPending} onClick={()=>pdf.mutate()}><Download size={16}/>{pdf.isPending?"…":"Download PDF"}</Button>{pdf.isError&&<p role="alert">{pdf.error.message}</p>}<p>{id ? "Setiap hasil memakai skala programnya sendiri." : "Each result uses its own programme scale."}</p></div>
 <div className="curriculum-outcomes">{evidence.map(e => <article className="school-record" key={e.id}><div className="school-record-main"><p className="ose-eyebrow">{e.assessment_context.program.name} · {e.assessment_context.program.version} · {e.status}</p><h3>{e.assessment_context.outcome.code} · {e.assessment_context.outcome.name}</h3>{data.can_manage && <strong>{data.students.find(s => s.id === e.student_id)?.name}</strong>}<p>{e.assessment_context.scale.name}: <strong>{evidenceValue(e)}</strong></p><p>{e.feedback}</p><small>{e.assessed_at} · {e.assessment_context.subject.name}</small></div>{data.can_manage && <Button variant="ghost" aria-label={id ? "Edit penilaian" : "Edit assessment"} onClick={() => setEditing(e)}><Pencil size={16}/></Button>}</article>)}</div>
 {!evidence.length && <p className="school-empty">{id ? "Belum ada hasil penilaian pada pilihan ini." : "No assessment results for this selection."}</p>}
 <div className="school-pagination"><Button variant="ghost" disabled={!page || q.isFetching} onClick={() => setPage(p => p - 1)}>←</Button><span>{id ? "Halaman" : "Page"} {page + 1}</span><Button variant="ghost" disabled={data.evidence.length < 100 || q.isFetching} onClick={() => setPage(p => p + 1)}>→</Button></div>{data.can_manage && data.outcomes.length > 0 && <EvidenceForm key={editing?.id ?? "new"} data={data} examMode={examMode} editing={editing} pending={save.isPending} onCancel={() => setEditing(undefined)} onSave={payload => save.mutate({ resource: "evidence", payload, recordId: editing?.id })}/>}
 </>}
 {(save.isError || unlink.isError) && <p role="alert" className="school-error">{save.error?.message ?? unlink.error?.message}</p>}{save.isSuccess && <p role="status">{id ? "Tersimpan." : "Saved."}</p>}
 </div>;
}
function Choices({ name, label, options, optional, value, defaultValue, onChange, disabled }: { name: string; label: string; options: CurriculumOption[]; optional?: boolean; value?: string; defaultValue?: string; onChange?: (v: string) => void; disabled?: boolean }) {
 return <label className="school-field"><span>{label}</span><Select name={name} required={!optional} value={value} defaultValue={defaultValue} disabled={disabled} onChange={onChange ? e => onChange(e.target.value) : undefined}><option value="">{label}</option>{options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</Select></label>;
}
function AlignmentForm({ data, examMode, pending, onSave }: { data: CurriculumLearningData; examMode: boolean; pending: boolean; onSave: (p: Record<string, unknown>) => void }) {
 const { locale } = useTranslations(); const id = locale === "id-ID"; const [type, setType] = useState(examMode ? "exam_id" : "course");
 const resources = type === "lesson_id" ? data.lessons : type === "assignment_id" ? data.assignments : type === "question_set_id" ? data.question_sets : data.exams;
 function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); onSave({ outcome_id: f.get("outcome"), purpose: f.get("purpose"), notes: f.get("notes") || null, ...(type !== "course" ? { [type]: f.get("resource") } : {}) }); }
 return <form className="school-editor" onSubmit={submit}><h3>{id ? "Hubungkan capaian" : "Align an outcome"}</h3><Choices name="outcome" label={id ? "Capaian pembelajaran" : "Learning outcome"} options={data.outcomes.map(o => ({ ...o, name: `${o.code} · ${o.name}` }))}/>
 <label className="school-field"><span>{id ? "Hubungkan ke" : "Align to"}</span><Select value={type} onChange={e => setType(e.target.value)}>{(examMode ? [["exam_id", id ? "Ujian" : "Exam"]] : [["course", "Course"], ["lesson_id", "Lesson"], ["assignment_id", "Assignment"], ["question_set_id", id ? "Bank soal" : "Question set"]]).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select></label>
 {type !== "course" && <Choices key={type} name="resource" label={id ? "Materi / penilaian" : "Learning / assessment resource"} options={resources}/>}
 <Choices name="purpose" label={id ? "Tujuan keterkaitan" : "Alignment purpose"} options={[{ id: "TEACH", name: id ? "Diajarkan" : "Teach" }, { id: "PRACTICE", name: id ? "Latihan" : "Practice" }, { id: "ASSESS", name: id ? "Dinilai" : "Assess" }]}/><Input name="notes" label={id ? "Catatan (opsional)" : "Notes (optional)"} maxLength={3000}/><Button disabled={pending} type="submit">{pending ? "…" : id ? "Simpan keterkaitan" : "Save alignment"}</Button></form>;
}
function EvidenceForm({ data, examMode, editing, pending, onSave, onCancel }: { data: CurriculumLearningData; examMode: boolean; editing?: CurriculumEvidence; pending: boolean; onSave: (p: Record<string, unknown>) => void; onCancel: () => void }) {
 const { locale } = useTranslations(); const id = locale === "id-ID"; const [outcomeId, setOutcome] = useState(editing?.outcome_id ?? ""); const [scaleId, setScale] = useState(editing?.scale_id ?? "");
 const outcome = data.outcomes.find(o => o.id === outcomeId); const scales = data.scales.filter(s => s.program_id === outcome?.program_id); const scale = scales.find(s => s.id === scaleId);
 function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const numeric = scale?.kind === "NUMERIC" || scale?.kind === "RUBRIC"; onSave({ student_id: editing?.student_id ?? f.get("student"), outcome_id: outcomeId, scale_id: scaleId, [examMode ? "exam_id" : "assignment_id"]: f.get("resource") || null, score: numeric ? Number(f.get("score")) : null, descriptor: numeric ? null : f.get("descriptor"), feedback: f.get("feedback"), assessed_at: f.get("date"), status: f.get("status") }); }
 return <form className="school-editor" onSubmit={submit}><h3>{editing ? (id ? "Edit penilaian" : "Edit assessment") : (id ? "Catat bukti capaian" : "Record outcome evidence")}</h3>
 <Choices name="student" label={id ? "Siswa" : "Student"} options={data.students} value={editing?.student_id} disabled={!!editing}/>
 <Choices name="outcome" label={id ? "Capaian pembelajaran" : "Learning outcome"} options={data.outcomes.map(o => ({ ...o, name: `${data.programs.find(p => p.id === o.program_id)?.name} · ${o.code} · ${o.name}` }))} value={outcomeId} disabled={!!editing} onChange={v => { setOutcome(v); setScale(""); }}/>
 <Choices name="scale" label={id ? "Skala program" : "Programme scale"} options={scales} value={scaleId} disabled={!!editing} onChange={setScale}/>
 {scale && <><p>{scale.criteria}</p>{["NUMERIC", "RUBRIC"].includes(scale.kind) ? <Input key={scale.id} name="score" label={`${id ? "Nilai" : "Score"} (${scale.minimum}–${scale.maximum})`} type="number" step="0.01" min={scale.minimum ?? undefined} max={scale.maximum ?? undefined} defaultValue={editing?.score ?? ""} required/> : <Choices key={scale.id} name="descriptor" label={id ? "Predikat / deskripsi" : "Grade / descriptor"} options={scale.labels.map(l => ({ id: l, name: l }))} defaultValue={editing?.descriptor ?? undefined}/>}</>}
 <Choices name="resource" label={examMode ? (id ? "Ujian" : "Exam") : (id ? "Tugas (opsional)" : "Assignment (optional)")} options={examMode ? data.exams : data.assignments} optional={!examMode} defaultValue={(examMode ? editing?.exam_id : editing?.assignment_id) ?? undefined}/>
 <Input name="date" label={id ? "Tanggal penilaian" : "Assessment date"} type="date" defaultValue={editing?.assessed_at ?? new Date().toISOString().slice(0, 10)} required/>
 <label className="school-field"><span>{id ? "Bukti & umpan balik" : "Evidence & feedback"}</span><textarea name="feedback" rows={4} maxLength={10000} defaultValue={editing?.feedback} required/></label>
 <label className="school-field"><span>{id ? "Visibilitas hasil" : "Result visibility"}</span><Select name="status" defaultValue={editing?.status ?? "DRAFT"}><option value="DRAFT">{id ? "Draf — hanya guru" : "Draft — teachers only"}</option><option value="PUBLISHED">{id ? "Publikasikan ke siswa" : "Publish to student"}</option></Select></label>
 <div className="flex gap-3"><Button type="submit" disabled={pending || !scale}>{pending ? "…" : id ? "Simpan penilaian" : "Save assessment"}</Button>{editing && <Button type="button" variant="ghost" onClick={onCancel}>{id ? "Batal edit" : "Cancel edit"}</Button>}</div>
 </form>;
}
