"use client";
import { useState } from "react";
import { FilePlus, Pencil, Plus } from "lucide-react";
import { useTranslations } from "../i18n/i18n-provider";
import { amount, date, useOwnerList, useOwnerSave, useOwnerSummary, value, type OwnerRow } from "../../lib/owner";
import { Button, Select } from "../ui";
import { plans } from "./owner-tenants";
import { OwnerDialog, OwnerForm, OwnerHeading, OwnerMetric, OwnerSearch, OwnerShell, OwnerStatus, OwnerTable, type OwnerField } from "./owner-ui";

type Editor = { kind: "contract" | "invoice" | "receipt" | "expense"; row?: OwnerRow };
function invoiceDefaults(row: OwnerRow): OwnerRow {
  const start = new Date((value(row, "invoice_period_end") || value(row, "onboarded_on") || new Date().toISOString().slice(0, 10)) + "T12:00:00Z");
  if (row.invoice_period_end) start.setUTCDate(start.getUTCDate() + 1);
  const end = new Date(start); end.setUTCMonth(end.getUTCMonth() + ({ MONTHLY: 1, QUARTERLY: 3, YEARLY: 12 }[value(row, "billing_period")] ?? 1)); end.setUTCDate(end.getUTCDate() - 1);
  return { ...row, period_start: start.toISOString().slice(0, 10), period_end: end.toISOString().slice(0, 10) > value(row, "expires_on") ? value(row, "expires_on") : end.toISOString().slice(0, 10), due_on: start.toISOString().slice(0, 10), amount: row.period_amount };
}
export function FinanceEditor({ editor, close }: { editor: Editor; close: () => void }) {
  const { t } = useTranslations(); const save = useOwnerSave(); const [requestId] = useState(() => crypto.randomUUID()); const { kind, row } = editor;
  const billing = [{ value: "MONTHLY", label: t("ownerMonthly") }, { value: "QUARTERLY", label: t("ownerQuarterly") }, { value: "YEARLY", label: t("ownerYearly") }];
  const fields: OwnerField[] = kind === "contract" ? [
    { key: "onboarded_on", label: "ownerOnboarding", type: "date", required: true }, { key: "expires_on", label: "ownerExpiry", type: "date", required: true },
    { key: "billing_period", label: "ownerBillingPeriod", options: billing, required: true }, { key: "annual_amount", label: "ownerAnnualAmount", type: "number", min: 0, required: true }, { key: "period_amount", label: "ownerPeriodAmount", type: "number", min: 0, required: true },
  ] : kind === "invoice" ? [
    { key: "period_start", label: "ownerPeriodStart", type: "date", required: true }, { key: "period_end", label: "ownerPeriodEnd", type: "date", required: true }, { key: "due_on", label: "ownerDueDate", type: "date", required: true },
    { key: "amount", label: "ownerAmount", type: "number", min: 0.01, required: true }, { key: "notes", label: "ownerNotes" },
  ] : [...(kind === "expense" ? [{ key: "description", label: "ownerDescription" as const, required: true }] : []), { key: "amount", label: "ownerAmount", type: "number", min: 0.01, max: kind === "receipt" ? Number(row?.balance) : undefined, required: true }, { key: "paid_on", label: "ownerPaidOn", type: "date", required: true }, { key: "reference", label: "ownerReference", required: true }];
  return <OwnerDialog title={t({ contract: "ownerContract", invoice: "ownerCreateInvoice", receipt: "ownerRecordReceipt", expense: "ownerRecordExpense" }[kind] as "ownerContract")} close={close}><p className="owner-dialog-description">{row && (value(row, "name") || value(row, "tenant_name"))}</p><OwnerForm fields={fields} initial={kind === "invoice" && row ? invoiceDefaults(row) : kind === "receipt" ? { id: "", amount: row?.balance, paid_on: new Date().toISOString().slice(0, 10) } : row} pending={save.isPending} error={save.error?.message} saveLabel={kind === "invoice" ? t("ownerCreateAndNotify") : undefined} submit={payload => save.mutate({ kind, id: kind === "invoice" ? undefined : row?.id, payload: kind === "invoice" ? { ...payload, tenant_id: row?.id, request_id: requestId } : payload }, { onSuccess: close })}>{kind === "invoice" && <p className="owner-help">{t("ownerInvoiceNotice")}</p>}{kind === "receipt" && <p className="owner-help">{t("ownerReceiptHelp")}</p>}</OwnerForm></OwnerDialog>;
}
function FinanceLedger({ kind, close }: { kind: "income" | "expenses" | "receivables"; close: () => void }) {
  const { t, locale } = useTranslations(); const [page, setPage] = useState(1); const [source, setSource] = useState(kind === "income" ? "receipts" : kind === "expenses" ? "expenses" : "invoices"); const [status, setStatus] = useState(""); const [editor, setEditor] = useState<Editor>();
  const q = useOwnerList(source, { status: source === "commissions" ? "RECEIVED" : status }, page);
  const label = { income: "ownerIncome", expenses: "ownerExpenses", receivables: "ownerReceivables" } as const;
  return <OwnerDialog title={t(label[kind])} close={close} wide><div className="owner-toolbar">{kind === "expenses" ? <><Select aria-label={t("ownerCategory")} value={source} onChange={e => { setSource(e.target.value); setPage(1); }}><option value="expenses">{t("ownerOperatingExpenses")}</option><option value="commissions">{t("ownerPartnerFees")}</option></Select><Button onClick={() => setEditor({ kind: "expense" })}><Plus size={16}/>{t("ownerRecordExpense")}</Button></> : kind === "receivables" && <Select aria-label={t("ownerInvoiceStatus")} value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">{t("ownerAllInvoices")}</option><option value="OPEN">{t("ownerOpen")}</option><option value="OVERDUE">{t("ownerOverdue")}</option><option value="PAID">{t("ownerPaid")}</option></Select>}</div>
    <OwnerTable headers={[t("ownerDescription"), t("ownerAmount"), t("ownerDate"), t("ownerActions")]} list={q.data} loading={q.isPending} error={q.isError} retry={() => void q.refetch()} page={page} setPage={setPage}>{q.data?.items.map(row => <tr key={row.id}><td><strong>{value(row, "number") || value(row, "description") || value(row, "reference") || t("ownerPartnerFees")}</strong><small>{value(row, "tenant_name") || value(row, "invoice_number")}</small></td><td>{amount(row.amount, locale)}{source === "invoices" && <small>{t("ownerBalance")}: {amount(row.balance, locale)}</small>}</td><td>{date(row.paid_on || row.received_at || row.due_on, locale)}</td><td>{source === "invoices" ? <div className="owner-actions"><OwnerStatus status={row.status}/><Button size="sm" disabled={Number(row.balance) <= 0} onClick={() => setEditor({ kind: "receipt", row })}>{t("ownerRecordReceipt")}</Button></div> : <OwnerStatus status="PAID"/>}</td></tr>)}</OwnerTable>{editor && <FinanceEditor editor={editor} close={() => setEditor(undefined)}/>}</OwnerDialog>;
}
export function OwnerFinance() {
  const { t, locale } = useTranslations(); const [query, setQuery] = useState(""); const [plan, setPlan] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [editor, setEditor] = useState<Editor>(); const [ledger, setLedger] = useState<"income" | "expenses" | "receivables">();
  const q = useOwnerList("finance", { query, plan, invoice_status: status }, page); const summary = useOwnerSummary();
  const periods: Record<string, string> = { MONTHLY: t("ownerMonthly"), QUARTERLY: t("ownerQuarterly"), YEARLY: t("ownerYearly") };
  return <OwnerShell><OwnerHeading title="ownerFinance" description="ownerFinanceDesc"/>{summary.isError ? <p role="alert">{t("loadError")}</p> : <div className="owner-metrics">{(["income", "expenses", "receivables"] as const).map((key, i) => <OwnerMetric key={key} label={t((["ownerIncome", "ownerExpenses", "ownerReceivables"] as const)[i])} value={summary.data ? amount(summary.data[key], locale) : "…"} detail={key === "receivables" ? `${t("ownerOverdue")}: ${summary.data ? amount(summary.data.overdue, locale) : "…"}` : t("ownerViewDetails")} onClick={() => setLedger(key)}/>)}</div>}
    <OwnerSearch query={query} setQuery={v => { setQuery(v); setPage(1); }}><Select aria-label={t("ownerPlan")} value={plan} onChange={e => { setPlan(e.target.value); setPage(1); }}><option value="">{t("ownerAllPlans")}</option>{plans.map(p => <option key={p}>{p}</option>)}</Select><Select aria-label={t("ownerInvoiceStatus")} value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">{t("ownerAllInvoices")}</option>{["PAID", "OPEN", "OVERDUE", "NONE"].map((s, i) => <option key={s} value={s}>{t((["ownerPaid", "ownerOpen", "ownerOverdue", "ownerNoInvoice"] as const)[i])}</option>)}</Select></OwnerSearch>
    <OwnerTable headers={[t("ownerTenant"), t("ownerPlan"), t("ownerOnboarding"), t("ownerExpiry"), t("ownerBillingPeriod"), t("ownerAnnualAmount"), t("ownerPeriodAmount"), t("ownerLatestInvoice"), t("ownerActions")]} list={q.data} loading={q.isPending} error={q.isError} retry={() => void q.refetch()} page={page} setPage={setPage}>{q.data?.items.map(row => <tr key={row.id}><td><strong>{value(row, "name")}</strong><small>{value(row, "code")}</small></td><td>{value(row, "plan_code")}</td><td>{date(row.onboarded_on, locale)}</td><td>{date(row.expires_on, locale)}</td><td>{periods[value(row, "billing_period")] || "—"}</td><td>{row.annual_amount == null ? "—" : amount(row.annual_amount, locale)}</td><td>{row.period_amount == null ? "—" : amount(row.period_amount, locale)}</td><td><OwnerStatus status={row.invoice_status}/><small>{value(row, "invoice_number")}</small></td><td><div className="owner-actions"><Button size="sm" variant="ghost" onClick={() => setEditor({ kind: "contract", row })}><Pencil size={15}/>{t("ownerContract")}</Button><Button size="sm" disabled={!row.onboarded_on || !row.is_active} onClick={() => setEditor({ kind: "invoice", row })}><FilePlus size={15}/>{t("ownerCreateInvoice")}</Button></div></td></tr>)}</OwnerTable>
    {editor && <FinanceEditor editor={editor} close={() => setEditor(undefined)}/>} {ledger && <FinanceLedger kind={ledger} close={() => setLedger(undefined)}/>}
  </OwnerShell>;
}
