"use client";
import { useState, type FormEvent } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { usePlans } from "../school/growth-public";
import { schoolRpc } from "../../lib/school";
import { OwnerShell, OwnerDialog } from "./owner-ui";
import { useTranslations } from "../i18n/i18n-provider";
import { Button, Input } from "../ui";
export type Product = {code:string;name:string;price_monthly:number;features:string[];features_en:string[];offer_note:string;offer_note_en:string;discount_percent:number;custom_pricing:boolean};
export function OwnerProducts() {
 const {locale,t}=useTranslations(); const id=locale==="id-ID"; const q=usePlans(); const cache=useQueryClient(); const [editing,setEditing]=useState<Product>();
 const save=useMutation({mutationFn:(payload:Record<string,unknown>)=>schoolRpc("school_product_save",{payload}),onSuccess:async()=>{setEditing(undefined);await cache.invalidateQueries({queryKey:["public-plans"]});}});
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({code:editing!.code,name:f.get("name"),price_monthly:Number(f.get("price_monthly")),discount_percent:Number(f.get("discount_percent")),custom_pricing:f.get("custom_pricing")==="on",features:String(f.get("features")).split("\n").map(s=>s.trim()).filter(Boolean),features_en:String(f.get("features_en")).split("\n").map(s=>s.trim()).filter(Boolean),offer_note:f.get("offer_note"),offer_note_en:f.get("offer_note_en")});}
 return <OwnerShell><div className="owner-heading"><div><h2>{t("ownerProduct")}</h2><p>{id?"Tiga segmen produk. Perubahan tampil langsung pada paket di landing page.":"Three product segments. Changes appear in the landing page plans."}</p></div></div>{q.isError?<p role="alert">{t("loadError")} <Button onClick={()=>void q.refetch()}>{t("retry")}</Button></p>:<div className="school-pricing-grid">{q.data?.map(p=><article key={p.code} className="school-plan"><small>{p.code}</small><h3>{p.name}</h3><p>{new Intl.NumberFormat(locale,{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(p.price_monthly)}</p><p>{id?"Diskon":"Discount"}: {p.discount_percent}%</p><ul>{(id?p.features:p.features_en).map(f=><li key={f}>{f}</li>)}</ul><Button onClick={()=>{save.reset();setEditing(p);}}>{t("edit")}</Button></article>)}</div>}{editing&&<OwnerDialog wide title={editing.name} close={()=>setEditing(undefined)}><form className="owner-form" onSubmit={submit}><Input name="name" label={id?"Nama produk":"Product name"} defaultValue={editing.name} required minLength={2} maxLength={100}/><Input name="price_monthly" label={id?"Harga / siswa / bulan (Rp)":"Price / student / month (IDR)"} type="number" min={0} max={2147483647} defaultValue={editing.price_monthly} required/><Input name="discount_percent" label={id?"Diskon (%)":"Discount (%)"} type="number" min={0} max={100} step="0.01" defaultValue={editing.discount_percent} required/>{["features","features_en"].map(key=><label key={key} className="school-field"><span>{key==="features"?"Fitur Bahasa Indonesia — satu per baris":"English features — one per line"}</span><textarea name={key} defaultValue={(editing[key as "features"|"features_en"]??[]).join("\n")} required rows={6} maxLength={9000}/></label>)}<Input name="offer_note" label="Penawaran Bahasa Indonesia" defaultValue={editing.offer_note} maxLength={1000}/><Input name="offer_note_en" label="English offer" defaultValue={editing.offer_note_en} maxLength={1000}/><label className="school-consent"><input name="custom_pricing" type="checkbox" defaultChecked={editing.custom_pricing}/>{id?"Tawarkan penyesuaian paket dan harga":"Offer a tailored package and price"}</label>{save.isError&&<p role="alert">{save.error.message}</p>}<Button type="submit" disabled={save.isPending}>{t("save")}</Button></form></OwnerDialog>}</OwnerShell>;
}
