"use client";
import { useState } from "react";
import { ExternalLink, Plus } from "lucide-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useTranslations } from "../i18n/i18n-provider";
import { amount, date, useOwnerList, useOwnerSave, value, type OwnerRow } from "../../lib/owner";
import { schoolRpc } from "../../lib/school";
import { Button, Input, Select } from "../ui";
import { OwnerDialog, OwnerForm, OwnerHeading, OwnerSearch, OwnerShell, OwnerStatus, OwnerTable, StatusFilter, type OwnerField } from "./owner-ui";

function PartnerEditor({ row, close }: { row?: OwnerRow; close: () => void }) {
  const { t } = useTranslations(); const save = useOwnerSave(); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const users = useOwnerList("users", { query: search, status: "ACTIVE" }, page, !row);
  const fields: OwnerField[] = [{ key: "name", label: "ownerName", required: true }, ...(!row ? [{ key: "user_id", label: "ownerAccount" as const, required: true, options: (users.data?.items ?? []).map(u => ({ value: u.id, label: `${value(u, "full_name")} · ${value(u, "email")}` })) }, { key: "referral_code", label: "ownerReferralCode" as const, required: true }] : []), { key: "domicile", label: "ownerDomicile" }, { key: "phone", label: "ownerPhone" }, { key: "bank_name", label: "ownerBank" }, { key: "bank_account_name", label: "ownerAccountName" }, { key: "bank_account_number", label: "ownerAccountNumber" }, { key: "payment_url", label: "ownerGatewayURL", type: "url" }];
  return <OwnerDialog title={t(row ? "ownerEditPartner" : "ownerAddPartner")} close={close} wide>{!row && <><Input label={t("ownerSearchAccount")} value={search} onChange={e => { setSearch(e.target.value); setPage(1); }}/><div className="owner-actions"><Button size="sm" variant="ghost" disabled={page === 1} onClick={() => setPage(page - 1)}>{t("ownerPrevious")}</Button><span>{page}</span><Button size="sm" variant="ghost" disabled={!users.data || page * 20 >= users.data.total} onClick={() => setPage(page + 1)}>{t("ownerNext")}</Button></div>{users.isError && <p role="alert">{t("loadError")}</p>}</>}
    <OwnerForm fields={fields} initial={row} pending={save.isPending} error={save.error?.message} submit={data => { const payload = Object.fromEntries(Object.entries(data).map(([k, v]) => [k, k === "payment_url" ? v : v ?? ""])); save.mutate({ kind: "partner", id: row?.id, payload }, { onSuccess: close }); }}><p className="owner-help">{t("ownerGatewayHelp")}</p></OwnerForm></OwnerDialog>;
}
function PartnerDetails({ row, close }: { row: OwnerRow; close: () => void }) {
  const { t, locale } = useTranslations(); const [tab, setTab] = useState("commissions"); const [page, setPage] = useState(1); const [editing, setEditing] = useState(false); const [payment, setPayment] = useState<OwnerRow>(); const [commission, setCommission] = useState<OwnerRow>(); const save = useOwnerSave(); const cache = useQueryClient();
  const current = useOwnerList("partners", { id: row.id }); const partner = current.data?.items.find(p => p.id === row.id) ?? row;
  const details = useOwnerList(tab, { partner_id: row.id }, page);
  const gateway = useMutation({ mutationFn: () => schoolRpc<string>("school_owner_payment_link", { partner_id: row.id }), onSuccess: url => { const parsed = new URL(url); if (parsed.protocol === "https:" && !parsed.username && !parsed.password) window.location.assign(url); } });
  const lead = useMutation({ mutationFn: ({ id, stage }: { id: string; stage: string }) => schoolRpc("school_growth_save", { kind: "lead", record_id: id, payload: { stage } }), onSuccess: () => cache.invalidateQueries({ queryKey: ["owner"] }) });
  return <OwnerDialog title={value(partner, "name")} close={close} wide><div className="owner-detail-top"><div><OwnerStatus status={partner.status}/><p>{value(partner, "domicile") || "—"}</p><p>{value(partner, "phone") || "—"} · {value(partner, "email")}</p><p>{value(partner, "bank_name") || "—"} · {value(partner, "bank_account_number") || "—"}</p><small>{value(partner, "bank_account_name")}</small></div><Button variant="ghost" onClick={() => setEditing(true)}>{t("ownerEdit")}</Button></div>
    <div className="owner-detail-metrics">{(["earned", "paid", "unpaid"] as const).map((key, i) => <div key={key}><span>{t((["ownerEarned", "ownerPaidFees", "ownerUnpaidFees"] as const)[i])}</span><strong>{amount(partner[key], locale)}</strong></div>)}</div>
    <div className="owner-toolbar"><Select aria-label={t("ownerCategory")} value={tab} onChange={e => { setTab(e.target.value); setPage(1); }}><option value="commissions">{t("ownerPartnerFees")}</option><option value="leads">{t("ownerLeads")}</option></Select><Button disabled={Number(partner.unpaid) <= 0 || !partner.payment_url || gateway.isPending} onClick={() => gateway.mutate()}><ExternalLink size={16}/>{t("ownerSendPayment")}</Button></div>
    {!partner.payment_url && <p className="owner-help">{t("ownerGatewayMissing")}</p>}{(gateway.isError || lead.isError) && <p role="alert" className="school-error">{gateway.error?.message || lead.error?.message}</p>}
    <OwnerTable headers={[tab === "leads" ? t("ownerTenant") : t("ownerPartnerFees"), t("ownerStatus"), t("ownerActions")]} list={details.data} loading={details.isPending} error={details.isError} retry={() => void details.refetch()} page={page} setPage={setPage}>{details.data?.items.map(item => <tr key={item.id}><td>{tab === "leads" ? <><strong>{value(item, "school_name")}</strong><small>{value(item, "contact_name")} · {value(item, "phone")}</small><small>{value(item, "email")}</small></> : <><strong>{amount(item.amount, locale)}</strong><small>{value(item, "reference") || "—"} · {date(item.received_at, locale)}</small></>}</td><td>{tab === "leads" ? <Select aria-label={`${t("ownerStage")} ${value(item, "school_name")}`} value={value(item, "stage")} disabled={lead.isPending} onChange={e => lead.mutate({ id: item.id, stage: e.target.value })}>{["NEW", "CONTACTED", "DEMO", "PROPOSAL", "WON", "LOST"].map(s => <option key={s}>{s}</option>)}</Select> : <OwnerStatus status={item.status}/>}</td><td>{tab === "leads" ? <Button size="sm" disabled={item.stage !== "WON"} onClick={() => { save.reset(); setCommission(item); }}>{t("ownerAddFee")}</Button> : <Button size="sm" disabled={item.status === "RECEIVED"} onClick={() => { save.reset(); setPayment(item); }}>{t("ownerRecordPayment")}</Button>}</td></tr>)}</OwnerTable>
    {editing && <PartnerEditor row={partner} close={() => setEditing(false)}/>}
    {payment && <OwnerDialog title={t("ownerRecordPayment")} close={() => setPayment(undefined)}><p>{amount(payment.amount, locale)}</p><OwnerForm fields={[{ key: "reference", label: "ownerReference", required: true }]} pending={save.isPending} error={save.error?.message} submit={payload => save.mutate({ kind: "commission_paid", id: payment.id, payload }, { onSuccess: () => setPayment(undefined) })}><p className="owner-help">{t("ownerReceiptHelp")}</p></OwnerForm></OwnerDialog>}
    {commission && <OwnerDialog title={t("ownerAddFee")} close={() => setCommission(undefined)}><p>{value(commission, "school_name")}</p><OwnerForm fields={[{ key: "amount", label: "ownerAmount", type: "number", required: true, min: 0.01 }]} pending={save.isPending} error={save.error?.message} submit={payload => save.mutate({ kind: "commission", payload: { ...payload, partner_id: row.id, lead_id: commission.id } }, { onSuccess: () => setCommission(undefined) })}/></OwnerDialog>}
  </OwnerDialog>;
}
export function OwnerPartners() {
  const { t } = useTranslations(); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [selected, setSelected] = useState<OwnerRow>(); const [adding, setAdding] = useState(false); const q = useOwnerList("partners", { query, status }, page); const save = useOwnerSave();
  return <OwnerShell><OwnerHeading title="ownerPartner" description="ownerPartnerDesc"><Button onClick={() => setAdding(true)}><Plus size={17}/>{t("ownerAddPartner")}</Button></OwnerHeading><OwnerSearch query={query} setQuery={v => { setQuery(v); setPage(1); }}><StatusFilter status={status} change={v => { setStatus(v); setPage(1); }}/></OwnerSearch>{save.isError && <p role="alert" className="school-error">{save.error.message}</p>}
    <OwnerTable headers={[t("ownerName"), t("ownerDomicile"), t("ownerLeads"), t("ownerClosings"), t("ownerSuccessRate"), t("ownerStatus"), t("ownerActions")]} list={q.data} loading={q.isPending} error={q.isError} retry={() => void q.refetch()} page={page} setPage={setPage}>{q.data?.items.map(row => <tr key={row.id}><td><button className="owner-name" onClick={() => setSelected(row)}>{value(row, "name")}</button><small>{value(row, "referral_code")}</small></td><td>{value(row, "domicile") || "—"}</td><td>{value(row, "leads")}</td><td>{value(row, "closings")}</td><td>{value(row, "success_rate")}%</td><td><OwnerStatus status={row.status}/></td><td><Button size="sm" variant="ghost" disabled={save.isPending} onClick={() => save.mutate({ kind: "partner", id: row.id, payload: { is_active: !row.is_active } })}>{t(row.is_active ? "ownerDeactivate" : "ownerActivate")}</Button></td></tr>)}</OwnerTable>
    {selected && <PartnerDetails row={selected} close={() => setSelected(undefined)}/>} {adding && <PartnerEditor close={() => setAdding(false)}/>}
  </OwnerShell>;
}
