-- Phase 39: Team+ tasks.
create table public.team_tasks (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete restrict,
  project_id uuid not null references public.team_projects(id) on delete cascade,
  task_number bigint generated by default as identity,
  title text not null check (char_length(trim(title)) between 2 and 240),
  description text,
  status text not null default 'BACKLOG'
    check (status in ('BACKLOG', 'TODO', 'IN_PROGRESS', 'REVIEW', 'DONE')),
  priority text not null default 'MEDIUM'
    check (priority in ('LOWEST', 'LOW', 'MEDIUM', 'HIGH', 'HIGHEST')),
  assignee_user_id uuid references public.users(id) on delete set null,
  reporter_user_id uuid not null references public.users(id) on delete restrict,
  due_date date,
  sort_order numeric(14,4) not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (tenant_id, task_number)
);

create index team_tasks_board_idx
  on public.team_tasks (tenant_id, project_id, status, sort_order, created_at);
create index team_tasks_assignee_idx
  on public.team_tasks (tenant_id, assignee_user_id, due_date);

alter table public.team_tasks enable row level security;
revoke all on public.team_tasks from anon, authenticated;
create policy team_tasks_select_tenant on public.team_tasks
  for select to authenticated
  using (tenant_id = public.current_tenant_id());

insert into public.permissions (code, name, description)
values
  ('team_tasks.read', 'Read Team+ tasks', 'View project boards and task details'),
  ('team_tasks.create', 'Create Team+ tasks', 'Create tasks in Team+ projects'),
  ('team_tasks.update', 'Update Team+ tasks', 'Maintain, assign, and move Team+ tasks'),
  ('team_tasks.delete', 'Delete Team+ tasks', 'Delete Team+ tasks')
on conflict (code) do update
set name = excluded.name,
    description = excluded.description,
    updated_at = timezone('utc', now());

insert into public.role_permissions (role_id, permission_id)
select role.id, permission.id
from public.roles role
cross join public.permissions permission
where role.code in ('OWNER', 'PRINCIPAL', 'STAFF', 'TEACHER')
  and permission.code like 'team_tasks.%'
on conflict (role_id, permission_id) do nothing;
