import { BadRequestException, ConflictException, Injectable, InternalServerErrorException, NotFoundException } from "@nestjs/common";
import { AuditService } from "../audit/audit.service";
import { SupabaseService } from "../../common/supabase/supabase.service";
type Resource="academic_years"|"semesters"|"classrooms"|"subjects";
@Injectable() export class AcademicService {
 constructor(private readonly supabase:SupabaseService,private readonly audit:AuditService){}
 private get client(){return this.supabase.getClient();}
 private async tenant(userId:string){const {data,error}=await this.client.from("users").select("tenant_id,is_active").eq("id",userId).single();if(error||!data?.tenant_id||!data.is_active)throw new NotFoundException("Active tenant user not found");return data.tenant_id as string;}
 private async validRelation(resource:Resource,tenantId:string,input:object){if(resource!=="semesters"&&resource!=="classrooms")return;const {data}=await this.client.from("academic_years").select("id").eq("id",(input as {academic_year_id?:string}).academic_year_id ?? "").eq("tenant_id",tenantId).single();if(!data)throw new BadRequestException("Academic year does not belong to the current tenant");}
 async list(userId:string,resource:Resource){const tenantId=await this.tenant(userId);const {data,error}=await this.client.from(resource).select("*").eq("tenant_id",tenantId).order("name");if(error)throw new InternalServerErrorException("Failed to fetch academic records");return data??[];}
 async create(userId:string,resource:Resource,dto:object){const tenantId=await this.tenant(userId);await this.validRelation(resource,tenantId,dto);const input=dto as {name?:unknown};const values={...dto,tenant_id:tenantId,name:typeof input.name==='string'?input.name.trim():input.name};const {data,error}=await this.client.from(resource).insert(values).select("*").single();if(error?.code==='23505')throw new ConflictException("A record with this name or code already exists");if(error||!data)throw new InternalServerErrorException("Failed to create academic record");await this.audit.record({tenantId,actorUserId:userId,action:"CREATE",module:"ACADEMIC",resourceType:resource,resourceId:data.id,afterState:data});return data;}
 async update(userId:string,resource:Resource,id:string,dto:object){const tenantId=await this.tenant(userId);const {data:before}=await this.client.from(resource).select("*").eq("id",id).eq("tenant_id",tenantId).single();if(!before)throw new NotFoundException("Academic record not found");await this.validRelation(resource,tenantId,dto);const values=Object.fromEntries(Object.entries(dto).filter(([,v])=>v!==undefined).map(([k,v])=>[k,typeof v==='string'&&k==='name'?v.trim():v]));if(!Object.keys(values).length)throw new BadRequestException("At least one field is required");const {data,error}=await this.client.from(resource).update(values).eq("id",id).eq("tenant_id",tenantId).select("*").single();if(error?.code==='23505')throw new ConflictException("A record with this name or code already exists");if(error||!data)throw new InternalServerErrorException("Failed to update academic record");await this.audit.record({tenantId,actorUserId:userId,action:"UPDATE",module:"ACADEMIC",resourceType:resource,resourceId:id,beforeState:before,afterState:data});return data;}
 async remove(userId:string,resource:Resource,id:string){const tenantId=await this.tenant(userId);const {data:before}=await this.client.from(resource).select("*").eq("id",id).eq("tenant_id",tenantId).single();if(!before)throw new NotFoundException("Academic record not found");const {error}=await this.client.from(resource).delete().eq("id",id).eq("tenant_id",tenantId);if(error)throw new ConflictException("This record is still in use and cannot be deleted");await this.audit.record({tenantId,actorUserId:userId,action:"DELETE",module:"ACADEMIC",resourceType:resource,resourceId:id,beforeState:before});return {success:true,id};}
}
