// Photography is illustrative; all product copy describes existing module capabilities.
export const moduleStories = {
  "o-core": { en: ["A calmer start to every school day.", "School calendar & accounts"], id: ["Awali hari sekolah dengan lebih tertata.", "Kalender & akun sekolah"], position: "66% 42%" },
  "o-academic": { en: ["Every class, on the same page.", "Classes & curriculum"], id: ["Selaraskan setiap kelas dan rencana belajar.", "Kelas & kurikulum"], position: "55% 40%" },
  "o-attendance": { en: ["Arrive. Scan. Ready to learn.", "Live face attendance"], id: ["Datang. Pindai. Siap belajar.", "Presensi wajah langsung"], position: "32% 40%" },
  "o-learning": { en: ["Let curiosity keep going.", "Lessons & assignments"], id: ["Ruang untuk terus ingin tahu.", "Materi & tugas belajar"], position: "57% 40%" },
  "o-exam": { en: ["Give every achievement a clear picture.", "Online exams & results"], id: ["Lihat setiap capaian dengan lebih jelas.", "Ujian online & hasil"], position: "53% 40%" },
  "o-finance": { en: ["School bills, settled from home.", "Easy parent payments"], id: ["Tagihan sekolah, beres dari rumah.", "Pembayaran mudah oleh orang tua"], position: "45% 40%" },
  "o-team": { en: ["Great school days start with a team.", "Projects & shared tasks"], id: ["Hari sekolah yang baik dimulai dari tim.", "Proyek & tugas bersama"], position: "51% 40%" },
  "o-connect": { en: ["A closer connection, one message away.", "Parent & teacher chat"], id: ["Lebih dekat, cukup lewat satu pesan.", "Chat orang tua & guru"], position: "37% 40%" },
} as const;

export const marketingFaqs = [
  { key: "schools", en: ["Is OSEKOLA suitable for our school?", "OSEKOLA brings academic administration, learning, attendance, finance, teamwork, and communication together. Start with your school's priorities; our team can help map the modules and access for your teachers, staff, students, and parents."], id: ["Apakah OSEKOLA cocok untuk sekolah kami?", "OSEKOLA menyatukan administrasi akademik, pembelajaran, presensi, keuangan, kerja tim, dan komunikasi. Mulai dari prioritas sekolah Anda; tim kami dapat membantu memetakan modul serta akses guru, staf, siswa, dan orang tua."] },
  { key: "start", en: ["How do we get started?", "Book a free demo or complete the School Digital Maturity assessment. We will discuss your current processes, school size, and priorities, then agree on the setup, data preparation, and support your team needs."], id: ["Bagaimana cara mulai menggunakan OSEKOLA?", "Jadwalkan demo gratis atau isi assessment School Digital Maturity. Kami akan membahas proses, jumlah siswa, dan prioritas sekolah, lalu menyepakati pengaturan, persiapan data, serta pendampingan yang dibutuhkan tim Anda."] },
  { key: "curricula", en: ["Can we use more than one curriculum?", "Yes. A school can configure multiple programmes, including Kurikulum Merdeka, Cambridge, Pearson Edexcel, and IB, by academic year, class, or student. Each programme keeps its own learning outcomes and grading scales. Your school supplies its syllabus and assessment policies."], id: ["Bisakah satu sekolah memakai beberapa kurikulum?", "Bisa. Sekolah dapat mengatur beberapa program, termasuk Kurikulum Merdeka, Cambridge, Pearson Edexcel, dan IB, per tahun ajaran, kelas, atau siswa. Setiap program memiliki capaian belajar dan skala penilaian sendiri. Sekolah menyiapkan silabus serta kebijakan penilaiannya."] },
  { key: "attendance", en: ["How does face attendance work?", "Staff or teachers guide face enrollment and verification using a device camera, with the required consent, including a guardian's consent for children. Enrolled users can then check in with a face scan. Manual attendance remains available when a camera is unsuitable."], id: ["Bagaimana presensi pengenalan wajah bekerja?", "Staf atau guru mendampingi pendaftaran dan verifikasi wajah melalui kamera perangkat, dengan persetujuan yang diperlukan, termasuk persetujuan wali untuk anak. Pengguna yang sudah terdaftar dapat melakukan presensi dengan pemindaian wajah. Presensi manual tetap tersedia jika kamera tidak mendukung."] },
  { key: "parents", en: ["What can parents access?", "Parents can follow information about their own children, view published reports and attendance, check bills, and chat with teachers through the access granted by the school. They do not need to navigate the school's administrative workspace."], id: ["Apa saja yang dapat diakses orang tua?", "Orang tua dapat mengikuti informasi anaknya sendiri, melihat laporan yang sudah diterbitkan dan kehadiran, mengecek tagihan, serta berbincang dengan guru sesuai akses dari sekolah. Mereka tidak perlu membuka ruang kerja administrasi sekolah."] },
  { key: "payments", en: ["Can parents pay school bills online?", "Yes, once the school activates its supported payment provider. Parents open an outstanding bill, continue to the available checkout, and check the payment status in OSEKOLA. Payment methods and any provider fees depend on the school's merchant setup."], id: ["Bisakah orang tua membayar tagihan sekolah secara online?", "Bisa, setelah sekolah mengaktifkan penyedia pembayaran yang didukung. Orang tua membuka tagihan yang belum lunas, melanjutkan ke pembayaran yang tersedia, lalu mengecek statusnya di OSEKOLA. Metode dan biaya penyedia pembayaran mengikuti pengaturan merchant sekolah."] },
  { key: "access", en: ["How is access to school information managed?", "Access follows each user's role and school. Teachers, staff, students, and parents see the information and tools permitted for them. Parents are linked to their own children, and private files are available through authenticated access."], id: ["Bagaimana akses informasi sekolah diatur?", "Akses mengikuti peran pengguna dan sekolahnya. Guru, staf, siswa, dan orang tua melihat informasi serta alat yang diizinkan untuk mereka. Orang tua dihubungkan dengan anaknya sendiri, dan berkas privat tersedia melalui akses yang memerlukan autentikasi."] },
  { key: "plans", en: ["Can the plan grow with our school?", "Discuss your student count, required modules, and support needs with our team. The plans shown above provide a starting point, and tailored features or pricing can be discussed for your school or foundation."], id: ["Apakah paket bisa mengikuti perkembangan sekolah?", "Diskusikan jumlah siswa, modul, dan kebutuhan pendampingan dengan tim kami. Paket di atas menjadi titik awal, dan penyesuaian fitur atau harga dapat dibahas sesuai kebutuhan sekolah atau yayasan Anda."] },
] as const;
