export const demoUrl = "https://wa.me/6285110511078?text=Saya%20ingin%20menjadwalkan%20demo%20gratis%20OSEKOLA%20untuk%20sekolah%20kami.";
export const marketingModules = [
  { id: "o-core", name: "O-Core", icon: "core", idCopy: ["Satu pusat untuk seluruh sekolah.", "Satukan identitas sekolah, akun, agenda, dan informasi penting dalam ruang kerja yang tertata.", "Profil dan identitas sekolah", "Akun pengguna dan akses berdasarkan peran", "Pusat notifikasi dan kalender", "Media sekolah dengan akses terpisah"], enCopy: ["One home for your school.", "Bring school identity, accounts, schedules, and important updates into one organized workspace.", "School profile and identity", "User accounts and role-based access", "Notification and calendar centers", "Isolated school media storage"] },
  { id: "o-academic", name: "O-Academic", icon: "academic", idCopy: ["Akademik rapi, sekolah siap bergerak.", "Tata fondasi kegiatan belajar agar guru dan pengelola sekolah bekerja dengan informasi yang selaras.", "Tahun ajaran dan semester", "Kelas dan mata pelajaran", "Data guru dan siswa", "Penugasan guru dan penempatan siswa"], enCopy: ["Organized academics. A school ready to grow.", "Build a clear foundation for learning so teachers and school teams work from the same information.", "Academic years and semesters", "Classrooms and subjects", "Teacher and student records", "Teacher assignments and student placement"] },
  { id: "o-attendance", name: "O-Attendance", icon: "attendance", idCopy: ["Setiap kehadiran lebih berarti.", "Bantu sekolah mencatat kehadiran secara konsisten dan menindaklanjuti ketidakhadiran dengan lebih cepat.", "Presensi guru dan siswa", "Sesi presensi dengan QR", "Status hadir, terlambat, izin, dan absen", "Riwayat kehadiran per kelas"], enCopy: ["Every school day counts.", "Record attendance consistently and help your team follow up on absences sooner.", "Teacher and student attendance", "QR attendance sessions", "Present, late, excused, and absent statuses", "Class attendance history"] },
  { id: "o-learning", name: "O-Learning", icon: "learning", idCopy: ["Belajar berlanjut, di mana pun.", "Hubungkan materi, tugas, dan pengumpulan pekerjaan agar proses belajar lebih terarah.", "Pengelolaan kursus dan materi", "Publikasi pelajaran", "Tugas dan pengumpulan pekerjaan", "Penyimpanan berkas pembelajaran"], enCopy: ["Keep learning, wherever you are.", "Connect lessons, assignments, and submissions to make the learning journey easier to follow.", "Course and learning material management", "Lesson publishing", "Assignments and submissions", "Learning file storage"] },
  { id: "o-exam", name: "O-Exam", icon: "exam", idCopy: ["Penilaian terencana, hasil lebih jelas.", "Siapkan ujian dan kelola hasil penilaian dalam alur yang mudah ditelusuri.", "Bank soal dan pengelolaan ujian", "Jadwal dan sesi ujian", "Hasil ujian siswa", "Tinjauan soal oleh guru"], enCopy: ["Planned assessments. Clearer results.", "Prepare exams and manage assessment results through an easy-to-follow workflow.", "Question bank and exam management", "Exam schedules and sessions", "Student exam results", "Teacher question review"] },
  { id: "o-finance", name: "O-Finance", icon: "finance", idCopy: ["Keuangan sekolah lebih tertata.", "Dari tagihan hingga pembayaran, bantu tim administrasi memahami posisi keuangan sekolah.", "Akun, kategori, dan periode keuangan", "Tagihan siswa", "Pencatatan dan status pembayaran", "Laporan keuangan"], enCopy: ["School finances, brought into focus.", "From invoices to payments, give your administration team a clearer view of school finances.", "Finance accounts, categories, and periods", "Student billing", "Payment records and statuses", "Financial reports"] },
  { id: "o-team", name: "O-Team", icon: "team", idCopy: ["Tim kompak, rencana jadi nyata.", "Koordinasikan proyek dan pekerjaan sekolah dalam ruang kolaborasi yang terarah.", "Proyek dan anggota tim", "Tugas dan progres pekerjaan", "Pengaturan akses proyek", "Keuangan dan dokumen proyek"], enCopy: ["Aligned teams. Plans into progress.", "Coordinate school projects and everyday work in a focused collaborative space.", "Projects and team members", "Tasks and work progress", "Project access settings", "Project finances and documents"] },
] as const;
export const marketingCopy = {
  "id-ID": { title: "Sekolah lebih terhubung.", accent: "Belajar lebih bermakna.", intro: "Satukan akademik, pembelajaran, dan operasional sekolah dalam satu ekosistem. OSEKOLA membantu sekolah dan yayasan memberi ruang lebih besar untuk hal yang terpenting: perkembangan setiap siswa.", contact: "Bicarakan kebutuhan sekolah", modules: "Tujuh modul. Satu ekosistem.", moduleHint: "Pilih modul untuk mengenal fiturnya.", details: "Lihat fitur", close: "Tutup detail modul", features: "Yang bisa Anda kelola", closing: "Guru lebih fokus. Siswa lebih terarah. Orang tua lebih terhubung.", closingCopy: "Bangun pengalaman sekolah yang sederhana dan konsisten, dari kelas hingga rumah.", contactTitle: "Mari mulai dari sekolah Anda.", contactCopy: "Diskusikan kebutuhan sekolah atau yayasan bersama tim OSEKOLA.", office: "Kantor pusat", soon: "Segera tersedia di", rights: "Hak cipta dilindungi.", demo: "Jadwalkan demo gratis" },
  "en-US": { title: "A more connected school.", accent: "More meaningful learning.", intro: "Bring academics, learning, and school operations into one ecosystem. OSEKOLA helps schools and foundations make more room for what matters most: every student's growth.", contact: "Talk about your school", modules: "Seven modules. One ecosystem.", moduleHint: "Choose a module to explore its features.", details: "Explore features", close: "Close module details", features: "What you can manage", closing: "Focused teachers. Engaged students. Connected parents.", closingCopy: "Build a simple, consistent school experience, from classroom to home.", contactTitle: "Let's start with your school.", contactCopy: "Discuss your school or foundation's needs with the OSEKOLA team.", office: "Head office", soon: "Coming soon to", rights: "All rights reserved.", demo: "Book a free demo" },
};
