import { PDFDocument, StandardFonts, rgb, type PDFPage } from "pdf-lib";
import type { ProjectData } from "../components/part11/project-workspace";
import type { Evidence } from "../components/part11/project-evidence";
const safe=(s:unknown)=>String(s??"—").replace(/[\u2010-\u2015]/g,"-").replace(/[^\x20-\x7e\xa0-\xff\n]/g," ");
export async function projectPdf(data:ProjectData,evidence:Evidence[],locale:string){
 const tr=(en:string,id:string)=>locale==="id-ID"?id:en,doc=await PDFDocument.create(),regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold),ink=rgb(.07,.12,.19),blue=rgb(.004,.49,1);
 doc.setTitle(`${data.project.name} - Project Report`);doc.setAuthor("OSEKOLA");
 let page!:PDFPage,y=0;
 function add(){page=doc.addPage([595.28,841.89]);y=747;page.drawText("OSEKOLA / O-TEAM",{x:44,y:790,size:11,font:bold,color:blue});page.drawLine({start:{x:44,y:777},end:{x:550,y:777},color:rgb(.8,.85,.9),thickness:1});}
 function ensure(h:number){if(y-h<55)add();}
 function text(value:unknown,size=10,strong=false){const font=strong?bold:regular;for(const para of safe(value).split("\n")){let line="";for(const c of para){if(line&&font.widthOfTextAtSize(line+c,size)>507){ensure(size+7);page.drawText(line,{x:44,y,size,font,color:ink});y-=size+7;line="";}line+=c;}ensure(size+7);page.drawText(line,{x:44,y,size,font,color:ink});y-=size+7;}y-=4;}
 function section(title:string){ensure(65);y-=12;text(title,14,true);}
 const money=(n:number)=>`Rp ${n.toLocaleString("id-ID")}`;
 add();text(tr("Project Completion Report","Laporan Pelaksanaan Proyek"),22,true);text(data.project.name,16,true);text(`${data.project.code} | ${data.project.status} | ${new Date().toLocaleDateString(locale)}`);
 section(tr("1. Project Details","1. Detail Proyek"));text(data.project.description||tr("No description","Tanpa deskripsi"));text(`${tr("Timeline","Jadwal")}: ${data.project.starts_on||"—"} - ${data.project.due_on||"—"}`);text(`${tr("Completed Tasks","Tugas Selesai")}: ${data.tasks.filter(t=>t.status==="DONE").length}/${data.task_count}`);
 section(tr("2. Committee","2. Panitia"));data.committee.forEach(p=>text(`${p.position}: ${p.name}`));
 section(tr("3. Activity Timeline","3. Timeline Kegiatan"));for(const task of data.tasks){text(`${task.parent_task_id?"  + ":""}${task.title}`,11,true);text(`${task.starts_on||"—"} - ${task.due_date||"—"} | ${task.status} | PIC: ${task.assignees.map(p=>p.name).join(", ")||"—"}`);if(task.description)text(task.description);}
 section(tr("4. Project Financial Report","4. Laporan Keuangan Proyek"));const invoiced=data.invoices.filter(i=>!["DRAFT","VOID"].includes(i.status)).reduce((s,i)=>s+Number(i.amount),0),paid=data.payments.filter(p=>p.status==="CONFIRMED").reduce((s,p)=>s+Number(p.amount),0);text(`${tr("Invoiced","Ditagihkan")}: ${money(invoiced)} | ${tr("Received","Diterima")}: ${money(paid)} | ${tr("Outstanding","Sisa Tagihan")}: ${money(Math.max(0,invoiced-paid))}`,11,true);data.invoices.forEach(i=>text(`${i.invoice_number} | ${i.description||""} | ${i.due_date} | ${i.status} | ${money(Number(i.amount))}`));data.payments.forEach(p=>text(`${p.receipt_number} | ${p.paid_at.slice(0,10)} | ${p.status} | ${money(Number(p.amount))}`));if(!data.invoices.length&&!data.payments.length)text(tr("No project financial transactions recorded.","Belum ada transaksi keuangan proyek."));
 section(tr("5. Event Documentation","5. Dokumentasi Kegiatan"));if(!evidence.length)text(tr("No documentation uploaded.","Belum ada dokumentasi yang diunggah."));for(const item of evidence){ensure(65);text(item.name.slice(37),10,true);if(item.type==="image/png"||item.type==="image/jpeg"){const response=await fetch(item.url);if(!response.ok)throw new Error(tr("An evidence file could not be loaded. Refresh and retry.","Dokumentasi gagal dimuat. Muat ulang dan coba lagi."));const bytes=await response.arrayBuffer(),img=item.type==="image/png"?await doc.embedPng(bytes):await doc.embedJpg(bytes);const scale=Math.min(507/img.width,290/img.height,1),w=img.width*scale,h=img.height*scale;ensure(h+18);page.drawImage(img,{x:44,y:y-h,width:w,height:h});y-=h+18;}else if(item.type==="application/pdf"){text(tr("Attached PDF: available in the project documentation section.","Lampiran PDF: tersedia pada bagian dokumentasi proyek."));}else text(tr("Image available in the project documentation section.","Gambar tersedia pada bagian dokumentasi proyek."));}
 section(tr("6. Approval and Signatures","6. Pengesahan dan Tanda Tangan"));text(tr("Place / date: ______________________________","Tempat / tanggal: ______________________________"));for(const position of ["CHAIR","SECRETARY","TREASURER"]){ensure(85);text(`${position}: ${data.committee.find(p=>p.position===position)?.name||"________________"}`,11,true);y-=35;text("Signature / Tanda tangan: ______________________________");}
 for(const [i,p] of doc.getPages().entries())p.drawText(`${i+1} / ${doc.getPageCount()}`,{x:500,y:30,size:8,font:regular,color:ink});return doc.save();
}
